### ISSUE TITLE
向Excel中写入数据时报NullPointerException

### ISSUE THREAD

**Issue by weeklynote** [alibaba/easyexcel#1033]
版本：2.1.4

使用
EasyExcel.write(excelName,clazz).sheet(sheetName).doWrite(dataList);

java.lang.NullPointerException: null
	at com.alibaba.excel.ExcelWriter.finish(ExcelWriter.java:328) ~[easyexcel-2.1.4.jar:na]
	at com.alibaba.excel.ExcelWriter.finalize(ExcelWriter.java:338) ~[easyexcel-2.1.4.jar:na]
	at java.lang.System$2.invokeFinalize(System.java:1270) [na:1.8.0_144]
	at java.lang.ref.Finalizer.runFinalizer(Finalizer.java:98) [na:1.8.0_144]
	at java.lang.ref.Finalizer.access$100(Finalizer.java:34) [na:1.8.0_144]
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:210) [na:1.8.0_144]

**Comment by zhuangjiaju** [comment]
请提供详细代码

**Comment by zhuangjiaju** [comment]
是否已经解决问题了？如果未解决 请重新打开问题。

**Comment by fightingyuman** [comment]
@weeklynote 你解决了这个问题吗？我们也遇到了，是不是数据格式的问题呀？
