### ISSUE TITLE
麻烦看下这个问题,实在定位不到问题,跪谢

### ISSUE THREAD

**Issue by aiwthao** [alibaba/easyexcel#1044]
Exception in thread "STATUS-EXPORT-thread-1" java.lang.NullPointerException
at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)
at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219)
at sun.awt.FontConfiguration.init(FontConfiguration.java:107)
at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:774)
at sun.font.SunFontManager$2.run(SunFontManager.java:431)
at java.security.AccessController.doPrivileged(Native Method)
at sun.font.SunFontManager.<init>(SunFontManager.java:376)
at sun.awt.FcFontManager.<init>(FcFontManager.java:35)
at sun.awt.X11FontManager.<init>(X11FontManager.java:57)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at java.lang.Class.newInstance(Class.java:442)
at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83)
at java.security.AccessController.doPrivileged(Native Method)
at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
at java.awt.Font.getFont2D(Font.java:491)
at java.awt.Font.canDisplayUpTo(Font.java:2060)
at java.awt.font.TextLayout.singleFont(TextLayout.java:470)
at java.awt.font.TextLayout.<init>(TextLayout.java:531)
at org.apache.poi.ss.util.SheetUtil.getDefaultCharWidth(SheetUtil.java:273)
at org.apache.poi.xssf.streaming.AutoSizeColumnTracker.<init>(AutoSizeColumnTracker.java:117)
at org.apache.poi.xssf.streaming.SXSSFSheet.<init>(SXSSFSheet.java:82)
at org.apache.poi.xssf.streaming.SXSSFWorkbook.createAndRegisterSXSSFSheet(SXSSFWorkbook.java:661)
at org.apache.poi.xssf.streaming.SXSSFWorkbook.createSheet(SXSSFWorkbook.java:682)
at org.apache.poi.xssf.streaming.SXSSFWorkbook.createSheet(SXSSFWorkbook.java:92)
at com.alibaba.excel.util.WorkBookUtil.createSheet(WorkBookUtil.java:66)
at com.alibaba.excel.context.WriteContextImpl.initSheet(WriteContextImpl.java:154)
at com.alibaba.excel.context.WriteContextImpl.currentSheet(WriteContextImpl.java:131)
at com.alibaba.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl.java:56)
at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:161)
at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:146)
at com.beantechs.tsp.backend.service.service.impl.VehicleStatusDebugService.export(VehicleStatusDebugService.java:330)
at com.beantechs.tsp.backend.service.controller.debug.vehicle.VehicleStatusDebugController.lambda$export$0(VehicleStatusDebugController.java:117)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

相同的代码 在windows平台上完美运行,在linux上一直报空指针?
猜测是字体问题,但又不知道怎么去解决,求大佬给点建议,跪谢跪谢

**Comment by aiwthao** [comment]
问题 已解决 ,我来分享下,由于我们公司用的是openJDK(很坑爹的玩意),缺少了很多必要的组件,此原因是由于字体配置组件确实导致的
解决方案:
再dockergfile中添加 相关依赖
RUN apk add --no-cache ttf-dejavu
