### ISSUE TITLE
多次执行测试用例imageWrite(),前几次能成功，后几次运行失败

### ISSUE THREAD

**Issue by dota17** [alibaba/easyexcel#1147]
**触发场景描述**
多次执行测试用例imageWrite(),前几次能成功，后几次运行失败，运行失败后打开对应是生成的Excel文件，提示文件损坏。
**触发Bug的代码**
```java
   这里写代码
```
**提示的异常或者没有达到的效果**
2020-03-10 19:29:47.864 DEBUG [main] com.alibaba.excel.context.WriteContextImpl:78 - Begin to Initialization 'WriteContextImpl'
2020-03-10 19:29:47.879 DEBUG [main] com.alibaba.excel.metadata.property.ExcelHeadProperty:95 - The initialization sheet/table 'ExcelHeadProperty' is complete , head kind is CLASS
2020-03-10 19:29:47.895 DEBUG [main] com.alibaba.excel.context.WriteContextImpl:97 - CurrentConfiguration is writeWorkbookHolder
2020-03-10 19:29:48.176 DEBUG [main] com.alibaba.excel.context.WriteContextImpl:89 - Initialization 'WriteContextImpl' complete
2020-03-10 19:29:48.176 DEBUG [main] com.alibaba.excel.metadata.property.ExcelHeadProperty:95 - The initialization sheet/table 'ExcelHeadProperty' is complete , head kind is CLASS
2020-03-10 19:29:48.176 DEBUG [main] com.alibaba.excel.context.WriteContextImpl:145 - CurrentConfiguration is writeSheetHolder
2020-03-10 19:29:48.176 DEBUG [main] com.alibaba.excel.context.WriteContextImpl:181 - Can not find sheet:0 ,now create it
2020-03-10 19:29:49.660 DEBUG [main] com.alibaba.excel.context.WriteContextImpl:362 - Finished write.

com.alibaba.excel.exception.ExcelDataConvertException: Convert data:https://raw.githubusercontent.com/alibaba/easyexcel/master/src/test/resources/converter/img.jpg error,at row:1

	at com.alibaba.excel.write.executor.AbstractExcelWriteExecutor.doConvert(AbstractExcelWriteExecutor.java:117)
	at com.alibaba.excel.write.executor.AbstractExcelWriteExecutor.convert(AbstractExcelWriteExecutor.java:93)
	at com.alibaba.excel.write.executor.AbstractExcelWriteExecutor.converterAndSet(AbstractExcelWriteExecutor.java:39)
	at com.alibaba.excel.write.executor.ExcelWriteAddExecutor.addJavaObjectToExcel(ExcelWriteAddExecutor.java:137)
	at com.alibaba.excel.write.executor.ExcelWriteAddExecutor.addOneRowOfDataToExcel(ExcelWriteAddExecutor.java:65)
	at com.alibaba.excel.write.executor.ExcelWriteAddExecutor.add(ExcelWriteAddExecutor.java:51)
	at com.alibaba.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl.java:61)
	at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:161)
	at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:146)
	at com.alibaba.excel.write.builder.ExcelWriterSheetBuilder.doWrite(ExcelWriterSheetBuilder.java:190)
	at com.alibaba.easyexcel.test.demo.write.WriteTest.imageWrite(WriteTest.java:229)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
	at sun.security.ssl.SSLSocketImpl.waitForClose(SSLSocketImpl.java:1761)
	at sun.security.ssl.HandshakeOutStream.flush(HandshakeOutStream.java:124)
	at sun.security.ssl.Handshaker.kickstart(Handshaker.java:1079)
	at sun.security.ssl.SSLSocketImpl.kickstartHandshake(SSLSocketImpl.java:1479)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1346)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at java.net.URL.openStream(URL.java:1057)
	at com.alibaba.excel.converters.url.UrlImageConverter.convertToExcelData(UrlImageConverter.java:42)
	at com.alibaba.excel.converters.url.UrlImageConverter.convertToExcelData(UrlImageConverter.java:20)
	at com.alibaba.excel.write.executor.AbstractExcelWriteExecutor.doConvert(AbstractExcelWriteExecutor.java:113)
	... 32 more

Process finished with exit code -1

**Comment by dota17** [comment]
问题已经解决了，报错的原因是在根据url下载图片时网络连接超时，改下网络设置就好了。
