### ISSUE TITLE
参照文档 web下载的demo 出现一个异常

### ISSUE THREAD

**Issue by WorkAccounthjj** [alibaba/easyexcel#1153]
**触发场景描述**

**触发Bug的代码**
```java
@RequestMapping("download")
	public ModelAndView download(HttpServletResponse response, Date startCreateTime,Date endCreateTime) {
		try {
			ServletOutputStream outputStream = response.getOutputStream();
			String fileName = URLEncoder.encode("("+ DateUtil.formatDateTime(startCreateTime)+" - "+DateUtil.formatDateTime(endCreateTime) +")", "UTF-8");
			List<QuizPlanData> quizPlanData = packageData(startCreateTime, endCreateTime);
			if (CollectionUtil.isNotEmpty(quizPlanData)){
				EasyExcel.write(outputStream, QuizPlanData.class).sheet("33").doWrite(quizPlanData);
			}else {
				return ajaxFailure("无符合条件的数据!");
			}
			response.setHeader("Content-disposition", "attachment;filename=" + fileName + ".xlsx");
			response.setContentType("application/vnd.ms-excel");
			response.setCharacterEncoding("utf-8");
			return ajaxSuccess("获取成功!", false);
		} catch (Exception e) {
			logger.error("查询区间 [{}] - [{}] 方案详情异常", DateUtil.formatDateTime(startCreateTime),DateUtil.formatDateTime(endCreateTime),e);
		}
		return ajaxFailure("查询异常!");
	}

**提示的异常或者没有达到的效果**
```java
`java.lang.IllegalStateException: getOutputStream() has already been called for this response
	at org.apache.catalina.connector.Response.getWriter(Response.java:564)
	at org.apache.catalina.connector.ResponseFacade.getWriter(ResponseFacade.java:212)
	at javax.servlet.ServletResponseWrapper.getWriter(ServletResponseWrapper.java:109)
	at org.apache.jasper.runtime.JspWriterImpl.initOut(JspWriterImpl.java:115)
	at org.apache.jasper.runtime.JspWriterImpl.flushBuffer(JspWriterImpl.java:108)
	at org.apache.jasper.runtime.PageContextImpl.release(PageContextImpl.java:176)
	at org.apache.jasper.runtime.JspFactoryImpl.internalReleasePageContext(JspFactoryImpl.java:120)
	at org.apache.jasper.runtime.JspFactoryImpl.releasePageContext(JspFactoryImpl.java:75)
	at org.apache.jsp.WEB_002dINF.jsp.ajaxDone_jsp._jspService(ajaxDone_jsp.java:149)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:438)
	at org.apache.jasper.servlet.JspServlet._serviceJspFile(JspServlet.java:396)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:40001)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:716)
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:584)
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:523)
	at org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:160)
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1257)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1037)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:980)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.__invoke(StandardContextValve.java:94)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:40002)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1132)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2527)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2516)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)`
```

**Comment by zhuangjiaju** [comment]
返回参数改成`void`

**Comment by InGitHubChild** [comment]
改成void也不生效，是 response.getOutputStream() 以及  out.write()。不能同时存在吧。本来想一行代码导出excel的..

**Comment by InGitHubChild** [comment]
我的代码如下
 public void exportExcel(SysHistoryVO historyVo,HttpServletResponse response) {
        //查询数
        List<HistoryTemplete> historyTempletes =  sysHistoryMapper.selectByParam(historyVo);
        try {
            response.setContentType("application/vnd.ms-excel");
            response.setCharacterEncoding("utf-8");
            // 这里URLEncoder.encode可以防止中文乱码 当然和easyexcel没有关系
            String fileName = URLEncoder.encode("测试", "UTF-8");
            response.setHeader("Content-disposition", "attachment;filename=" + fileName + ".xlsx");
            ExcelWriterBuilder write = EasyExcel.write(response.getOutputStream(), HistoryTemplete.class);
            ExcelWriterSheetBuilder aaa = write.sheet("模板");
            aaa.doWrite(historyTempletes);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

执行了这行代码
ExcelWriterSheetBuilder aaa = write.sheet("模板");
代码跑到这里时，会报错


com.alibaba.fastjson.JSONException: write javaBean error, class org.springframework.security.web.header.HeaderWriterFilter$HeaderWriterResponse, fieldName : response, write javaBean error, class org.springframework.security.web.context.HttpSessionSecurityContextRepository$SaveToSessionResponseWrapper, fieldName : response, write javaBean error, class org.springframework.security.web.firewall.FirewalledResponse, fieldName : response, getOutputStream() has already been called for this response
	at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:326) ~[lfasr-sdk-client-2.0.0.1005-jar-with-dependencies.jar:?]
	at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:304) ~[lfasr-sdk-client-2.0.0.1005-jar-with-dependencies.jar:?]
	at com.alibaba.fastjson.serializer.ASMSerializer_7_StatHttpServletResponseWrapper.write(Unknown Source) ~[?:?]
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:275) ~[lfasr-sdk-client-2.0.0.1005-jar-with-dependencies.jar:?]
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:637) ~[lfasr-sdk-client-2.0.0.1005-jar-with-dependencies.jar:?]
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:579) ~[lfasr-sdk-client-2.0.0.1005-jar-with-dependencies.jar:?]
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:544) ~[lfasr-sdk-client-2.0.0.1005-jar-with-dependencies.jar:?]
