### ISSUE TITLE
写Excel时单元格内换行问题

### ISSUE THREAD

**Issue by naihewuxiao** [alibaba/easyexcel#1164]
**异常代码**
```java

//自定义存储数据类
   @Data
public class TestExcelData {
    @ExcelProperty(index = 0, value = "datas")
    private String datas;
}

//给数据类赋值
List<TestExcelData> res = new ArrayList<>();
TestExcelData data1 = new TestExcelData();
data1.setOriginPrice("test1\n"+"test2");
res.add(data1);

……//生成Excel
```
**异常提示**
打开生成的Excel之后test1和test2是在一行内的
只有点击该单元格后才能正确显示2行
**建议描述**

**Comment by zhuangjiaju** [comment]
升级到`2.2.0-beta1` 以上 用`@ContentStyle` 注解 的 `wrapped` 改成true

**Comment by Jacksonary** [comment]
> 升级到`2.2.0-beta1` 以上 用`@ContentStyle` 注解 的 `wrapped` 改成true

3.3.4 加了注解后报错
```log
java.lang.annotation.AnnotationTypeMismatchException: Incorrectly typed data found for annotation element public abstract com.alibaba.excel.enums.BooleanEnum com.alibaba.excel.annotation.write.style.ContentStyle.wrapped() (Found data of type class java.lang.Boolean[true])
at sun.reflect.annotation.AnnotationTypeMismatchExceptionProxy.generateException(AnnotationTypeMismatchExceptionProxy.java:57) ~[na:1.8.0_261]
at sun.reflect.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:84) ~[na:1.8.0_261]
at com.sun.proxy.$Proxy306.wrapped(Unknown Source) ~[na:na]
at com.alibaba.excel.metadata.property.StyleProperty.build(StyleProperty.java:208) ~[easyexcel-core-3.3.4.jar:na]
at com.alibaba.excel.util.ClassUtils.doDeclaredFieldContentMap(ClassUtils.java:256) ~[easyexcel-core-3.3.4.jar:na]
at com.alibaba.excel.util.ClassUtils.lambda$declaredFieldContentMap$4(ClassUtils.java:204) ~[easyexcel-core-3.3.4.jar:na]
```
