### ISSUE TITLE
版本升级至2.2.0，写Excel报错

### ISSUE THREAD

**Issue by naihewuxiao** [alibaba/easyexcel#1165]
**异常代码**
```java
   public String uploadToOssCfExcel(List list, Class cls, String fileName) throws Exception{
        try (ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {
            ExcelWriterBuilder writerBuilder = EasyExcelFactory.write(outputStream, cls);
            ExcelWriter excelWriter = EasyExcel.write(outputStream, cls).build();
            if (CollectionUtils.isEmpty(list)){
                ExcelWriterSheetBuilder sheetWriter = writerBuilder.excelType(ExcelTypeEnum.XLSX).sheet(0);
                sheetWriter.doWrite(list);
            }else {
                int count = (list.size() % SHEET_SIZE == 0) ? (list.size() / SHEET_SIZE) : ((list.size() / SHEET_SIZE) + 1);
                for (int i = 1; i <= count; i++) {
                    WriteSheet writeSheet = EasyExcel.writerSheet(i-1).build();
                    if (i * SHEET_SIZE > list.size()) {
                        excelWriter.write(list.subList((i - 1) * SHEET_SIZE, list.size()), writeSheet);
                        break;
                    } else {
                        excelWriter.write(list.subList((i - 1) * SHEET_SIZE, i * SHEET_SIZE), writeSheet);
                    }
                }
                excelWriter.finish();
            }
            String failureUrl = uploadToOss(BucketFileDirEnum.BASE.getFileDir()  + fileName, outputStream);
            log.info("文件上传成功，url={}", failureUrl);
            return failureUrl;
        }catch (Exception e){
            log.info("文件上传异常", e);
            throw e;
        }
```
**异常提示**
ExcelWriter excelWriter = EasyExcel.write(outputStream, cls).build();//该行报错
请提供完整的异常提示,记住是全部异常！
异常：
2020-03-17 19:46:51.972 [] [main:150456] [OssProxy.java:210] - [INFO] 文件上传异常
com.alibaba.excel.exception.ExcelGenerateException: java.lang.NoClassDefFoundError: org/apache/poi/POIXMLTypeLoader
	at com.alibaba.excel.write.ExcelBuilderImpl.<init>(ExcelBuilderImpl.java:41)
	at com.alibaba.excel.ExcelWriter.<init>(ExcelWriter.java:47)
	at com.alibaba.excel.write.builder.ExcelWriterBuilder.build(ExcelWriterBuilder.java:130)
	at com.clubfactory.ic.core.proxy.OssProxy.uploadToOssCfExcel(OssProxy.java:189)
	at com.clubfactory.ic.core.service.impl.BaseInfoServiceImpl.downloadHsCodeInfo(BaseInfoServiceImpl.java:312)
	at com.clubfactory.ic.core.service.impl.BaseInfoServiceImpl$$FastClassBySpringCGLIB$$35b37403.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
	at com.clubfactory.ic.core.service.impl.BaseInfoServiceImpl$$EnhancerBySpringCGLIB$$45e56e3f.downloadHsCodeInfo(<generated>)
	at com.clubfactory.ic.server.BaseInfoTest.testDownloadInfo(BaseInfoTest.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:73)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:83)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: java.lang.NoClassDefFoundError: org/apache/poi/POIXMLTypeLoader
	at org.openxmlformats.schemas.spreadsheetml.x2006.main.CTWorkbook$Factory.newInstance(Unknown Source)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.onWorkbookCreate(XSSFWorkbook.java:460)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:263)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:257)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:245)
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.<init>(SXSSFWorkbook.java:243)
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.<init>(SXSSFWorkbook.java:213)
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.<init>(SXSSFWorkbook.java:188)
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.<init>(SXSSFWorkbook.java:274)
	at com.alibaba.excel.util.WorkBookUtil.createWorkBook(WorkBookUtil.java:45)
	at com.alibaba.excel.context.WriteContextImpl.<init>(WriteContextImpl.java:85)
	at com.alibaba.excel.write.ExcelBuilderImpl.<init>(ExcelBuilderImpl.java:35)
	... 39 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.apache.poi.POIXMLTypeLoader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 51 common frames omitted

原版本2.0.0，因需使用@ContentStyle(wrapped=true)  ,将版本升级至2.2.0-beat1版本，但原先可以运行的代码报错

**Comment by zhuangjiaju** [comment]
请检查 是否统一poi版本 ，该类在 
```xml
    <dependency>
      <groupId>org.apache.poi</groupId>
      <artifactId>poi-ooxml-schemas</artifactId>
      <version>3.17</version>
    </dependency>
```
里面
