### ISSUE TITLE
加密文件上传出错

### ISSUE THREAD

**Issue by LiZhongJun** [alibaba/easyexcel#1167]
**异常代码**
```java
com.alibaba.excel.exception.ExcelCommonException: Convert excel format exception.You can try specifying the 'excelType' yourself
	at com.alibaba.excel.support.ExcelTypeEnum.valueOf(ExcelTypeEnum.java:71)
	at com.alibaba.excel.read.metadata.holder.ReadWorkbookHolder.<init>(ReadWorkbookHolder.java:160)
	at com.alibaba.excel.context.AnalysisContextImpl.<init>(AnalysisContextImpl.java:45)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.<init>(ExcelAnalyserImpl.java:44)
	at com.alibaba.excel.ExcelReader.<init>(ExcelReader.java:143)
	at com.alibaba.excel.read.builder.ExcelReaderBuilder.build(ExcelReaderBuilder.java:270)

**Comment by LiZhongJun** [comment]
Easyexcel 可以处理这种问题吗？

**Comment by zhuangjiaju** [comment]
需要传入参数password，并升级到最新版本。

**Comment by yinft** [comment]
> 需要传入参数password，并升级到最新版本。

你好，请问是在哪个方法里传password
