### ISSUE TITLE
多次导出后会白屏

### ISSUE THREAD

**Issue by lxz999** [alibaba/easyexcel#1186]
不刷新页面多次连续导出会白屏，报错：
com.alibaba.excel.exception.ExcelGenerateException: Can not close IO.
        at com.alibaba.excel.context.WriteContextImpl.finish(WriteContextImpl.java:331)
        at com.alibaba.excel.write.ExcelBuilderImpl.finish(ExcelBuilderImpl.java:101)
        at com.alibaba.excel.ExcelWriter.finish(ExcelWriter.java:328)
        at com.alibaba.excel.write.builder.ExcelWriterSheetBuilder.doWrite(ExcelWriterSheetBuilder.java:191)

**Comment by zhuangjiaju** [comment]
贴全异常

**Comment by zhuangjiaju** [comment]
不知道是否解决了问题？如果未解决，请重新打开问题。
