### ISSUE TITLE
解析数据抛异常

### ISSUE THREAD

**Issue by fefredgws** [alibaba/easyexcel#1207]
java.lang.IllegalArgumentException: Unquoted special character ';' in pattern "#,##0;-#,##0;-??;@"
	at java.text.DecimalFormat.applyPattern(DecimalFormat.java:3256)
	at java.text.DecimalFormat.<init>(DecimalFormat.java:464)
	at com.alibaba.excel.metadata.DataFormatter$InternalDecimalFormatWithScale.<init>(DataFormatter.java:457)
	at com.alibaba.excel.metadata.DataFormatter.createNumberFormat(DataFormatter.java:520)
	at com.alibaba.excel.metadata.DataFormatter.createFormat(DataFormatter.java:253)
	at com.alibaba.excel.metadata.DataFormatter.getFormat(DataFormatter.java:174)
	at com.alibaba.excel.metadata.DataFormatter.getFormattedNumberString(DataFormatter.java:585)
	at com.alibaba.excel.metadata.DataFormatter.format(DataFormatter.java:602)
	at com.alibaba.excel.util.NumberDataFormatterUtils.format(NumberDataFormatterUtils.java:39)
	at com.alibaba.excel.converters.string.StringNumberConverter.convertToJavaData(StringNumberConverter.java:50)
	at com.alibaba.excel.converters.string.StringNumberConverter.convertToJavaData(StringNumberConverter.java:22)
	at com.alibaba.excel.util.ConverterUtils.doConvertToJavaObject(ConverterUtils.java:133)
	at com.alibaba.excel.util.ConverterUtils.convertToJavaObject(ConverterUtils.java:103)
	at com.alibaba.excel.read.listener.ModelBuildEventListener.buildStringList(ModelBuildEventListener.java:62)
	at com.alibaba.excel.read.listener.ModelBuildEventListener.invoke(ModelBuildEventListener.java:41)
	at com.alibaba.excel.read.listener.ModelBuildEventListener.invoke(ModelBuildEventListener.java:28)
	at com.alibaba.excel.read.processor.DefaultAnalysisEventProcessor.dealData(DefaultAnalysisEventProcessor.java:100)
	at com.alibaba.excel.read.processor.DefaultAnalysisEventProcessor.endRow(DefaultAnalysisEventProcessor.java:47)
	at com.alibaba.excel.analysis.v07.handlers.RowTagHandler.endElement(RowTagHandler.java:46)
	at com.alibaba.excel.analysis.v07.handlers.sax.XlsxRowHandler.endElement(XlsxRowHandler.java:89)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)

**Comment by zhuangjiaju** [comment]
能否提供下excel.

**Comment by fefredgws** [comment]
web 无对象 同步返回













在 2020-04-22 19:18:10，"Jiaju Zhuang" <notifications@github.com> 写道：

能否提供下excel.

**Comment by fefredgws** [comment]
但不影响数据质量

**Comment by zhuangjiaju** [comment]
请详细描述您的问题

**Comment by fefredgws** [comment]
只是日志里会打印异常信息，没有其他影响


| |
何辉宗
|
|
邮箱：he_huizong@163.com
|

签名由 网易邮箱大师 定制

在2020年04月23日 19:03，Jiaju Zhuang 写道：

请详细描述您的问题
