### ISSUE TITLE
Can not close IO. Caused by: java.lang.NullPointerException

### ISSUE THREAD

**Issue by Nemo1986** [alibaba/easyexcel#1216]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   这里写你的代码
// 这里注意 有同学反应使用swagger 会导致各种问题，请直接用浏览器或者用postman

        response.setContentType("application/vnd.ms-excel");

        response.setCharacterEncoding("utf-8");

        // 这里URLEncoder.encode可以防止中文乱码 当然和easyexcel没有关系

        String fileName = URLEncoder.encode("测试", "UTF-8");

        response.setHeader("Content-disposition", "attachment;filename=" + fileName + ".xlsx");

        EasyExcel.write(response.getOutputStream(), BizcentCheckResult.class).sheet("模板").doWrite(bizcentCheckResults);
**异常提示**

com.alibaba.excel.exception.ExcelGenerateException: Can not close IO.
	at com.alibaba.excel.context.WriteContextImpl.finish(WriteContextImpl.java:358) ~[easyexcel-2.1.6.jar:?]
	at com.alibaba.excel.write.ExcelBuilderImpl.finish(ExcelBuilderImpl.java:101) ~[easyexcel-2.1.6.jar:?]
	at com.alibaba.excel.ExcelWriter.finish(ExcelWriter.java:328) ~[easyexcel-2.1.6.jar:?]
	at com.alibaba.excel.write.builder.ExcelWriterSheetBuilder.doWrite(ExcelWriterSheetBuilder.java:191) ~[easyexcel-2.1.6.jar:?]
	at com.lygjdf.bizcent.BizcentCheckCentreVM.down(BizcentCheckCentreVM.java:229) ~[classes/:?]
	at sun.reflect.GeneratedMethodAccessor417.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:45005) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
	at org.zkoss.bind.impl.ParamCall.call(ParamCall.java:149) ~[zkbind.jar:8.6.0]
	at org.zkoss.bind.impl.BinderImpl.handleNotifyChange(BinderImpl.java:1883) ~[zkbind.jar:8.6.0]
	at org.zkoss.bind.impl.BinderImpl.doExecute(BinderImpl.java:2051) ~[zkbind.jar:8.6.0]
	at org.zkoss.bind.impl.BinderImpl.doCommand(BinderImpl.java:1778) ~[zkbind.jar:8.6.0]
	at org.zkoss.bind.impl.BinderImpl.access$1300(BinderImpl.java:136) ~[zkbind.jar:8.6.0]
	at org.zkoss.bind.impl.BinderImpl$CommandEventListener.onEvent0(BinderImpl.java:1625) ~[zkbind.jar:8.6.0]
	at org.zkoss.bind.impl.BinderImpl$CommandEventListener.onEvent(BinderImpl.java:1578) ~[zkbind.jar:8.6.0]
	at org.zkoss.zk.ui.AbstractComponent.onEvent(AbstractComponent.java:3177) ~[zk.jar:8.6.0]
	at org.zkoss.zk.ui.AbstractComponent.service(AbstractComponent.java:3147) ~[zk.jar:8.6.0]
	at org.zkoss.zk.ui.AbstractComponent.service(AbstractComponent.java:3089) ~[zk.jar:8.6.0]
	at org.zkoss.zk.ui.impl.EventProcessor.process(EventProcessor.java:138) ~[zk.jar:8.6.0]
	at org.zkoss.zk.ui.impl.UiEngineImpl.processEvent(UiEngineImpl.java:1846) ~[zk.jar:8.6.0]
	at org.zkoss.zk.ui.impl.UiEngineImpl.process(UiEngineImpl.java:1618) [zk.jar:8.6.0]
	at org.zkoss.zk.ui.impl.UiEngineImpl.execUpdate(UiEngineImpl.java:1321) [zk.jar:8.6.0]
	at org.zkoss.zkmax.au.websocket.WebSocketEndPoint.process(WebSocketEndPoint.java:263) [zkmax.jar:8.6.0]
	at org.zkoss.zkmax.au.websocket.WebSocketEndPoint.access$100(WebSocketEndPoint.java:63) [zkmax.jar:8.6.0]
	at org.zkoss.zkmax.au.websocket.WebSocketEndPoint$1.onMessage(WebSocketEndPoint.java:119) [zkmax.jar:8.6.0]
	at org.zkoss.zkmax.au.websocket.WebSocketEndPoint$1.onMessage(WebSocketEndPoint.java:109) [zkmax.jar:8.6.0]
	at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:394) [tomcat-websocket.jar:8.5.33]
	at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:119) [tomcat-websocket.jar:8.5.33]
	at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:495) [tomcat-websocket.jar:8.5.33]
	at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:294) [tomcat-websocket.jar:8.5.33]
	at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133) [tomcat-websocket.jar:8.5.33]
	at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:82) [tomcat-websocket.jar:8.5.33]
	at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:171) [tomcat-websocket.jar:8.5.33]
	at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:151) [tomcat-websocket.jar:8.5.33]
	at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:148) [tomcat-websocket.jar:8.5.33]
	at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54) [tomcat-coyote.jar:8.5.33]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53) [tomcat-coyote.jar:8.5.33]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806) [tomcat-coyote.jar:8.5.33]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498) [tomcat-coyote.jar:8.5.33]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:8.5.33]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.5.33]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
	at org.apache.coyote.http11.Http11OutputBuffer$SocketOutputBuffer.doWrite(Http11OutputBuffer.java:623) ~[tomcat-coyote.jar:8.5.33]
	at org.apache.coyote.http11.filters.ChunkedOutputFilter.doWrite(ChunkedOutputFilter.java:121) ~[tomcat-coyote.jar:8.5.33]
	at org.apache.coyote.http11.Http11OutputBuffer.doWrite(Http11OutputBuffer.java:225) ~[tomcat-coyote.jar:8.5.33]
	at org.apache.coyote.Response.doWrite(Response.java:541) ~[tomcat-coyote.jar:8.5.33]
	at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:351) ~[catalina.jar:8.5.33]
	at org.apache.catalina.connector.OutputBuffer.flushByteBuffer(OutputBuffer.java:825) ~[catalina.jar:8.5.33]
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:310) ~[catalina.jar:8.5.33]
	at org.apache.catalina.connector.OutputBuffer.close(OutputBuffer.java:263) ~[catalina.jar:8.5.33]
	at org.apache.catalina.connector.CoyoteOutputStream.close(CoyoteOutputStream.java:157) ~[catalina.jar:8.5.33]
	at com.alibaba.excel.context.WriteContextImpl.finish(WriteContextImpl.java:333) ~[easyexcel-2.1.6.jar:?]
	... 43 more
请提供完整的异常提示,记住是全部异常！
**建议描述**

这个是tomcat-coyote.jar的包问题吗？

**Comment by xuewuyang** [comment]
遇到同样的问题，更换poi版本也不行

**Comment by xuewuyang** [comment]
是Http11OutputBuffer里面的commit方法被调用了两次，但是不懂这里为什么要调用两次，第二次socketWrapper被置为null，因此报空指针异常。

**Comment by zhuangjiaju** [comment]
这个必现么?会不会用户关闭了浏览器，或者时间太长？

**Comment by Nemo1986** [comment]
必现的，调试中就出现这个问题了，不是浏览器或者时间长的问题。

**Comment by zhuangjiaju** [comment]
这个需要你自己debug试试 我这里没法复现。
