### ISSUE TITLE
SpringBoot2 报classloder加载错误

### ISSUE THREAD

**Issue by jutleo** [alibaba/easyexcel#1290]
SpringBoot2 pom.xml引入
       <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>easyexcel</artifactId>
            <version>2.2.3</version>
        </dependency>
在web页面上点击导出，因导出文件太大，使用异步方法在后台导出，单独下载。

 @Async
    public void zjDBExport(Export export) {...}

报如下错误：

net.sf.cglib.core.CodeGenerationException: java.lang.reflect.InvocationTargetException-->null
	at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:237) ~[cglib-3.1.jar:?]
	at net.sf.cglib.beans.BeanMap$Generator.create(BeanMap.java:122) ~[cglib-3.1.jar:?]
	at net.sf.cglib.beans.BeanMap.create(BeanMap.java:58) ~[cglib-3.1.jar:?]
	at com.alibaba.excel.write.executor.ExcelWriteAddExecutor.addJavaObjectToExcel(ExcelWriteAddExecutor.java:116) ~[easyexcel-2.2.3.jar:?]
	at com.alibaba.excel.write.executor.ExcelWriteAddExecutor.addOneRowOfDataToExcel(ExcelWriteAddExecutor.java:67) ~[easyexcel-2.2.3.jar:?]
	at com.alibaba.excel.write.executor.ExcelWriteAddExecutor.add(ExcelWriteAddExecutor.java:52) ~[easyexcel-2.2.3.jar:?]
	at com.alibaba.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl.java:58) ~[easyexcel-2.2.3.jar:?]
	at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:161) ~[easyexcel-2.2.3.jar:?]
	at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:146) ~[easyexcel-2.2.3.jar:?]

跟踪代码发现，cglib jar文件中，在第二个if中获取到，第三个if获取是正确的。获取ClassLoader错误。

ClassLoader t = this.classLoader;
        if (t == null) {
            t = this.getDefaultClassLoader();
        }

        if (t == null) {
            t = this.getClass().getClassLoader();
        }

        if (t == null) {
            t = Thread.currentThread().getContextClassLoader();
        }

**Comment by zhuangjiaju** [comment]
尝试贴全代码

**Comment by zhuangjiaju** [comment]
是否已经解决了问题？如果未解决 请重新打开问题。
