### ISSUE TITLE
大佬们谁知道怎么解析CSV文件啊

### ISSUE THREAD

**Issue by ProwDong** [alibaba/easyexcel#1296]
在读取csv文件的时候会抛出：
com.alibaba.excel.exception.ExcelCommonException: Unknown excel type.

	at com.alibaba.excel.support.ExcelTypeEnum.valueOf(ExcelTypeEnum.java:49)
	at com.alibaba.excel.read.metadata.holder.ReadWorkbookHolder.<init>(ReadWorkbookHolder.java:160)
	at com.alibaba.excel.context.AnalysisContextImpl.<init>(AnalysisContextImpl.java:45)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.<init>(ExcelAnalyserImpl.java:44)
	at com.alibaba.excel.ExcelReader.<init>(ExcelReader.java:143)
	at com.alibaba.excel.read.builder.ExcelReaderBuilder.build(ExcelReaderBuilder.java:270)
	at com.example.demo.DemoApplicationTests.contextLoads(DemoApplicationTests.java:24)

**Comment by ProwDong** [comment]
我就想知道easyexcel能不能解析CSV,可以的话应该怎么配置

**Comment by dota17** [comment]
目前不能解析CSV，有super-csv和commons-csv可以用

**Comment by ProwDong** [comment]
@dota17 好的

**Comment by ProwDong** [comment]
> 目前不能解析CSV，有super-csv和commons-csv可以用

好的

**Comment by ProwDong** [comment]
> 目前不能解析CSV，有super-csv和commons-csv可以用



> 目前不能解析CSV，有super-csv和commons-csv可以用

好的
