### ISSUE TITLE
请问数据格式转换异常有没有办法捕获？ExcelGenerateException

### ISSUE THREAD

**Issue by masterCat92** [alibaba/easyexcel#1304]
com.alibaba.excel.exception.ExcelGenerateException: java.lang.NumberFormatException: For input string: "132%"
	at com.alibaba.excel.modelbuild.ModelBuildEventListener.invoke(ModelBuildEventListener.java:24)
	at com.alibaba.excel.analysis.BaseSaxAnalyser.notifyListeners(BaseSaxAnalyser.java:72)
	at com.alibaba.excel.analysis.v03.XlsSaxAnalyser.processRecord(XlsSaxAnalyser.java:311)

格式转换异常我希望能捕获，但是XlsSaxAnalyser中继承BaseSaxAnalyser后该方法固定了。
BaseSaxAnalyser这个抽象类的notifyListeners方法可不可以自定义实现呢？比如spi指定实现类这样的？

**Comment by zhuangjiaju** [comment]
实现`onException`方法
