### ISSUE TITLE
Converter not found, convert STRING to String

### ISSUE THREAD

**Issue by Hasherc** [alibaba/easyexcel#1345]
**触发场景描述**

**触发Bug的代码**
```java
File file = null;
        try {
            if (fileName.endsWith(".xls")) {
                file = new File(System.currentTimeMillis() + "_" + MD5.md5String(noskey) + ".xls");
            } else {
                file = new File(System.currentTimeMillis() + "_" + MD5.md5String(noskey) + ".xlsx");
            }
            nosAdapterService.download(bucketName, noskey, file);
            allData = EasyExcel.read(file, ExcelSongData.class, new DefaultListener()).sheet().doReadSync();
        } finally {
            if (file != null) {
                file.deleteOnExit();
            }
        }

```
**提示的异常或者没有达到的效果**
```
exception in search
com.alibaba.excel.exception.ExcelAnalysisException: com.alibaba.excel.exception.ExcelDataConvertException: Converter not found, convert STRING to String
	at com.alibaba.excel.analysis.v07.XlsxSaxAnalyser.parseXmlSource(XlsxSaxAnalyser.java:170) ~[easyexcel-2.1.6.jar:?]
	at com.alibaba.excel.analysis.v07.XlsxSaxAnalyser.execute(XlsxSaxAnalyser.java:189) ~[easyexcel-2.1.6.jar:?]
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.analysis(ExcelAnalyserImpl.java:105) ~[easyexcel-2.1.6.jar:?]
	at com.alibaba.excel.ExcelReader.read(ExcelReader.java:180) ~[easyexcel-2.1.6.jar:?]
	at com.alibaba.excel.ExcelReader.read(ExcelReader.java:170) ~[easyexcel-2.1.6.jar:?]
	at com.alibaba.excel.read.builder.ExcelReaderSheetBuilder.doReadSync(ExcelReaderSheetBuilder.java:175) ~[easyexcel-2.1.6.jar:?]
```

**Comment by Hasherc** [comment]
非必现，同一份表格，读取三次。仅一次出现改问题

**Comment by zhuangjiaju** [comment]
尝试升级到最新版本。

**Comment by zhuangjiaju** [comment]
这个问题是否已经解决？未解决的话重新打开问题。

**Comment by Hasherc** [comment]
该issue提出后，暂时还没有复现过
