### ISSUE TITLE
文件导出时，单元格内容长度过长时，抛出The maximum length of cell contents (text) is 32,767 characters

### ISSUE THREAD

**Issue by loongshaw** [alibaba/easyexcel#1352]
文件导出时，字段长度过长时，抛出The maximum length of cell contents (text) is 32,767 characters

`java.lang.IllegalArgumentException: The maximum length of cell contents (text) is 32,767 characters
	at org.apache.poi.xssf.streaming.SXSSFCell.setCellValue(SXSSFCell.java:325)
	at com.alibaba.excel.util.WorkBookUtil.createCell(WorkBookUtil.java:69)
	at com.alibaba.excel.write.ExcelBuilderImpl.addBasicTypeToExcel(ExcelBuilderImpl.java:102)
	at com.alibaba.excel.write.ExcelBuilderImpl.addOneRowOfDataToExcel(ExcelBuilderImpl.java:125)
	at com.alibaba.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl.java:63)
	at com.alibaba.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl.java:70)
	at com.alibaba.excel.ExcelWriter.write1(ExcelWriter.java:106)`

**Comment by KOkkmiao** [comment]
这个字段过长应该你这个自己解决吧。

**Comment by caofanCPU** [comment]
啥玩意要往一个单元格里写3万字?长篇小说吗?

**Comment by zhuangjiaju** [comment]
这个需要自己分开了

**Comment by yongxiang-chen** [comment]
https://www.cnblogs.com/zt007/p/14824395.html   这是前辈给出的一套解决方案  根据需要自行选择

> 这个有放开限制方案么

**Comment by jinhuiDing** [comment]
https://support.microsoft.com/zh-cn/office/excel-%E8%A7%84%E8%8C%83%E4%B8%8E%E9%99%90%E5%88%B6-1672b34d-7043-467e-8e27-269d656771c3
