### ISSUE TITLE
 头有空列时，写入Excel报空指针

### ISSUE THREAD

**Issue by uenglish** [alibaba/easyexcel#1422]
**触发场景描述**
头有空列时，合并头报NPE

**触发Bug的代码**
```java
package test;

import com.alibaba.excel.EasyExcel;
import com.alibaba.excel.ExcelWriter;
import org.junit.Test;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.stream.IntStream;

public class TestEasyEcel {

    @Test
    public void dynamicHeadWrite() {
        String fileName = "/Users/feng/temp/dynamicHeadWrite" + System.currentTimeMillis() + ".xlsx";

        ExcelWriter excelWriter = EasyExcel.write(fileName).autoCloseStream(Boolean.FALSE).build();
        excelWriter.write(dataList(), EasyExcel.writerSheet("模版1").head(headA()).build());
        excelWriter.write(dataList(), EasyExcel.writerSheet("模版2").head(headB()).build());
        excelWriter.finish();
    }

    private List<List<String>> headA() {
        return head("A");
    }

    private List<List<String>> headB() {
        return head("B");
    }

    private List<List<String>> head(String name) {
        List<List<String>> list = new ArrayList<>();
        IntStream.range(1, 3).forEach(i -> {
            List<String> headi = new ArrayList<>();
            headi.add(name + i + "字符串");
            headi.add(name + i + "数字");
            headi.add(name + i + "日期");
            headi.add(null);
            list.add(headi);
        });

        /*
         * EasyExcel 的设计缺陷
         * 行和列的顺序是反的
         *
         * 所以此处将行和列的顺序互换一下
         */
        List<List<String>> list2 = new ArrayList<>();
        for (int i = 0; i < list.size(); i++) {
            List<String> strings = list.get(i);

            for (int j = 0; j < strings.size(); j++) {
                String s = strings.get(j);

                if (list2.size() > j && null != list2.get(j)) {
                    List<String> list2arr = list2.get(j);
                    list2arr.add(s);
                    list2.set(j, list2arr);
                } else {
                    List<String> list2arr = new ArrayList<>(list.size());
                    list2arr.add(s);
                    list2.add(j, list2arr);
                }
            }
        }

        return list2;
    }

    private List<List<Object>> dataList() {
        List<List<Object>> list = new ArrayList<>();
        for (int i = 0; i < 10; i++) {
            List<Object> data = new ArrayList<>();
            data.add("字符串" + i);
            data.add(0.56);
            data.add(new Date());
            data.add(null);
            list.add(data);
        }
        return list;
    }
}

```
**提示的异常**
```
java.lang.NullPointerException
	at com.alibaba.excel.write.property.ExcelWriteHeadProperty.headCellRangeList(ExcelWriteHeadProperty.java:161)
	at com.alibaba.excel.context.WriteContextImpl.addMergedRegionToCurrentSheet(WriteContextImpl.java:231)
	at com.alibaba.excel.context.WriteContextImpl.initHead(WriteContextImpl.java:218)
	at com.alibaba.excel.context.WriteContextImpl.initSheet(WriteContextImpl.java:191)
	at com.alibaba.excel.context.WriteContextImpl.currentSheet(WriteContextImpl.java:122)
	at com.alibaba.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl.java:53)
	at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:161)
	at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:146)
	at test.TestEasyEcel.dynamicHeadWrite(TestEasyEcel.java:19)
```

**Comment by zhuangjiaju** [comment]
不建议放入头中有空。

**Comment by etcZYP** [comment]
> 

如果不能有空列怎么让某一列空出来

**Comment by etcZYP** [comment]
> 不建议放入头中有空。想办法自己提前判断下。

如果不能有空列怎么让某一列空出来
