### ISSUE TITLE
NullPointerException 

### ISSUE THREAD

**Issue by InspireYi** [alibaba/easyexcel#1527]
<dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>easyexcel</artifactId>
                <version>2.2.6</version>
            </dependency>

代码
EasyExcel.read(file.getInputStream(), clazz, new SingleRowListener(rowProcessor)).sheet(0).doRead();

导入excel报错堆栈

at org.apache.poi.xssf.usermodel.XSSFTableStyle.<init>(XSSFTableStyle.java:64)
	at org.apache.poi.xssf.model.StylesTable.readFrom(StylesTable.java:247)
	at org.apache.poi.xssf.model.StylesTable.<init>(StylesTable.java:141)
	at org.apache.poi.xssf.eventusermodel.XSSFReader.getStylesTable(XSSFReader.java:126)
	at com.alibaba.excel.analysis.v07.XlsxSaxAnalyser.<init>(XlsxSaxAnalyser.java:81)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.choiceExcelExecutor(ExcelAnalyserImpl.java:99)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.<init>(ExcelAnalyserImpl.java:51)
	at com.alibaba.excel.ExcelReader.<init>(ExcelReader.java:145)
	at com.alibaba.excel.read.builder.ExcelReaderBuilder.build(ExcelReaderBuilder.java:193)
	at com.alibaba.excel.read.builder.ExcelReaderBuilder.sheet(ExcelReaderBuilder.java:229)
	at com.alibaba.excel.read.builder.ExcelReaderBuilder.sheet(ExcelReaderBuilder.java:221)

请问这种怎么解决？

**Comment by zhuangjiaju** [comment]
贴全代码 并上传文件。

**Comment by InspireYi** [comment]
https://github.com/InspireYi/easyexceltest
@zhuangjiaju

**Comment by zhuangjiaju** [comment]
已经在`3.0.0-beta1` 版本修复，beta版本会在一个月内升级成正式版。
