### ISSUE TITLE
com.alibaba.excel.exception.ExcelGenerateException: java.lang.UnsatisfiedLinkError: /usr/lib/jvm/java-11-oracle/lib/libfontmanager.so: libfreetype.so.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by erzay** [alibaba/easyexcel#1533]
**异常代码**
```java

EasyExcel.write(filePath, ExcelProductInfo.class).sheet().doWrite(excelProductInfos);

```
**异常提示**
```log
com.alibaba.excel.exception.ExcelGenerateException: java.lang.UnsatisfiedLinkError: /usr/lib/jvm/java-11-oracle/lib/libfontmanager.so: libfreetype.so.6: cannot open shared object file: No such file or directory
        at com.alibaba.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl.java:64)
        at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:161)
        at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:146)
        at com.alibaba.excel.write.builder.ExcelWriterSheetBuilder.doWrite(ExcelWriterSheetBuilder.java:61)
        ...
Caused by: java.lang.UnsatisfiedLinkError: /usr/lib/jvm/java-11-oracle/lib/libfontmanager.so: libfreetype.so.6: cannot open shared object file: No such file or directory
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2638)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:827)
        at java.base/java.lang.System.loadLibrary(System.java:1871)
        at java.desktop/sun.font.FontManagerNativeLibrary$1.run(FontManagerNativeLibrary.java:57)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/sun.font.FontManagerNativeLibrary.<clinit>(FontManagerNativeLibrary.java:32)
        at java.desktop/sun.font.SunFontManager$1.run(SunFontManager.java:270)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/sun.font.SunFontManager.<clinit>(SunFontManager.java:266)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:82)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
        at java.desktop/java.awt.Font.getFont2D(Font.java:497)
        at java.desktop/java.awt.Font.canDisplayUpTo(Font.java:2250)
        at java.desktop/java.awt.font.TextLayout.singleFont(TextLayout.java:469)
        at java.desktop/java.awt.font.TextLayout.<init>(TextLayout.java:530)
        at org.apache.poi.ss.util.SheetUtil.getDefaultCharWidth(SheetUtil.java:275)
        at org.apache.poi.xssf.streaming.AutoSizeColumnTracker.<init>(AutoSizeColumnTracker.java:117)
        at org.apache.poi.xssf.streaming.SXSSFSheet.<init>(SXSSFSheet.java:82)
        at org.apache.poi.xssf.streaming.SXSSFWorkbook.createAndRegisterSXSSFSheet(SXSSFWorkbook.java:658)
        at org.apache.poi.xssf.streaming.SXSSFWorkbook.createSheet(SXSSFWorkbook.java:679)
        at org.apache.poi.xssf.streaming.SXSSFWorkbook.createSheet(SXSSFWorkbook.java:90)
        at com.alibaba.excel.util.WorkBookUtil.createSheet(WorkBookUtil.java:66)
        at com.alibaba.excel.context.WriteContextImpl.createSheet(WriteContextImpl.java:205)
        at com.alibaba.excel.context.WriteContextImpl.initSheet(WriteContextImpl.java:168)
        at com.alibaba.excel.context.WriteContextImpl.currentSheet(WriteContextImpl.java:122)
        at com.alibaba.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl.java:53)
        ... 21 common frames omitted
```
**建议描述**
docker容器，jdk11

**Comment by zhuangjiaju** [comment]
常见问题。

**Comment by wankang189** [comment]
我也遇到了同样的问题，你的问题解决了吗?

**Comment by BigPanda-Lu** [comment]
同样的问题

**Comment by BigPanda-Lu** [comment]
RUN yum install dejavu-sans-fonts fontconfig -y  dockerFile加上上面这句话即可，环境缺少字库

**Comment by erzay** [comment]
> 我也遇到了同样的问题，你的问题解决了吗?

我当时在本地是oracle jdk 没有问题。线上是openJdk，应该是Linux没有安装对应的字体。线上机器装下字体。

**Comment by guowenmeng** [comment]
通过这里解决了我的问题：https://github.com/docker-library/openjdk/issues/333

**Comment by guowenmeng** [comment]
docker下jdk镜像不要用slim版本。 可查看这里  docker-library/openjdk#333

**Comment by flagest** [comment]
我使用这个教程安装Linux字体，还是要报上面的错误。https://blog.csdn.net/YuZhuQue/article/details/112980894
