### ISSUE TITLE
模板没有变量的时候报错

### ISSUE THREAD

**Issue by Andyfoo** [alibaba/easyexcel#1564]
**触发场景描述**
模板excel中没有变量的时候报错，如果随便写一个{safasdf}就不会报错了，程序应该对这种情况处理。

**触发Bug的代码**
```java

		Map<String, Object> data3 = new HashMap<String, Object> ();
		data3.put("date", new Date());
		
		ExcelWriter excelWriter = EasyExcel.write("out.xlsx").withTemplate("tpl.xlsx").build();
		WriteSheet writeSheet = EasyExcel.writerSheet().build();
		excelWriter.fill(data3, writeSheet);
		excelWriter.finish();
```
**提示的异常或者没有达到的效果**
`Exception in thread "main" java.lang.NullPointerException
	at com.alibaba.excel.write.executor.ExcelWriteFillExecutor.doFill(ExcelWriteFillExecutor.java:191)
	at com.alibaba.excel.write.executor.ExcelWriteFillExecutor.fill(ExcelWriteFillExecutor.java:121)
	at com.alibaba.excel.write.ExcelBuilderImpl.fill(ExcelBuilderImpl.java:78)
	at com.alibaba.excel.ExcelWriter.fill(ExcelWriter.java:185)
	at com.alibaba.excel.ExcelWriter.fill(ExcelWriter.java:173)
	at tests.TestXls.main(TestXls.java:32)
`

**Comment by lq1448061208** [comment]
你好,我也出现了这个问题,请问是怎么解决的呢

**Comment by jaedonghan** [comment]
我也遇到这个问题了，这个问题还引发了另一个问题，fill方法抛出错误调用finishOnException关闭流，导致后面的sheet就无法填充数据了
