### ISSUE TITLE
关于easyexcel-2.2.6用到的Ehcache设置默认目录一些疑问

### ISSUE THREAD

**Issue by SpinSi** [alibaba/easyexcel#1580]
开发者：
           感谢您的easyexcel设计与开发，使用easyexcel的过程很爽。
    使用过程中发现easyexcel用到了Ehcache。但是Ehcache默认缓存文件是在系统的tmp文件下，我司对临时文件会定时删除。
    如果Ehcache 的临时文件夹被删除，会导致再次使用时发生如下异常。您看在Easyexcel中是否可以做下处理，或者在使用说明 
    中指明
     ... ...
Caused by: java.lang.RuntimeException: Unable to handle persistence
        at org.ehcache.core.EhcacheManager.getStore(EhcacheManager.java:448)
        at org.ehcache.core.EhcacheManager.createNewEhcache(EhcacheManager.java:317)
        at org.ehcache.core.EhcacheManager.createCache(EhcacheManager.java:266)
        ... 27 common frames omitted
Caused by: org.ehcache.CachePersistenceException: Unable to create or reuse directory: /tmp/xxxxx/excache/xxxxx/file
        at org.ehcache.impl.persistence.FileUtils.create(FileUtils.java:98)
        at org.ehcache.impl.persistence.DefaultLocalPersistenceService.createSafeSpace(DefaultLocalPersistenceService.java:166)
        at org.ehcache.impl.persistence.DefaultDiskResourceService.createSpace(DefaultDiskResourceService.java:150)
        at org.ehcache.impl.persistence.DefaultDiskResourceService.getPersistenceSpaceIdentifier(DefaultDiskResourceService.java:109)
        at org.ehcache.core.EhcacheManager.getStore(EhcacheManager.java:439)
        ... 29 common frames omitted

**Comment by zhugw** [comment]
CentOS系统中遇到了同样的问题 、

解决方法： 显式指定`java.io.tmpdir`

如 `java -Djava.io.tmpdir=/data/foo/tmp -jar foo.jar`

对应源码：`com.alibaba.excel.util.FileUtils`
```
private static String tempFilePrefix =
        System.getProperty(TempFile.JAVA_IO_TMPDIR) + File.separator + UUID.randomUUID().toString() + File.separator;
private static String cachePath = tempFilePrefix + EX_CACHE + File.separator;
```

**Comment by zhuangjiaju** [comment]
可以自己设置java 的临时目录
