### ISSUE TITLE
java.lang.IllegalArgumentException: rate must be positive

### ISSUE THREAD

**Issue by HusenHuang** [alibaba/easyexcel#1736]
```java
com.alibaba.excel.exception.ExcelAnalysisException: java.lang.IllegalArgumentException: rate must be positive
    at com.alibaba.excel.analysis.v07.XlsxSaxAnalyser.parseXmlSource(XlsxSaxAnalyser.java:183)
    at com.alibaba.excel.analysis.v07.XlsxSaxAnalyser.execute(XlsxSaxAnalyser.java:201)
    at com.alibaba.excel.analysis.ExcelAnalyserImpl.analysis(ExcelAnalyserImpl.java:115)
    at com.alibaba.excel.ExcelReader.read(ExcelReader.java:182)
    at com.alibaba.excel.ExcelReader.read(ExcelReader.java:172)
    at com.alibaba.excel.read.builder.ExcelReaderSheetBuilder.doRead(ExcelReaderSheetBuilder.java:65)
    at com.candao.task.api.utils.EasyExcelUtils.readInputStream(EasyExcelUtils.java:184)
    at com.candao.task.api.utils.EasyExcelUtils.readUrl(EasyExcelUtils.java:247)
    at com.candao.task.api.task.QueueTaskConsumerListener$1.lambda$run$0(QueueTaskConsumerListener.java:94)
    at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
    at com.candao.task.api.utils.DistributedDecorator.lambda$decorate$0(DistributedDecorator.java:14)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: rate must be positive
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:135)
    at com.google.common.util.concurrent.RateLimiter.setRate(RateLimiter.java:223)
    at com.google.common.util.concurrent.RateLimiter.create(RateLimiter.java:132)
    at com.google.common.util.concurrent.RateLimiter.create(RateLimiter.java:126)
    at com.candao.task.api.utils.HeartbeatUtils.getRateLimiter(HeartbeatUtils.java:48)
    at com.candao.task.api.utils.HeartbeatUtils.send(HeartbeatUtils.java:27)
    at com.candao.task.api.utils.BaseImportExcelTaskMapListener.invoke(BaseImportExcelTaskMapListener.java:201)
    at com.candao.task.api.utils.BaseImportExcelTaskMapListener.invoke(BaseImportExcelTaskMapListener.java:36)
    at com.alibaba.excel.read.processor.DefaultAnalysisEventProcessor.dealData(DefaultAnalysisEventProcessor.java:100)
    at com.alibaba.excel.read.processor.DefaultAnalysisEventProcessor.endRow(DefaultAnalysisEventProcessor.java:47)
    at com.alibaba.excel.analysis.v07.handlers.RowTagHandler.endElement(RowTagHandler.java:47)
    at com.alibaba.excel.analysis.v07.handlers.sax.XlsxRowHandler.endElement(XlsxRowHandler.java:89)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
    at com.alibaba.excel.analysis.v07.XlsxSaxAnalyser.parseXmlSource(XlsxSaxAnalyser.java:178)
```

**Comment by zhuangjiaju** [comment]
这个属于你写的业务代码抛异常。需要自己处理。
