### ISSUE TITLE
读取Datagrip导出的Excel文件抛空指针异常

### ISSUE THREAD

**Issue by hh-cat** [alibaba/easyexcel#1738]
**触发场景描述**
开发中使用Datagrip从数据库中导出Excel无法使用easyexcel读取，用WPS打开对应Excel随便动一下然后保存又可以正常读取了。

**触发Bug的代码**
使用语雀中“不创建对象的读”示例代码读取

**提示的异常或者没有达到的效果**
![image](https://user-images.githubusercontent.com/19165905/103295854-cd1bc680-4a2f-11eb-80c2-f424c63eaf9e.png)

**堆栈**
```
Exception in thread "main" com.alibaba.excel.exception.ExcelAnalysisException: java.lang.NullPointerException
	at com.alibaba.excel.analysis.v07.XlsxSaxAnalyser.parseXmlSource(XlsxSaxAnalyser.java:183)
	at com.alibaba.excel.analysis.v07.XlsxSaxAnalyser.execute(XlsxSaxAnalyser.java:201)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.analysis(ExcelAnalyserImpl.java:115)
	at com.alibaba.excel.ExcelReader.read(ExcelReader.java:182)
	at com.alibaba.excel.ExcelReader.read(ExcelReader.java:172)
	at com.alibaba.excel.read.builder.ExcelReaderSheetBuilder.doRead(ExcelReaderSheetBuilder.java:65)
	at ExcelDemo.main(ExcelDemo.java:19)
Caused by: java.lang.NullPointerException
	at com.alibaba.excel.analysis.v07.handlers.CellTagHandler.startElement(CellTagHandler.java:50)
	at com.alibaba.excel.analysis.v07.handlers.sax.XlsxRowHandler.startElement(XlsxRowHandler.java:67)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:510)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1359)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:142)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1214)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:644)
	at com.alibaba.excel.analysis.v07.XlsxSaxAnalyser.parseXmlSource(XlsxSaxAnalyser.java:178)
	... 6 more
```

**Comment by zhuangjiaju** [comment]
会在3+版本修复

**Comment by zhuangjiaju** [comment]
已经在`3.0.0-beta1` 版本修复，beta版本会在一个月内升级成正式版。
