### ISSUE TITLE
本地没问题（windows+tomcat），线上报错（国产服务器+国产servlet中间件）

### ISSUE THREAD

**Issue by oopsRookie** [alibaba/easyexcel#1757]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**
本地没问题，线上报错。
注：windows + tomcat 下正常（6台不同电脑测试过），国产服务器（Linux内核）+ 国产中间件报错
**触发Bug的代码**
```java
        if(this.watermark != null && !"".equals(this.watermark)){
            writer = EasyExcel.write(fos)
                    .inMemory(true)
                    .registerWriteHandler(new WaterMarkHandler(this.watermark))
                    .withTemplate(is).build();
        }else {
            writer = EasyExcel.write(fos).withTemplate(is).build();
        }

        //fill data to corresponding sheet
        for (int index = 0; index < this.sheetNos.size(); index++) {
            WriteSheet sheet = EasyExcel.writerSheet(this.sheetNos.get(index), this.sheetNames.get(index))
                    .build();
            writer.fill(this.data.get(index), sheet);                //报错的位置！
            //map填入
            writer.fill(map, sheet);
        }
```
**提示的异常或者没有达到的效果**
com.alibaba.excel.exception.ExcelGenerateException: java.lang.InternalError: java.lang.reflect.InvocationTargetException
	at com.alibaba.excel.write.ExcelBuilderImpl.fill(ExcelBuilderImpl.java:84) ~[easyexcel-2.2.7.jar:na]
	at com.alibaba.excel.ExcelWriter.fill(ExcelWriter.java:185) ~[easyexcel-2.2.7.jar:na]
	at com.alibaba.excel.ExcelWriter.fill(ExcelWriter.java:173) ~[easyexcel-2.2.7.jar:na]

**Comment by zhuangjiaju** [comment]
应该是没有字体 常见问题有
