### ISSUE TITLE
 com.alibaba.excel.exception.ExcelAnalysisException: java.lang.NoSuchMethodError: 

### ISSUE THREAD

**Issue by p19971018** [alibaba/easyexcel#1770]
突然就出现这个问题了，找不到原因，之前在其它项目都是可以运行的
**异常代码**

```java
文件类型MultipartFile，使用了org.springframework.util.FileCopyUtils中的copy(InputStream in, OutputStream out)进行文件复制（FileCopyUtils.copy(text.getInputStream(), new FileOutputStream(newPath));），然后程序读取
EasyExcel.read(filePath, Staff.class, new DemoDataListener(parama)).sheet().headRowNumber(2).doRead();

maven坐标
   <dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
		</dependency> 
		 <dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>3.17</version>
		</dependency> 
		 <dependency>
		    <groupId>com.alibaba</groupId>
		    <artifactId>easyexcel</artifactId>
		    <version>2.2.6</version>
		</dependency> 
```
**异常提示**
Exception in thread "Thread-27" com.alibaba.excel.exception.ExcelAnalysisException: java.lang.NoSuchMethodError: org.apache.poi.util.XMLHelper.newDocumentBuilder()Ljavax/xml/parsers/DocumentBuilder;
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.<init>(ExcelAnalyserImpl.java:57)
	at com.alibaba.excel.ExcelReader.<init>(ExcelReader.java:145)
	at com.alibaba.excel.read.builder.ExcelReaderBuilder.build(ExcelReaderBuilder.java:193)
	at com.alibaba.excel.read.builder.ExcelReaderBuilder.sheet(ExcelReaderBuilder.java:229)
	at com.alibaba.excel.read.builder.ExcelReaderBuilder.sheet(ExcelReaderBuilder.java:217)
	at com.zjry.sign.controller.SignUpController$SendSms.run(SignUpController.java:225)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.apache.poi.util.XMLHelper.newDocumentBuilder()Ljavax/xml/parsers/DocumentBuilder;
	at org.apache.poi.ooxml.util.DocumentHelper.newDocumentBuilder(DocumentHelper.java:47)
	at org.apache.poi.ooxml.util.DocumentHelper.<clinit>(DocumentHelper.java:36)
	at org.apache.poi.openxml4j.opc.internal.ContentTypeManager.parseContentTypesFile(ContentTypeManager.java:395)
	at org.apache.poi.openxml4j.opc.internal.ContentTypeManager.<init>(ContentTypeManager.java:104)
	at org.apache.poi.openxml4j.opc.internal.ZipContentTypeManager.<init>(ZipContentTypeManager.java:54)
	at org.apache.poi.openxml4j.opc.ZipPackage.getPartsImpl(ZipPackage.java:256)
	at org.apache.poi.openxml4j.opc.OPCPackage.getParts(OPCPackage.java:732)
	at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:280)
	at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:186)
	at com.alibaba.excel.analysis.v07.XlsxSaxAnalyser.readOpcPackage(XlsxSaxAnalyser.java:137)
	at com.alibaba.excel.analysis.v07.XlsxSaxAnalyser.<init>(XlsxSaxAnalyser.java:63)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.choiceExcelExecutor(ExcelAnalyserImpl.java:99)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.<init>(ExcelAnalyserImpl.java:51)
	... 6 more

**建议描述**

**Comment by p19971018** [comment]
添加依赖包

<dependency>
		     <groupId>com.alibaba</groupId>
		     <artifactId>easyexcel</artifactId>
		     <version>2.1.6</version>
		 </dependency>
		
		 <dependency>
		     <groupId>org.apache.poi</groupId>
		     <artifactId>poi-ooxml</artifactId>
		     <version>3.17</version>
		 </dependency>
		
		 <dependency>
		     <groupId>org.apache.poi</groupId>
		     <artifactId>poi-ooxml-schemas</artifactId>
		     <version>3.17</version>
		 </dependency>
		
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>3.17</version>
		</dependency>
