### ISSUE TITLE
java.io.FileNotFoundException: /tmp/76f0fbf6-bfd3-4c99-8a01-cc9e3c04fcbf/poifiles/poi-sxssf-sheet1685731914547649569.xml

### ISSUE THREAD

**Issue by ZJM6658** [alibaba/easyexcel#1814]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**
当导出excel数据超过一定数量（测试1000+条数据），时就会报错，必现
easyexcel版本2.2.7
poi、poi-ooxml、poi-ooxml-schemas 版本都是3.17
**触发Bug的代码**
```java
   String fileName = this.getTempExcelFilePathName(download.getLocation());
        int totalPage = (int) Math.ceil(dataCount / 50.0);
        int pageSize = 50;
        ExcelWriter excelWriter = null;
        try {
            excelWriter = EasyExcel.write(fileName, LiveSpeakerPayExcelVO.class).build();
            WriteSheet writeSheet = EasyExcel.writerSheet("sheet1").build();
            for (int i = 1; i <= totalPage; i++) {
                IPage<LiveListPayVo> pageObj = liveSpeakerService.getDoctorLivePayList(new Page(i, pageSize, false), uOrgId, orgType, reviewStatus, targetOrgId, startAt, endAt, null);
                if (CollectionUtils.isEmpty(pageObj.getRecords())) {
                    break;
                }
                List<LiveSpeakerPayExcelVO> dataList = new ArrayList<>();
                for (LiveListPayVo record : pageObj.getRecords()) {
                    dataList.add(new LiveSpeakerPayExcelVO(record));
                }
                excelWriter.write(dataList, writeSheet);
                try {
                    Thread.sleep(50);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        } finally {
            if (null != excelWriter) {
                excelWriter.finish();
            }
        }
```
**提示的异常或者没有达到的效果**
2021-03-08 14:58:45.072 [Finalizer] WARN  com.alibaba.excel.ExcelWriter - Destroy object failed
com.alibaba.excel.exception.ExcelGenerateException: Can not close IO.
	at com.alibaba.excel.context.WriteContextImpl.finish(WriteContextImpl.java:378)
	at com.alibaba.excel.write.ExcelBuilderImpl.finish(ExcelBuilderImpl.java:95)
	at com.alibaba.excel.ExcelWriter.finish(ExcelWriter.java:329)
	at com.alibaba.excel.ExcelWriter.finalize(ExcelWriter.java:340)
	at java.base/java.lang.System$2.invokeFinalize(System.java:2117)
	at java.base/java.lang.ref.Finalizer.runFinalizer(Finalizer.java:87)
	at java.base/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:171)
Caused by: java.io.FileNotFoundException: /tmp/76f0fbf6-bfd3-4c99-8a01-cc9e3c04fcbf/poifiles/poi-sxssf-sheet1685731914547649569.xml (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at org.apache.poi.xssf.streaming.SheetDataWriter.getWorksheetXMLInputStream(SheetDataWriter.java:140)
	at org.apache.poi.xssf.streaming.SXSSFSheet.getWorksheetXMLInputStream(SXSSFSheet.java:99)
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.injectData(SXSSFWorkbook.java:389)
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.write(SXSSFWorkbook.java:936)
	at com.alibaba.excel.context.WriteContextImpl.finish(WriteContextImpl.java:339)
	... 6 common frames omitted

**Comment by wtlihao** [comment]
我也碰到了，不知道怎么解决

**Comment by ZJM6658** [comment]
最后发现是数据问题，不知道为什么日志被吞掉了
