### ISSUE TITLE
com.alibaba.excel.exception.ExcelGenerateException: Can not close IO.

### ISSUE THREAD

**Issue by genjimoyouran** [alibaba/easyexcel#1820]
com.alibaba.excel.exception.ExcelGenerateException: Can not close IO.
Caused by: org.apache.catalina.connector.ClientAbortException: java.io.IOException: Broken pipe
at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:351)
at org.apache.catalina.connector.OutputBuffer.flushByteBuffer(OutputBuffer.java:776)
at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:298)
at org.apache.catalina.connector.OutputBuffer.close(OutputBuffer.java:251)
at org.apache.catalina.connector.CoyoteOutputStream.close(CoyoteOutputStream.java:157)
at org.springframework.security.web.util.OnCommittedResponseWrapper$SaveContextServletOutputStream.close(OnCommittedResponseWrapper.java:526)
at org.springframework.security.web.util.OnCommittedResponseWrapper$SaveContextServletOutputStream.close(OnCommittedResponseWrapper.java:526)
at com.alibaba.excel.context.WriteContextImpl.finish(WriteContextImpl.java:356)
... 95 common frames omitted
Caused by: java.io.IOException: Broken pipe

**Comment by genjimoyouran** [comment]
![image](https://user-images.githubusercontent.com/80512117/110912704-3765b700-834f-11eb-93a5-3bf69b545fd5.png)
数据过多就会导致这个问题 试了2.2.6 2.2.7都不行

**Comment by zhuangjiaju** [comment]
这个需要改成异步。用户未下载完成 关闭流了。
