### ISSUE TITLE
: Invalid row number (65536) outside allowable range (0..65535)

### ISSUE THREAD

**Issue by gaoxinfu** [alibaba/easyexcel#1822]
java.lang.IllegalArgumentException: Invalid row number (65536) outside allowable range (0..65535)
	at org.apache.poi.hssf.usermodel.HSSFRow.setRowNum(HSSFRow.java:252)
	at org.apache.poi.hssf.usermodel.HSSFRow.<init>(HSSFRow.java:86)
	at org.apache.poi.hssf.usermodel.HSSFRow.<init>(HSSFRow.java:70)
	at org.apache.poi.hssf.usermodel.HSSFSheet.createRow(HSSFSheet.java:259)
	at org.apache.poi.hssf.usermodel.HSSFSheet.createRow(HSSFSheet.java:83)
	at com.alibaba.excel.util.WorkBookUtil.createRow(WorkBookUtil.java:70)
	at com.alibaba.excel.write.executor.ExcelWriteAddExecutor.addOneRowOfDataToExcel(ExcelWriteAddExecutor.java:62)
	at com.alibaba.excel.write.executor.ExcelWriteAddExecutor.add(ExcelWriteAddExecutor.java:52)
	at com.alibaba.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl.java:58)
	at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:161)
	at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:146)
	at com.bestv.sync.data.charge.manage.service.impl.AccountFileService.deal(AccountFileService.java:104)
	at com.bestv.sync.data.charge.manage.service.impl.AccountFileService$$FastClassBySpringCGLIB$$b2aa1bf8.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)

**Comment by gaoxinfu** [comment]
超过 65535 是不是写入不成功的

**Comment by zhuangjiaju** [comment]
03版本 最多支持 65536 这是规范
