### ISSUE TITLE
Convert excel format exception.You can try specifying the 'excelType' yourself

### ISSUE THREAD

**Issue by yuanchaoyong** [alibaba/easyexcel#1845]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**
     excel文件原始文件导入没问题，删掉一行后导入报错
**触发Bug的代码**
```java
  com.alibaba.excel.exception.ExcelCommonException: Convert excel format exception.You can try specifying the 'excelType' yourself
	at com.alibaba.excel.support.ExcelTypeEnum.recognitionExcelType(ExcelTypeEnum.java:97)
	at com.alibaba.excel.support.ExcelTypeEnum.valueOf(ExcelTypeEnum.java:78)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.choiceExcelExecutor(ExcelAnalyserImpl.java:62)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.<init>(ExcelAnalyserImpl.java:51)
	at com.alibaba.excel.ExcelReader.<init>(ExcelReader.java:145)
	at com.alibaba.excel.read.builder.ExcelReaderBuilder.build(ExcelReaderBuilder.java:193)
	at com.alibaba.excel.read.builder.ExcelReaderBuilder.sheet(ExcelReaderBuilder.java:229)
	at com.alibaba.excel.read.builder.ExcelReaderBuilder.sheet(ExcelReaderBuilder.java:221)
	at com.dslyy.zn.sales.controller.achievements.AchievementAnalysisWeightController.batchImportWeight(AchievementAnalysisWeightController.java:161)
```
**提示的异常或者没有达到的效果**
 Convert excel format exception.You can try specifying the 'excelType' yourself

**Comment by zhuangjiaju** [comment]
建议重新保存下文件 这个是无法获取到文件的类型。可以自己指定类型。
