### ISSUE TITLE
如何指定使用xls格式文件

### ISSUE THREAD

**Issue by fangzhaoxuan** [alibaba/easyexcel#1868]
**异常代码**
 // 上传源文件
        importSourceFileUrl = uploadSourceFile(user, file);
        InputStream inputStream;
        try {
            inputStream = file.getInputStream();
        } catch (IOException e) {
            throw new BizException(ResultCodeEnum.FILE_INPUTSTREAM_ERR, e);
        }
        EnterpriseCreditListener creditListener = new EnterpriseCreditListener(importSourceFileUrl, iImportRecordService, importExcelRsVO, user, this, param);
        creditListener.errorMsg.clear();
        try {
            EasyExcelUtil.asyncRead(inputStream, EnterpriseCreditImportVO.class, creditListener, 0, 1);
        } catch (Exception e) {
            throw new BizException(ResultCodeEnum.IMPORT_DATA_ERROR, e);
        }
**异常提示**
Caused by: com.alibaba.excel.exception.ExcelCommonException: Convert excel format exception.You can try specifying the 'excelType' yourself
	at com.alibaba.excel.support.ExcelTypeEnum.recognitionExcelType(ExcelTypeEnum.java:97)
	at com.alibaba.excel.support.ExcelTypeEnum.valueOf(ExcelTypeEnum.java:78)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.choiceExcelExecutor(ExcelAnalyserImpl.java:62)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.<init>(ExcelAnalyserImpl.java:51)
	at com.alibaba.excel.ExcelReader.<init>(ExcelReader.java:145)
	at com.alibaba.excel.read.builder.ExcelReaderBuilder.build(ExcelReaderBuilder.java:193)
	at com.alibaba.excel.read.builder.ExcelReaderBuilder.sheet(ExcelReaderBuilder.java:229)
	at com.alibaba.excel.read.builder.ExcelReaderBuilder.sheet(ExcelReaderBuilder.java:221)
	at com.gongbaojin.common.file.EasyExcelUtil.asyncRead(EasyExcelUtil.java:198)
	at com.gongbaojin.cms.service.impl.EnterpriseCreditServiceImpl.upload(EnterpriseCreditServiceImpl.java:60)
	... 88 common frames omitted
**建议描述**
怎么指定使用xls格式

**Comment by zhuangjiaju** [comment]
`EasyExcel.write(fileName, DemoData.class).excelType(ExcelTypeEnum.XLS)` 指定
