### ISSUE TITLE
导入时报错,不太明白这是什么问题

### ISSUE THREAD

**Issue by xiangdan1** [alibaba/easyexcel#1887]
java.lang.IllegalStateException: Cache 'b1da71c9-3b29-4119-9f2e-3c337c5fa450' creation in EhcacheManager failed.
	at org.ehcache.core.EhcacheManager.createCache(EhcacheManager.java:302)
	at org.ehcache.core.EhcacheManager.createCache(EhcacheManager.java:252)
	at com.alibaba.excel.cache.Ehcache.init(Ehcache.java:76)
	at com.alibaba.excel.analysis.v07.XlsxSaxAnalyser.defaultReadCache(XlsxSaxAnalyser.java:108)
	at com.alibaba.excel.analysis.v07.XlsxSaxAnalyser.<init>(XlsxSaxAnalyser.java:72)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.choiceExcelExecutor(ExcelAnalyserImpl.java:99)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.<init>(ExcelAnalyserImpl.java:51)
	at com.alibaba.excel.ExcelReader.<init>(ExcelReader.java:145)
	at com.alibaba.excel.read.builder.ExcelReaderBuilder.build(ExcelReaderBuilder.java:193)
	at com.alibaba.excel.read.builder.ExcelReaderBuilder.sheet(ExcelReaderBuilder.java:229)
Caused by: java.lang.RuntimeException: Unable to handle persistence
	at org.ehcache.core.EhcacheManager.getStore(EhcacheManager.java:436)
	at org.ehcache.core.EhcacheManager.createNewEhcache(EhcacheManager.java:342)
	at org.ehcache.core.EhcacheManager.createCache(EhcacheManager.java:274)
	at org.ehcache.core.EhcacheManager.createCache(EhcacheManager.java:252)
	at com.alibaba.excel.cache.Ehcache.init(Ehcache.java:76)
	at com.alibaba.excel.analysis.v07.XlsxSaxAnalyser.defaultReadCache(XlsxSaxAnalyser.java:108)
	at com.alibaba.excel.analysis.v07.XlsxSaxAnalyser.<init>(XlsxSaxAnalyser.java:72)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.choiceExcelExecutor(ExcelAnalyserImpl.java:99)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.<init>(ExcelAnalyserImpl.java:51)
	at com.alibaba.excel.ExcelReader.<init>(ExcelReader.java:145)
Caused by: org.ehcache.CachePersistenceException: Unable to create or reuse directory: /tmp/3e9f8ba3-6da1-4492-8866-041b7d8442ed/excache/d31e4e58-f5f2-487f-b9b7-e0081dec7e13/file
	at org.ehcache.impl.persistence.FileUtils.create(FileUtils.java:98)
	at org.ehcache.impl.persistence.DefaultLocalPersistenceService.createSafeSpace(DefaultLocalPersistenceService.java:166)
	at org.ehcache.impl.persistence.DefaultDiskResourceService.createSpace(DefaultDiskResourceService.java:150)
	at org.ehcache.impl.persistence.DefaultDiskResourceService.getPersistenceSpaceIdentifier(DefaultDiskResourceService.java:109)
	at org.ehcache.core.EhcacheManager.getStore(EhcacheManager.java:427)
	at org.ehcache.core.EhcacheManager.createNewEhcache(EhcacheManager.java:342)
	at org.ehcache.core.EhcacheManager.createCache(EhcacheManager.java:274)
	at org.ehcache.core.EhcacheManager.createCache(EhcacheManager.java:252)
	at com.alibaba.excel.cache.Ehcache.init(Ehcache.java:76)
	at com.alibaba.excel.analysis.v07.XlsxSaxAnalyser.defaultReadCache(XlsxSaxAnalyser.java:108)

**Comment by lethal233** [comment]
能否提供一下复现bug的最小完整代码，我来看看能不能复现一下，跟踪一下源码？ @xiangdan1 应该是cache那里报错了

**Comment by xiangdan1** [comment]
[code.txt](https://github.com/alibaba/easyexcel/files/6354938/code.txt)
[excel.xlsx](https://github.com/alibaba/easyexcel/files/6354940/excel.xlsx)


我们导入的时候是有九十多万数据，由于是真实数据不便上传了，这个是偶现的问题，没有经常出现

**Comment by lethal233** [comment]
> [code.txt](https://github.com/alibaba/easyexcel/files/6354938/code.txt)
> [excel.xlsx](https://github.com/alibaba/easyexcel/files/6354940/excel.xlsx)
> 
> 我们导入的时候是有九十多万数据，由于是真实数据不便上传了，这个是偶现的问题，没有经常出现

OK，我尝试看看能不能复现一下 @xiangdan1

**Comment by zhuangjiaju** [comment]
创建文件报错了是否权限或者磁盘满了之类的问题？

**Comment by zhuangjiaju** [comment]
这个是否已经解决？如果未解决则重新打开问题。

**Comment by wangxin2285** [comment]
这个后来有解决么，我也遇见了这个问题，导入数据50万条的时候，也报了类似错我。50万数据，5个线程同时做，其中一个报错了。

**Comment by jiangjianwei1991** [comment]
我也出现了这个问题，导入的数据大约7~8M的数据。

**Comment by Level1Accelerator** [comment]
+1,大量数据导入会出现此问题
