### ISSUE TITLE
关闭流的时候报内存溢出

### ISSUE THREAD

**Issue by xuxiaoqun** [alibaba/easyexcel#1953]
2021-05-21 19:20:58.573  ERROR 10.8.110.1 [bfd-care,8de97729cbe76858] [bfd-admin-flow-0a08653b-450443-73] 24768 --- [pool-5-thread-1] com.dbenefit.care.biz.service.care.impl.CareUserWelfareServiceImpl : 导出详情失败
com.alibaba.excel.exception.ExcelGenerateException: Can not close IO.
	at com.alibaba.excel.context.WriteContextImpl.finish(WriteContextImpl.java:358)
	at com.alibaba.excel.write.ExcelBuilderImpl.finish(ExcelBuilderImpl.java:101)
	at com.alibaba.excel.ExcelWriter.finish(ExcelWriter.java:328)
	at com.dbenefit.care.biz.util.ExcelUtil.closeExcelWriter(ExcelUtil.java:197)
	at com.dbenefit.care.biz.service.care.impl.CareUserWelfareServiceImpl.getCareSendDetailStream(CareUserWelfareServiceImpl.java:280)
	at com.dbenefit.care.biz.service.care.impl.CareUserWelfareServiceImpl.createCareSendDetailExcel(CareUserWelfareServiceImpl.java:202)
	at com.dbenefit.care.biz.service.care.impl.CareUserWelfareServiceImpl$$FastClassBySpringCGLIB$$d0acbf99.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.dbenefit.care.biz.service.care.impl.CareUserWelfareServiceImpl$$EnhancerBySpringCGLIB$$a65b3c90.createCareSendDetailExcel(<generated>)
	at com.dbenefit.care.web.cloud.CareCloud.lambda$exportWelfareDetail$0(CareCloud.java:183)
	at com.dbenefit.application.util.BFDThreadPoolExecutor.lambda$wrapExecute$1(BFDThreadPoolExecutor.java:84)
	at com.alibaba.ttl.TtlRunnable.run(TtlRunnable.java:59)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3236)
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
	at java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:253)
	at java.util.zip.ZipOutputStream.closeEntry(ZipOutputStream.java:255)
	at org.apache.poi.openxml4j.opc.internal.marshallers.ZipPartMarshaller.marshall(ZipPartMarshaller.java:92)
	at org.apache.poi.openxml4j.opc.internal.MemoryPackagePart.save(MemoryPackagePart.java:112)
	at org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller.marshall(DefaultMarshaller.java:43)
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:585)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1539)
	at org.apache.poi.openxml4j.opc.OPCPackage.close(OPCPackage.java:482)
	at org.apache.poi.POIXMLDocument.close(POIXMLDocument.java:189)
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.close(SXSSFWorkbook.java:909)
	at com.alibaba.excel.context.WriteContextImpl.finish(WriteContextImpl.java:316)
	at com.alibaba.excel.write.ExcelBuilderImpl.finish(ExcelBuilderImpl.java:101)
	at com.alibaba.excel.ExcelWriter.finish(ExcelWriter.java:328)
	at com.dbenefit.care.biz.util.ExcelUtil.closeExcelWriter(ExcelUtil.java:197)
	at com.dbenefit.care.biz.service.care.impl.CareUserWelfareServiceImpl.getCareSendDetailStream(CareUserWelfareServiceImpl.java:280)
	at com.dbenefit.care.biz.service.care.impl.CareUserWelfareServiceImpl.createCareSendDetailExcel(CareUserWelfareServiceImpl.java:202)
	at com.dbenefit.care.biz.service.care.impl.CareUserWelfareServiceImpl$$FastClassBySpringCGLIB$$d0acbf99.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionInterceptor$$Lambda$547/1230026826.proceedWithInvocation(Unknown Source)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.dbenefit.care.biz.service.care.impl.CareUserWelfareServiceImpl$$EnhancerBySpringCGLIB$$a65b3c90.createCareSendDetailExcel(<generated>)

**Comment by xuxiaoqun** [comment]
版本2.1.6

**Comment by zhuangjiaju** [comment]
建议升级版本 & 适当的调大内存
