### ISSUE TITLE
与亚马逊云储存一起用的时候，并发读取数据会失败。

### ISSUE THREAD

**Issue by ReachardZhou** [alibaba/easyexcel#196]
与亚马逊云储存一起用的时候，并发读取数据会失败，串行操作可以成功。
Excel文件在亚马逊云对象储存中，我并发读取并用easyexcel去解析文件流会报错。错误如下：

com.alibaba.excel.exception.ExcelAnalysisException: File type error，io must be available markSupported,you can do like this <code> new BufferedInputStream(new FileInputStream(\"/xxxx\"))</code> "
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.getSaxAnalyser(ExcelAnalyserImpl.java:58)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.analysis(ExcelAnalyserImpl.java:72)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.analysis(ExcelAnalyserImpl.java:67)
	at com.alibaba.excel.ExcelReader.read(ExcelReader.java:112)
	at com.alibaba.excel.EasyExcelFactory.read(EasyExcelFactory.java:39)
	at com.alibaba.easyexcel.test.Testconcurrent$Reader.run(Testconcurrent.java:40)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.alibaba.excel.exception.ExcelAnalysisException: Xls must be available markSupported,you can do like this <code> new BufferedInputStream(new FileInputStream("/xxxx"))</code> 
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.getSaxAnalyser(ExcelAnalyserImpl.java:50)
	... 6 more

说明：easyexcel并发读取本地文件流解析时不会报错
          并发去读取亚马逊文件流的时候也不会报错
    两个操作链接在一起并发就会报错，串行操作不会报错

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写
