### ISSUE TITLE
如果模板中没有任何填充的变量，传入map数据填充时会报NullPointerException

### ISSUE THREAD

**Issue by anycs** [alibaba/easyexcel#1961]
**触发场景描述**
 用map填充时，如果模板中没有任何填充的变量，当传入map数据填充时会报NullPointerException，模板中如果有任意变量则正常。
**触发Bug的代码**
```java
   WriteSheet writeSheet = EasyExcel.writerSheet(0).build();
   Map<String,Object> paramsData = new HashMap<>();
   paramsData.put("DAY","2021-05-31");
   excelWriter.fill(paramsData,writeSheet);
   excelWriter.finish();
```
**提示的异常或者没有达到的效果**
Exception in thread "main" java.lang.NullPointerException
	at com.alibaba.excel.write.executor.ExcelWriteFillExecutor.doFill(ExcelWriteFillExecutor.java:191)
	at com.alibaba.excel.write.executor.ExcelWriteFillExecutor.fill(ExcelWriteFillExecutor.java:121)
	at com.alibaba.excel.write.ExcelBuilderImpl.fill(ExcelBuilderImpl.java:78)
	at com.alibaba.excel.ExcelWriter.fill(ExcelWriter.java:185)
	at com.alibaba.excel.ExcelWriter.fill(ExcelWriter.java:173)

**Comment by zhuangjiaju** [comment]
已经在`3.0.0-beta1` 版本修复，beta版本会在一个月内升级成正式版。
