### ISSUE TITLE
java.lang.IllegalArgumentException: Attempting to write a row[0] in the range [0,500] that is already written to disk.

### ISSUE THREAD

**Issue by Kingsea442** [alibaba/easyexcel#1969]
java.lang.IllegalArgumentException: Attempting to write a row[0] in the range [0,500] that is already written to disk.

**Comment by Kingsea442** [comment]
复现场景：
大数据场景
每次往一个sheet里写1000行，然后超过5万行就创建个新的sheet。
问题出在同一个sheet，第二次写入即 1000-2000的时候


java.lang.IllegalArgumentException: Attempting to write a row[0] in the range [0,500] that is already written to disk.
	at org.apache.poi.xssf.streaming.SXSSFSheet.createRow(SXSSFSheet.java:131)
	at org.apache.poi.xssf.streaming.SXSSFSheet.createRow(SXSSFSheet.java:65)
	at com.alibaba.excel.util.WorkBookUtil.createRow(WorkBookUtil.java:70)
	at com.alibaba.excel.context.WriteContextImpl.initHead(WriteContextImpl.java:205)
	at com.alibaba.excel.context.WriteContextImpl.initSheet(WriteContextImpl.java:173)
	at com.alibaba.excel.context.WriteContextImpl.currentSheet(WriteContextImpl.java:114)
	at com.alibaba.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl.java:56)
	at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:161)
	at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:146)
	at

**Comment by zhuangjiaju** [comment]
贴全代码

**Comment by zhuangjiaju** [comment]
这个是否已经解决？如果未解决则重新打开问题。

**Comment by 1842626921** [comment]
我也是这个问题，好像是一批数据已经放入内存，最后合并单元格边框线样式的时候会出现找不到所需要的row，因为在内存里；可是这个问题该怎么解决呢？
