### ISSUE TITLE
抛出异常不能够继续往后解析执行

### ISSUE THREAD

**Issue by fengyts** [alibaba/easyexcel#2045]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**异常代码**
```java
   @Slf4j
public class EasyExcelReadListener<T> extends AnalysisEventListener<T> {

    private AtomicInteger row = new AtomicInteger(0);

    @Override
    public void invoke(Object data, AnalysisContext context) {
        try {
            List<Pair<String, String>> validMsgs = EasyExcelValidHelper.validateEntity(data);
            if (!CollectionUtils.isEmpty(validMsgs)) {
                String msg = validMsgs.stream().map(Pair::getValue).collect(Collectors.joining(";"));
                errors.add(new ExcelError(row.incrementAndGet(), -1, null, msg));
            }

            log.info("validate msg: {}", validMsgs);
        } catch (Exception e) {
            log.info("resolver exception: {}", e);
        }
    }

    @Override
    public void doAfterAllAnalysed(AnalysisContext context) {
    }

    @Override
    public void onException(Exception exception, AnalysisContext context) {
        try {
            if (exception instanceof ExcelDataConvertException) {
                ExcelDataConvertException e = (ExcelDataConvertException) exception;
                Integer rowIndex = e.getRowIndex();
                Integer columnIndex = e.getColumnIndex();
                log.info("第{}行，第{}列解析异常: {}", rowIndex, columnIndex, e);
                String headerName = "";
                if (!CollectionUtils.isEmpty(headers)) {
                    headerName = headers.get(columnIndex);
                }
                errors.add(new ExcelError(rowIndex, columnIndex, headerName, "数据解析异常"));
            } else {
                log.info("resolve excel exception-unknown exception:", exception);
            }
        } catch (Exception e) {
            errors.add(UNKNOWN_ERROR);
            log.info("resolve excel exception: {}", exception);
        }

    }
}
```
**异常提示**
16:31:56.448 [main] INFO com.backend.learn.poi.easyexcel.EasyExcelReadListener - 第2行，第2列解析异常: {}
com.alibaba.excel.exception.ExcelDataConvertException: Convert data a to class java.lang.Integer error 
	at com.alibaba.excel.util.ConverterUtils.doConvertToJavaObject(ConverterUtils.java:135)
	at com.alibaba.excel.util.ConverterUtils.convertToJavaObject(ConverterUtils.java:103)
	at com.alibaba.excel.read.listener.ModelBuildEventListener.buildUserModel(ModelBuildEventListener.java:113)
	at com.alibaba.excel.read.listener.ModelBuildEventListener.invoke(ModelBuildEventListener.java:38)
	at com.alibaba.excel.read.listener.ModelBuildEventListener.invoke(ModelBuildEventListener.java:28)
	at com.alibaba.excel.read.metadata.holder.AbstractReadHolder.notifyEndOneRow(AbstractReadHolder.java:145)
	at com.alibaba.excel.analysis.v07.handlers.ProcessResultCellHandler.endHandle(ProcessResultCellHandler.java:45)
	at com.alibaba.excel.analysis.v07.XlsxRowHandler.endElement(XlsxRowHandler.java:44)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.alibaba.excel.analysis.v07.XlsxSaxAnalyser.parseXmlSource(XlsxSaxAnalyser.java:165)
	at com.alibaba.excel.analysis.v07.XlsxSaxAnalyser.execute(XlsxSaxAnalyser.java:189)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.analysis(ExcelAnalyserImpl.java:105)
	at com.alibaba.excel.ExcelReader.read(ExcelReader.java:180)
	at com.alibaba.excel.ExcelReader.read(ExcelReader.java:170)
	at com.alibaba.excel.read.builder.ExcelReaderSheetBuilder.doReadSync(ExcelReaderSheetBuilder.java:175)
	at com.backend.learn.poi.easyexcel.ExcelTest.testEasyExcelRead(ExcelTest.java:42)
	at com.backend.learn.poi.easyexcel.ExcelTest.main(ExcelTest.java:51)
Caused by: java.lang.NumberFormatException: For input string: "a"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at com.alibaba.excel.util.NumberUtils.parseInteger(NumberUtils.java:90)
	at com.alibaba.excel.converters.integer.IntegerStringConverter.convertToJavaData(IntegerStringConverter.java:32)
	at com.alibaba.excel.converters.integer.IntegerStringConverter.convertToJavaData(IntegerStringConverter.java:17)
	at com.alibaba.excel.util.ConverterUtils.doConvertToJavaObject(ConverterUtils.java:133)
	... 25 common frames omitted
Exception in thread "main" com.alibaba.excel.exception.ExcelAnalysisException: Convert data a to class java.lang.Integer error 
	at com.alibaba.excel.read.metadata.holder.AbstractReadHolder.notifyEndOneRow(AbstractReadHolder.java:151)
	at com.alibaba.excel.analysis.v07.handlers.ProcessResultCellHandler.endHandle(ProcessResultCellHandler.java:45)
	at com.alibaba.excel.analysis.v07.XlsxRowHandler.endElement(XlsxRowHandler.java:44)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.alibaba.excel.analysis.v07.XlsxSaxAnalyser.parseXmlSource(XlsxSaxAnalyser.java:165)
	at com.alibaba.excel.analysis.v07.XlsxSaxAnalyser.execute(XlsxSaxAnalyser.java:189)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.analysis(ExcelAnalyserImpl.java:105)
	at com.alibaba.excel.ExcelReader.read(ExcelReader.java:180)
	at com.alibaba.excel.ExcelReader.read(ExcelReader.java:170)
	at com.alibaba.excel.read.builder.ExcelReaderSheetBuilder.doReadSync(ExcelReaderSheetBuilder.java:175)
	at com.backend.learn.poi.easyexcel.ExcelTest.testEasyExcelRead(ExcelTest.java:42)
	at com.backend.learn.poi.easyexcel.ExcelTest.main(ExcelTest.java:51)
Caused by: com.alibaba.excel.exception.ExcelDataConvertException: Convert data a to class java.lang.Integer error 
	at com.alibaba.excel.util.ConverterUtils.doConvertToJavaObject(ConverterUtils.java:135)
	at com.alibaba.excel.util.ConverterUtils.convertToJavaObject(ConverterUtils.java:103)
	at com.alibaba.excel.read.listener.ModelBuildEventListener.buildUserModel(ModelBuildEventListener.java:113)
	at com.alibaba.excel.read.listener.ModelBuildEventListener.invoke(ModelBuildEventListener.java:38)
	at com.alibaba.excel.read.listener.ModelBuildEventListener.invoke(ModelBuildEventListener.java:28)
	at com.alibaba.excel.read.metadata.holder.AbstractReadHolder.notifyEndOneRow(AbstractReadHolder.java:145)
	... 20 more
Caused by: java.lang.NumberFormatException: For input string: "a"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at com.alibaba.excel.util.NumberUtils.parseInteger(NumberUtils.java:90)
	at com.alibaba.excel.converters.integer.IntegerStringConverter.convertToJavaData(IntegerStringConverter.java:32)
	at com.alibaba.excel.converters.integer.IntegerStringConverter.convertToJavaData(IntegerStringConverter.java:17)
	at com.alibaba.excel.util.ConverterUtils.doConvertToJavaObject(ConverterUtils.java:133)
	... 25 more
**建议描述**
我希望的是在解析过程中，校验不合法数据在捕获异常之后能够继续往下执行，而不是发现异常就直接给终止了。

**Comment by zhuangjiaju** [comment]
实现 onException && hasNext 分别处理 抛出异常的情况 和 是否继续
