### ISSUE TITLE
2.2.8升级到3.0之后，导出大量带图片的信息写入时会报错

### ISSUE THREAD

**Issue by guizeru** [alibaba/easyexcel#2106]
使用场景：
    导出excel每一行要带三张照片，格式为xls。
问题描述：
    使用写入文件的方式为InputStream，之前使用2.2.8版本导出无问题，升级到3.0.0之后导出少量数据无问题，大量数据会报如下错误：
**异常提示**
java.lang.IllegalStateException: The maximum number of cell styles was exceeded. You can define up to 4000 styles in a .xls workbook
	at org.apache.poi.hssf.usermodel.HSSFWorkbook.createCellStyle(HSSFWorkbook.java:1262)
	at org.apache.poi.hssf.usermodel.HSSFWorkbook.createCellStyle(HSSFWorkbook.java:131)
	at com.alibaba.excel.util.StyleUtil.buildCellStyle(StyleUtil.java:39)
	at com.alibaba.excel.write.metadata.holder.WriteWorkbookHolder.createCellStyle(WriteWorkbookHolder.java:252)
	at com.alibaba.excel.write.executor.AbstractExcelWriteExecutor.fillStyle(AbstractExcelWriteExecutor.java:116)
	at com.alibaba.excel.write.executor.AbstractExcelWriteExecutor.converterAndSet(AbstractExcelWriteExecutor.java:76)
	at com.alibaba.excel.write.executor.ExcelWriteAddExecutor.addJavaObjectToExcel(ExcelWriteAddExecutor.java:145)
	at com.alibaba.excel.write.executor.ExcelWriteAddExecutor.addOneRowOfDataToExcel(ExcelWriteAddExecutor.java:76)
	at com.alibaba.excel.write.executor.ExcelWriteAddExecutor.add(ExcelWriteAddExecutor.java:57)
	at com.alibaba.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl.java:59)
	at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:73)
	at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:50)

**Comment by zhuangjiaju** [comment]
这个要贴下代码

**Comment by zhuangjiaju** [comment]
这个是否已经解决了问题？如果无法解决 请重新打开问题
