### ISSUE TITLE
当数据列表里面有值为空的时候触发NullPointerException异常

### ISSUE THREAD

**Issue by oleilei** [alibaba/easyexcel#2132]
### 触发场景描述
当数据列表里面有值为空的时候使用会触发空指针异常
版本3.0.0-beta2

### 触发Bug的代码
ExcelWriter excelWriter = EasyExcel.write(outputStream).password(secretKey).withTemplate(inputStream).build();
List<ElemeBillOrderVo> list = ...; //不为null
excelWriter.fill(list, orderSheet);

### 提示的异常或者没有达到的效果
```
Caused by: java.lang.NullPointerException: null
        at com.alibaba.excel.converters.ConverterKeyBuild.buildKey(ConverterKeyBuild.java:29)
        at com.alibaba.excel.converters.ConverterKeyBuild.buildKey(ConverterKeyBuild.java:38)
        at com.alibaba.excel.write.executor.AbstractExcelWriteExecutor.doConvert(AbstractExcelWriteExecutor.java:306)
        at com.alibaba.excel.write.executor.AbstractExcelWriteExecutor.convert(AbstractExcelWriteExecutor.java:271)
        at com.alibaba.excel.write.executor.ExcelWriteFillExecutor.doFill(ExcelWriteFillExecutor.java:216)
        at com.alibaba.excel.write.executor.ExcelWriteFillExecutor.fill(ExcelWriteFillExecutor.java:117)
        at com.alibaba.excel.write.ExcelBuilderImpl.fill(ExcelBuilderImpl.java:82)
        at com.alibaba.excel.ExcelWriter.fill(ExcelWriter.java:110)
        at com.alibaba.excel.ExcelWriter.fill(ExcelWriter.java:98)
```

### 分析
com.alibaba.excel.write.executor.ExcelWriteFillExecutor#216行，value为null则clazz=null

WriteCellData<?> cellData = convert(writeSheetHolder, value == null ? null : value.getClass(), CellDataTypeEnum.STRING, cell, value, fieldNameContentPropertyMap.get(variable));

导致第306行，doConvert方法中：
converter = currentWriteHolder.converterMap().get(ConverterKeyBuild.buildKey(clazz, targetType));
ConverterKeyBuild.buildKey(clazz, targetType) 该调用报NullPointerException

**Comment by zhuangjiaju** [comment]
尝试下`3.0.1`版本 我未复现
