### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/poi/xssf/streaming/SXSSFWorkbook

### ISSUE THREAD

**Issue by airufei** [alibaba/easyexcel#223]
java.lang.NoClassDefFoundError: org/apache/poi/xssf/streaming/SXSSFWorkbook

	at com.alibaba.excel.util.WorkBookUtil.createWorkBook(WorkBookUtil.java:27)
	at com.alibaba.excel.context.WriteContext.<init>(WriteContext.java:103)
	at com.alibaba.excel.write.ExcelBuilderImpl.<init>(ExcelBuilderImpl.java:40)
	at com.alibaba.excel.ExcelWriter.<init>(ExcelWriter.java:58)
	at com.alibaba.excel.EasyExcelFactory.getWriter(EasyExcelFactory.java:72)

**Comment by wqh0109663** [comment]
java.lang.ClassNotFoundException: org.apache.poi.xssf.streaming.SXSSFWorkbook 一样的错误 怎么解决的？

**Comment by zhuangjiaju** [comment]
请尝试升级版本后清理本项目

**Comment by zhoujimmy** [comment]
> 请尝试升级版本后清理本项目

老哥，我现在的已经是最新的2.2.10版本了，为啥还有这个问题？

**Comment by JYHarvest** [comment]
3.1.1版本遇到相同问题，咋解决的请问
