### ISSUE TITLE
com.alibaba.excel.exception.ExcelAnalysisException: java.lang.AbstractMethodError

### ISSUE THREAD

**Issue by jiangxiaoqiang** [alibaba/easyexcel#2246]
**异常代码**

定义的接受对象实体：

```java
package com.sportswin.soa.zhuolianorg.controller.impl.user;

import com.alibaba.excel.annotation.ExcelIgnoreUnannotated;
import com.alibaba.excel.annotation.ExcelProperty;
import com.sportswin.soa.spark.contract.response.ExcelDictConverter;
import lombok.Data;

import java.io.Serializable;

@Data
@ExcelIgnoreUnannotated
public class SparkUserExcelRequest implements Serializable {

    @ExcelProperty("姓名")
    private String nickname;

    @ExcelProperty("手机号码")
    private String phone;

    @ExcelProperty(value = "性别",converter = ExcelDictConverter.class)
    private String sex;
}
```
**异常提示**

```
Caused by: com.alibaba.excel.exception.ExcelAnalysisException: java.lang.AbstractMethodError
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.analysis(ExcelAnalyserImpl.java:126) ~[easyexcel-2.2.3.jar!/:na]
	at com.alibaba.excel.ExcelReader.read(ExcelReader.java:182) ~[easyexcel-2.2.3.jar!/:na]
	at com.alibaba.excel.ExcelReader.read(ExcelReader.java:172) ~[easyexcel-2.2.3.jar!/:na]
	at com.alibaba.excel.read.builder.ExcelReaderSheetBuilder.doRead(ExcelReaderSheetBuilder.java:65) ~[easyexcel-2.2.3.jar!/:na]
	at com.sportswin.soa.zhuolianorg.controller.impl.user.OrgUserImportController.orgUserImport(OrgUserImportController.java:37) ~[classes!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_252]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_252]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_252]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) [spring-web-5.1.13.RELEASE.jar!/:5.1.13.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) [spring-web-5.1.13.RELEASE.jar!/:5.1.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105) [spring-webmvc-5.1.13.RELEASE.jar!/:5.1.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:893) ~[spring-webmvc-5.1.13.RELEASE.jar!/:5.1.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:798) ~[spring-webmvc-5.1.13.RELEASE.jar!/:5.1.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.1.13.RELEASE.jar!/:5.1.13.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) [spring-webmvc-5.1.13.RELEASE.jar!/:5.1.13.RELEASE]
	... 52 common frames omitted
Caused by: java.lang.AbstractMethodError: null
	at com.alibaba.excel.util.ConverterUtils.doConvertToJavaObject(ConverterUtils.java:133) ~[easyexcel-2.2.3.jar!/:na]
	at com.alibaba.excel.util.ConverterUtils.convertToJavaObject(ConverterUtils.java:103) ~[easyexcel-2.2.3.jar!/:na]
	at com.alibaba.excel.read.listener.ModelBuildEventListener.buildUserModel(ModelBuildEventListener.java:123) ~[easyexcel-2.2.3.jar!/:na]
	at com.alibaba.excel.read.listener.ModelBuildEventListener.invoke(ModelBuildEventListener.java:38) ~[easyexcel-2.2.3.jar!/:na]
	at com.alibaba.excel.read.listener.ModelBuildEventListener.invoke(ModelBuildEventListener.java:28) ~[easyexcel-2.2.3.jar!/:na]
	at com.alibaba.excel.read.processor.DefaultAnalysisEventProcessor.dealData(DefaultAnalysisEventProcessor.java:100) ~[easyexcel-2.2.3.jar!/:na]
	at com.alibaba.excel.read.processor.DefaultAnalysisEventProcessor.endRow(DefaultAnalysisEventProcessor.java:47) ~[easyexcel-2.2.3.jar!/:na]
```

**建议描述**

Excel的内容：

<html  xmlns:o="urn:schemas-microsoft-com:office:office"  xmlns:x="urn:schemas-microsoft-com:office:excel"  xmlns="http://www.w3.org/TR/REC-html40">
<head>

<style>

</style>

</head>
<body>

姓名 | 手机号码 | 性别 | 年龄（岁） | 身高（cm） | 学历
-- | -- | -- | -- | -- | --
华仔 | 18888888888 | 男 | 18 | 175 | 本科

</body>

</html>

自定义的转换代码：

```
public class ExcelDictConverter implements Converter<Integer> {

    private String[] dictCodIsYesNoArr = {"maritalStatus", "sex", "education", "income"};

    @Override
    public Class supportJavaTypeKey() {
        return Integer.class;
    }

    @Override
    public CellDataTypeEnum supportExcelTypeKey() {
        return CellDataTypeEnum.STRING;
    }

    @Override
    public WriteCellData<?> convertToExcelData(Integer dictKey, ExcelContentProperty excelContentProperty, GlobalConfiguration globalConfiguration) throws Exception {
        // 类里需要转换的字段
        Field field = excelContentProperty.getField();
        String fieldName = field.getName();
        String excelValue = "未知";
        // 字典值为yes_no的字段
        if (StringUtils.equalsAnyIgnoreCase(fieldName, dictCodIsYesNoArr)) {
            if ("maritalStatus".equals(fieldName)) {
                excelValue = getMStatus(dictKey);
            }
            if ("sex".equals(fieldName)) {
                excelValue = getSexStatus(dictKey);
            }
            if ("education".equals(fieldName)) {
                excelValue = getEducation(dictKey);
            }
            if ("income".equals(fieldName)) {
                excelValue = getIncome(dictKey);
            }
        }
        String cellValue = StringUtil.isBlank(excelValue) ? dictKey.toString() : excelValue;
        WriteCellData cellData = new WriteCellData();
        cellData.setType(CellDataTypeEnum.STRING);
        cellData.setStringValue(cellValue);
        cellData.setData(cellValue);
        return cellData;
    }
}

```

但是经过调试，没有运行到自定义代码。

**Comment by ccxxrrnn** [comment]
Converter<Integer> 转换为 Converter<String> 
Converter<你要转换的属性的类型> 
convertToExcelData 第一个参数就是value
可以看一下文档和源码
