### ISSUE TITLE
在windows上导出正常，但是在linux上导出时抛出字体相关的异常。未修改linux环境，修改代码以另一种输出方式后又可以正常导出了

### ISSUE THREAD

**Issue by Gengq** [alibaba/easyexcel#2258]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**

在windows上导出正常，但是在linux上导出时抛出字体相关的异常。未修改linux环境，修改代码以另一种输出方式后又可以正常导出

**触发Bug的代码**
```java
//---------------------------------------------------------写法一
vo1.java
public class vo1{
  @ExcelProperty(value = "办公电话")
  private String phone;
}
//报异常的写法
EasyExcel.write(response.getOutputStream(), vo1.class).sheet(sheetName).doWrite(data);

//---------------------------------------------------------写法二
vo2.java
public class vo2{
  private String phone;
}
//正常导出的写法
EasyExcel.write(response.getOutputStream(), vo2.class).sheet(sheetName).head(generateHeader()).doWrite(data);

private List<List<String>> generateHeader(){
  List<List<String>> ret = new ArrayList<>();
		List<String> first = new ArrayList<>();
		first.add("办公电话");
		ret.add(first);
  return ret;
}
```
**提示的异常或者没有达到的效果**
java.lang.ArrayIndexOutOfBoundsException: 0
        at sun.font.CompositeFont.getSlotFont(CompositeFont.java:351)
        at sun.font.CompositeGlyphMapper.initMapper(CompositeGlyphMapper.java:81)
        at sun.font.CompositeGlyphMapper.<init>(CompositeGlyphMapper.java:62)
        at sun.font.CompositeFont.getMapper(CompositeFont.java:409)
        at sun.font.CompositeFont.canDisplay(CompositeFont.java:435)
        at java.awt.Font.canDisplayUpTo(Font.java:2063)
        at java.awt.font.TextLayout.singleFont(TextLayout.java:470)
        at java.awt.font.TextLayout.<init>(TextLayout.java:531)
        at org.apache.poi.ss.util.SheetUtil.getDefaultCharWidth(SheetUtil.java:285)
        at org.apache.poi.xssf.streaming.AutoSizeColumnTracker.<init>(AutoSizeColumnTracker.java:117)
        at org.apache.poi.xssf.streaming.SXSSFSheet.<init>(SXSSFSheet.java:89)
        at org.apache.poi.xssf.streaming.SXSSFWorkbook.createAndRegisterSXSSFSheet(SXSSFWorkbook.java:701)
        at org.apache.poi.xssf.streaming.SXSSFWorkbook.createSheet(SXSSFWorkbook.java:722)
        at org.apache.poi.xssf.streaming.SXSSFWorkbook.createSheet(SXSSFWorkbook.java:96)
        at com.alibaba.excel.util.WorkBookUtil.createSheet(WorkBookUtil.java:84)
        at com.alibaba.excel.context.WriteContextImpl.createSheet(WriteContextImpl.java:223)
        at com.alibaba.excel.context.WriteContextImpl.initSheet(WriteContextImpl.java:203)
        at com.alibaba.excel.context.WriteContextImpl.currentSheet(WriteContextImpl.java:135)
        at com.alibaba.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl.java:54)
        at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:73)
        at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:50)
        at com.alibaba.excel.write.builder.ExcelWriterSheetBuilder.doWrite(ExcelWriterSheetBuilder.java:62)

**Comment by zhuangjiaju** [comment]
这个需要研究下 是否可以移除字体

**Comment by zhuangjiaju** [comment]
这个可以参照下：https://www.yuque.com/easyexcel/faq/vdn3lu 这个试试
