### ISSUE TITLE
addOneRowOfHeadDataToExcel IndexOutOfBoundsException

### ISSUE THREAD

**Issue by dtbdtb** [alibaba/easyexcel#2262]
各位，请帮我看看，我怎么测试都不行，谢谢先呀
pom:
****************************
		<dependency>
    <groupId>com.alibaba</groupId>
    <artifactId>easyexcel</artifactId>
    <version>2.2.6</version>
</dependency>

error:
*********************************
Warning: Could not get charToByteConverterClass!
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.alibaba.excel.context.WriteContextImpl.addOneRowOfHeadDataToExcel(WriteContextImpl.java:245)
	at com.alibaba.excel.context.WriteContextImpl.initHead(WriteContextImpl.java:225)
	at com.alibaba.excel.context.WriteContextImpl.initSheet(WriteContextImpl.java:191)
	at com.alibaba.excel.context.WriteContextImpl.currentSheet(WriteContextImpl.java:122)
	at com.alibaba.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl.java:53)
	at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:161)
	at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:146)
	at io.cypsys.modules.test.test3.main(test3.java:136)

code:
********************************
public static void main(String[] args) throws IOException {
		String outPath = "c:\\test_"+System.currentTimeMillis()+".xlsx";
        try {
            //创建ExcelWriter写入对象
            ExcelWriter excelWriter = EasyExcel.write(new FileOutputStream(outPath)).build();
            BorderStyle borderThin = BorderStyle.THIN;
            // 头的策略
            WriteCellStyle headWriteCellStyle = new WriteCellStyle();
            // 背景色
            headWriteCellStyle.setFillForegroundColor((short) 13);
            WriteFont headWriteFont = new WriteFont();
            headWriteFont.setFontHeightInPoints((short) 12);
            headWriteCellStyle.setWriteFont(headWriteFont);
            headWriteCellStyle.setBorderLeft(borderThin);
            headWriteCellStyle.setBorderTop(borderThin);
            headWriteCellStyle.setBorderRight(borderThin);
            headWriteCellStyle.setBorderBottom(borderThin);
            // 内容的策略
            WriteCellStyle contentWriteCellStyle = new WriteCellStyle();
            // 字体策略
            WriteFont contentWriteFont = new WriteFont();
            // 字体大小
            contentWriteFont.setFontHeightInPoints((short) 10);
            contentWriteCellStyle.setWriteFont(contentWriteFont);

            //设置 自动换行
            contentWriteCellStyle.setWrapped(true);
            contentWriteCellStyle.setBorderLeft(borderThin);
            contentWriteCellStyle.setBorderTop(borderThin);
            contentWriteCellStyle.setBorderRight(borderThin);
            contentWriteCellStyle.setBorderBottom(borderThin);
          // 这个策略是 头是头的样式 内容是内容的样式 其他的策略可以自己实现
            HorizontalCellStyleStrategy horizontalCellStyleStrategy =
                    new HorizontalCellStyleStrategy(headWriteCellStyle, contentWriteCellStyle);
            //创建Sheet对象
            WriteSheet sheet = new WriteSheet();
            //创建表头集合
            List<List<String>> headList = new ArrayList<List<String>>();
            //第N列的表头
            List<String> headTitle1 = new ArrayList<>();
            List<String> headTitle2 = new ArrayList<>();
            headTitle2.add("c1");
            //Dau
            headTitle2.add("c2");
            headList.add(headTitle1);
            headList.add(headTitle2);
//            table.setHead(headList);
            List<List<Object>> dataList = new ArrayList<List<Object>>();
                List<Object> data = new ArrayList<Object>();
                data.add("c1_v");
                data.add("c2_v");
                dataList.add(data);
                List<Object> data1 = new ArrayList<Object>();
                data1.add("c11_v");
                data1.add("c22_v");
                dataList.add(data1);
                logger.info("dataList.size:  " + dataList.size());
                logger.info("headList.size:  " + headList.size());
           sheet = EasyExcel.writerSheet(1, "aaa")
                    .registerWriteHandler(horizontalCellStyleStrategy).head(headList)
                    .build();
            excelWriter.write((ArrayList) data1, sheet);
            // 记得 释放资源
            excelWriter.finish();
            System.out.println("ok");
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
	}

**Comment by dtbdtb** [comment]
done
