### ISSUE TITLE
导出多个sheet 页，excelWriter.finish() 就报错，如图所示(只在第一次导出的时候会报错)

### ISSUE THREAD

**Issue by machengjun220** [alibaba/easyexcel#2291]
com.alibaba.excel.exception.ExcelGenerateException: Can not close IO.
	at com.alibaba.excel.context.WriteContextImpl.finish(WriteContextImpl.java:420) ~[easyexcel-3.0.5.jar:na]
	at com.alibaba.excel.write.ExcelBuilderImpl.finish(ExcelBuilderImpl.java:99) ~[easyexcel-3.0.5.jar:na]
	at com.alibaba.excel.ExcelWriter.finish(ExcelWriter.java:143) ~[easyexcel-3.0.5.jar:na]
	at com.alibaba.excel.ExcelWriter.finalize(ExcelWriter.java:153) ~[easyexcel-3.0.5.jar:na]
	at java.lang.System$2.invokeFinalize(System.java:1270) [na:1.8.0_261]
	at java.lang.ref.Finalizer.runFinalizer(Finalizer.java:102) [na:1.8.0_261]
	at java.lang.ref.Finalizer.access$100(Finalizer.java:34) [na:1.8.0_261]
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:217) [na:1.8.0_261]
Caused by: java.io.IOException: This archive contains unclosed entries.
	at org.apache.commons.compress.archivers.zip.ZipArchiveOutputStream.finish(ZipArchiveOutputStream.java:467) ~[commons-compress-1.19.jar:1.19]
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.injectData(SXSSFWorkbook.java:419) ~[poi-ooxml-4.1.2.jar:4.1.2]
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.write(SXSSFWorkbook.java:959) ~[poi-ooxml-4.1.2.jar:4.1.2]
	at com.alibaba.excel.context.WriteContextImpl.finish(WriteContextImpl.java:381) ~[easyexcel-3.0.5.jar:na]
	... 7 common frames omitted

2022-01-18 16:00:54.805  WARN 14692 --- [      Finalizer] com.alibaba.excel.ExcelWriter            : Destroy object failed

com.alibaba.excel.exception.ExcelGenerateException: Can not close IO.
	at com.alibaba.excel.context.WriteContextImpl.finish(WriteContextImpl.java:420) ~[easyexcel-3.0.5.jar:na]
	at com.alibaba.excel.write.ExcelBuilderImpl.finish(ExcelBuilderImpl.java:99) ~[easyexcel-3.0.5.jar:na]
	at com.alibaba.excel.ExcelWriter.finish(ExcelWriter.java:143) ~[easyexcel-3.0.5.jar:na]
	at com.alibaba.excel.ExcelWriter.finalize(ExcelWriter.java:153) ~[easyexcel-3.0.5.jar:na]
	at java.lang.System$2.invokeFinalize(System.java:1270) [na:1.8.0_261]
	at java.lang.ref.Finalizer.runFinalizer(Finalizer.java:102) [na:1.8.0_261]
	at java.lang.ref.Finalizer.access$100(Finalizer.java:34) [na:1.8.0_261]
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:217) [na:1.8.0_261]
Caused by: java.io.IOException: This archive contains unclosed entries.
	at org.apache.commons.compress.archivers.zip.ZipArchiveOutputStream.finish(ZipArchiveOutputStream.java:467) ~[commons-compress-1.19.jar:1.19]
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.injectData(SXSSFWorkbook.java:419) ~[poi-ooxml-4.1.2.jar:4.1.2]
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.write(SXSSFWorkbook.java:959) ~[poi-ooxml-4.1.2.jar:4.1.2]
	at com.alibaba.excel.context.WriteContextImpl.finish(WriteContextImpl.java:381) ~[easyexcel-3.0.5.jar:na]
	... 7 common frames omitted

**Comment by machengjun220** [comment]
> com.alibaba.excel.exception.ExcelGenerateException: Can not close IO. at com.alibaba.excel.context.WriteContextImpl.finish(WriteContextImpl.java:420) ~[easyexcel-3.0.5.jar:na] at com.alibaba.excel.write.ExcelBuilderImpl.finish(ExcelBuilderImpl.java:99) ~[easyexcel-3.0.5.jar:na] at com.alibaba.excel.ExcelWriter.finish(ExcelWriter.java:143) ~[easyexcel-3.0.5.jar:na] at com.alibaba.excel.ExcelWriter.finalize(ExcelWriter.java:153) ~[easyexcel-3.0.5.jar:na] at java.lang.System$2.invokeFinalize(System.java:1270) [na:1.8.0_261] at java.lang.ref.Finalizer.runFinalizer(Finalizer.java:102) [na:1.8.0_261] at java.lang.ref.Finalizer.access$100(Finalizer.java:34) [na:1.8.0_261] at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:217) [na:1.8.0_261] Caused by: java.io.IOException: This archive contains unclosed entries. at org.apache.commons.compress.archivers.zip.ZipArchiveOutputStream.finish(ZipArchiveOutputStream.java:467) ~[commons-compress-1.19.jar:1.19] at org.apache.poi.xssf.streaming.SXSSFWorkbook.injectData(SXSSFWorkbook.java:419) ~[poi-ooxml-4.1.2.jar:4.1.2] at org.apache.poi.xssf.streaming.SXSSFWorkbook.write(SXSSFWorkbook.java:959) ~[poi-ooxml-4.1.2.jar:4.1.2] at com.alibaba.excel.context.WriteContextImpl.finish(WriteContextImpl.java:381) ~[easyexcel-3.0.5.jar:na] ... 7 common frames omitted
> 
> 2022-01-18 16:00:54.805 WARN 14692 --- [ Finalizer] com.alibaba.excel.ExcelWriter : Destroy object failed
> 
> com.alibaba.excel.exception.ExcelGenerateException: Can not close IO. at com.alibaba.excel.context.WriteContextImpl.finish(WriteContextImpl.java:420) ~[easyexcel-3.0.5.jar:na] at com.alibaba.excel.write.ExcelBuilderImpl.finish(ExcelBuilderImpl.java:99) ~[easyexcel-3.0.5.jar:na] at com.alibaba.excel.ExcelWriter.finish(ExcelWriter.java:143) ~[easyexcel-3.0.5.jar:na] at com.alibaba.excel.ExcelWriter.finalize(ExcelWriter.java:153) ~[easyexcel-3.0.5.jar:na] at java.lang.System$2.invokeFinalize(System.java:1270) [na:1.8.0_261] at java.lang.ref.Finalizer.runFinalizer(Finalizer.java:102) [na:1.8.0_261] at java.lang.ref.Finalizer.access$100(Finalizer.java:34) [na:1.8.0_261] at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:217) [na:1.8.0_261] Caused by: java.io.IOException: This archive contains unclosed entries. at org.apache.commons.compress.archivers.zip.ZipArchiveOutputStream.finish(ZipArchiveOutputStream.java:467) ~[commons-compress-1.19.jar:1.19] at org.apache.poi.xssf.streaming.SXSSFWorkbook.injectData(SXSSFWorkbook.java:419) ~[poi-ooxml-4.1.2.jar:4.1.2] at org.apache.poi.xssf.streaming.SXSSFWorkbook.write(SXSSFWorkbook.java:959) ~[poi-ooxml-4.1.2.jar:4.1.2] at com.alibaba.excel.context.WriteContextImpl.finish(WriteContextImpl.java:381) ~[easyexcel-3.0.5.jar:na] ... 7 common frames omitted

解决了，我创建了2个ExcelWriter!

ExcelWriterSheetBuilder builder = excelWriterBuilder.sheet();
WriteSheet sheet = sheetBuilder.sheetNo(sheetNo).sheetName(sheetName);
并且手动创建了ExcelWriter

ExcelWriter writer = excelWriterBuilder.build();
结果创建了两个ExcelWriter对象(sheet()方法也创建了一个)，导致finish()方法被执行了两次，一次手动执行，一次ExcelWriter.finalize()执行，第一次流被关闭后，第二次就抛异常了.
