### ISSUE TITLE
java.io.IOException: Zip bomb detected!

### ISSUE THREAD

**Issue by Ryoui** [alibaba/easyexcel#2340]
**建议先去看文档**
[快速开始](https://www.yuque.com/easyexcel/doc/easyexcel) 、[常见问题](https://www.yuque.com/easyexcel/faq)
**触发场景描述**

**触发Bug的代码**
```java
   ExcelReader excelReader = EasyExcel.read(excelFile.getInputStream()).registerReadListener(listener).build();
```
**提示的异常或者没有达到的效果**
com.alibaba.excel.exception.ExcelAnalysisException: java.io.IOException: Zip bomb detected! The file would exceed the max. ratio of compressed file size to the size of the expanded data.
This may indicate that the file is used to inflate memory usage and thus could pose a security risk.
You can adjust this limit via ZipSecureFile.setMinInflateRatio() if you need to work with files which exceed this limit.
Counter: 827282, cis.counter: 8192, ratio: 0.009902306589530535
Limits: MIN_INFLATE_RATIO: 0.01
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.<init>(ExcelAnalyserImpl.java:57)
	at com.alibaba.excel.ExcelReader.<init>(ExcelReader.java:145)
	at com.alibaba.excel.read.builder.ExcelReaderBuilder.build(ExcelReaderBuilder.java:193)

**Comment by TungMan0801** [comment]
Hello Mr Zhuang, we are a school group for the course Software Engineering. We want to offer to try to fix or develop this issue, or at least do a little contribution! If this bug has been fixed please just leave a comment, thanks! Hope to get your consent and support:)
