### ISSUE TITLE
在alpine docker上面报这个错 NoSuchFieldError: Factory 

### ISSUE THREAD

**Issue by lincanyitse** [alibaba/easyexcel#2387]
**异常代码**
```java
File excel = new File("/tmp/upload/统计-" + System.currentTimeMillis() + ".xlsx");
 FileOutputStream file = null;
try {
    file = new FileOutputStream(excel);
    ExcelWriter excelWriter = EasyExcel.write(file).build();
} catch (FileNotFoundException e) {
   e.printStackTrace();
}
```
**异常提示**
Servlet.service() for servlet [dispatcherServlet] in context with path [/organize] threw exception [Request processing failed; nested exception is com.alibaba.excel.exception.ExcelGenerateException: java.lang.NoSuchFieldError: Factory] with root cause
java.lang.NoSuchFieldError: Factory
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.onWorkbookCreate(XSSFWorkbook.java:456) ~[poi-ooxml-5.1.0.jar:5.1.0]
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:252) ~[poi-ooxml-5.1.0.jar:5.1.0]
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:246) ~[poi-ooxml-5.1.0.jar:5.1.0]
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:234) ~[poi-ooxml-5.1.0.jar:5.1.0]
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.<init>(SXSSFWorkbook.java:260) ~[poi-ooxml-5.1.0.jar:5.1.0]
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.<init>(SXSSFWorkbook.java:230) ~[poi-ooxml-5.1.0.jar:5.1.0]
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.<init>(SXSSFWorkbook.java:205) ~[poi-ooxml-5.1.0.jar:5.1.0]
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.<init>(SXSSFWorkbook.java:292) ~[poi-ooxml-5.1.0.jar:5.1.0]
	at com.alibaba.excel.util.WorkBookUtil.createWorkBook(WorkBookUtil.java:45) ~[easyexcel-2.2.6.jar:na]
	at com.alibaba.excel.context.WriteContextImpl.<init>(WriteContextImpl.java:85) ~[easyexcel-2.2.6.jar:na]
	at com.alibaba.excel.write.ExcelBuilderImpl.<init>(ExcelBuilderImpl.java:35) ~[easyexcel-2.2.6.jar:na]
	at com.alibaba.excel.ExcelWriter.<init>(ExcelWriter.java:47) ~[easyexcel-2.2.6.jar:na]
	at com.alibaba.excel.write.builder.ExcelWriterBuilder.build(ExcelWriterBuilder.java:130) ~[easyexcel-2.2.6.jar:na]

**Comment by zhuangjiaju** [comment]
poi 使用 4.1.2版本
