### ISSUE TITLE
一个异常

### ISSUE THREAD

**Issue by wolrdprogrammer9823** [alibaba/easyexcel#254]
异常信息如下:
 java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/xml/stream/XMLEventFactory;
        at org.apache.poi.openxml4j.opc.internal.marshallers.PackagePropertiesMarshaller.<clinit>(PackagePropertiesMarshaller.java:41)
        at org.apache.poi.openxml4j.opc.OPCPackage.init(OPCPackage.java:161)
        at org.apache.poi.openxml4j.opc.OPCPackage.<init>(OPCPackage.java:141)
        at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:72)
        at org.apache.poi.openxml4j.opc.OPCPackage.create(OPCPackage.java:394)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.newPackage(XSSFWorkbook.java:480)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:247)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:239)
        at org.apache.poi.xssf.streaming.SXSSFWorkbook.<init>(SXSSFWorkbook.java:241)
        at org.apache.poi.xssf.streaming.SXSSFWorkbook.<init>(SXSSFWorkbook.java:211)
        at org.apache.poi.xssf.streaming.SXSSFWorkbook.<init>(SXSSFWorkbook.java:186)
        at org.apache.poi.xssf.streaming.SXSSFWorkbook.<init>(SXSSFWorkbook.java:272)
        at com.alibaba.excel.util.WorkBookUtil.createWorkBook(WorkBookUtil.java:27)
        at com.alibaba.excel.context.WriteContext.<init>(WriteContext.java:98)
        at com.alibaba.excel.write.ExcelBuilderImpl.<init>(ExcelBuilderImpl.java:38)
        at com.alibaba.excel.ExcelWriter.<init>(ExcelWriter.java:58)
        at com.alibaba.excel.ExcelWriter.<init>(ExcelWriter.java:34)

**Comment by stonesingsong** [comment]
看看是不是因为你pom里同时写了poi的依赖，easyexcel自身依赖了poi

**Comment by wolrdprogrammer9823** [comment]
> 看看是不是因为你pom里同时写了poi的依赖，easyexcel自身依赖了poi
