### ISSUE TITLE
模板类中定义字段属性为Double，业务在Excel文件中对应的列填中文或者非数字类型，读取会报错，想回写失败行到失败文件，怎么处理这种场景？

### ISSUE THREAD

**Issue by lihaojieM** [alibaba/easyexcel#2564]
如标题所示，模板类中定义字段属性为Double，业务在Excel文件中对应的列填中文或者非数字类型，读取会报错，报错如下：

**异常提示**
com.alibaba.excel.exception.ExcelDataConvertException: Convert data com.alibaba.excel.metadata.data.ReadCellData@1cc238fb to class java.lang.Double error
at com.alibaba.excel.util.ConverterUtils.doConvertToJavaObject(ConverterUtils.java:155)
at com.alibaba.excel.util.ConverterUtils.convertToJavaObject(ConverterUtils.java:100)
at com.alibaba.excel.read.listener.ModelBuildEventListener.buildUserModel(ModelBuildEventListener.java:103)
at com.alibaba.excel.read.listener.ModelBuildEventListener.invoke(ModelBuildEventListener.java:41)
at com.alibaba.excel.read.listener.ModelBuildEventListener.invoke(ModelBuildEventListener.java:26)
at com.alibaba.excel.read.processor.DefaultAnalysisEventProcessor.dealData(DefaultAnalysisEventProcessor.java:99)
at com.alibaba.excel.read.processor.DefaultAnalysisEventProcessor.endRow(DefaultAnalysisEventProcessor.java:46)
at com.alibaba.excel.analysis.v03.handlers.DummyRecordHandler.processRecord(DummyRecordHandler.java:32)
at com.alibaba.excel.analysis.v03.XlsSaxAnalyser.processRecord(XlsSaxAnalyser.java:157)
at org.apache.poi.hssf.eventusermodel.MissingRecordAwareHSSFListener.processRecord(MissingRecordAwareHSSFListener.java:158)
at org.apache.poi.hssf.eventusermodel.FormatTrackingHSSFListener.processRecord(FormatTrackingHSSFListener.java:92)
at org.apache.poi.hssf.eventusermodel.HSSFRequest.processRecord(HSSFRequest.java:109)
at org.apache.poi.hssf.eventusermodel.HSSFEventFactory.genericProcessEvents(HSSFEventFactory.java:179)
at org.apache.poi.hssf.eventusermodel.HSSFEventFactory.processEvents(HSSFEventFactory.java:136)
at org.apache.poi.hssf.eventusermodel.HSSFEventFactory.processWorkbookEvents(HSSFEventFactory.java:82)
at org.apache.poi.hssf.eventusermodel.HSSFEventFactory.processWorkbookEvents(HSSFEventFactory.java:54)
at com.alibaba.excel.analysis.v03.XlsSaxAnalyser.execute(XlsSaxAnalyser.java:136)
at com.alibaba.excel.analysis.ExcelAnalyserImpl.analysis(ExcelAnalyserImpl.java:124)
at com.alibaba.excel.ExcelReader.read(ExcelReader.java:63)
at com.alibaba.excel.ExcelReader.read(ExcelReader.java:53)
at com.alibaba.excel.read.builder.ExcelReaderSheetBuilder.doRead(ExcelReaderSheetBuilder.java:65)

**Comment by zhuangjiaju** [comment]
参照：https://easyexcel.opensource.alibaba.com/docs/current/quickstart/read#%E6%95%B0%E6%8D%AE%E8%BD%AC%E6%8D%A2%E7%AD%89%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86
自己处理

**Comment by Alisa510** [comment]
你好我现在也遇到这个问题了，就是Excel接收的字段是Double可是导入的时候传的是字符串或者横线这种就直接报错Convert data com.alibaba.excel.metadata.data.ReadCellData@dcc00b25 to class java.lang.Double error 这个了，定义了监听器也没用呀，虽然会跳过这行数据读取下一行，但是如果我每行数据都有一列填的横线 这种，就所有的都跳过了，这个要怎么解决呀，你的问题最后是怎么解决的呀，chatgpt也拯救不了这个，愁死了，如果有解决的话可以回复一下嘛，十分感谢了
