### ISSUE TITLE
多图片文件下载时堆溢出

### ISSUE THREAD

**Issue by tian-jeff** [alibaba/easyexcel#2581]
我们需要生成的Excel中，某两列为图片格式，当图片到一定数量后，写文件会报错，具体错误为：
```
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3236)
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
	at java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:253)
	at java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:211)
	at java.util.zip.ZipOutputStream.write(ZipOutputStream.java:331)
	at org.apache.poi.openxml4j.opc.internal.marshallers.ZipPartMarshaller.marshall(ZipPartMarshaller.java:90)
	at org.apache.poi.openxml4j.opc.internal.MemoryPackagePart.save(MemoryPackagePart.java:112)
	at org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller.marshall(DefaultMarshaller.java:43)
	at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:585)
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1539)
	at org.apache.poi.openxml4j.opc.OPCPackage.close(OPCPackage.java:482)
	at org.apache.poi.POIXMLDocument.close(POIXMLDocument.java:189)
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.close(SXSSFWorkbook.java:909)
	at com.alibaba.excel.context.WriteContextImpl.finish(WriteContextImpl.java:341)
	at com.alibaba.excel.write.ExcelBuilderImpl.finish(ExcelBuilderImpl.java:95)
	at com.alibaba.excel.ExcelWriter.finish(ExcelWriter.java:329)
```

**Comment by zhuangjiaju** [comment]
// 这里注意下 所有的图片都会放到内存 暂时没有很好的解法，大量图片的情况下建议 2选1:
        // 1. 将图片上传到oss 或者其他存储网站: https://www.aliyun.com/product/oss ，然后直接放链接
        // 2. 使用: https://github.com/coobird/thumbnailator 或者其他工具压缩图片

**Comment by yaya56** [comment]
> // 这里注意下 所有的图片都会放到内存 暂时没有很好的解法，大量图片的情况下建议 2选1: // 1. 将图片上传到oss 或者其他存储网站: https://www.aliyun.com/product/oss ，然后直接放链接 // 2. 使用: https://github.com/coobird/thumbnailator 或者其他工具压缩图片

poi后续的版本是有解决这个问题的,5+版本,使用临时文件解决的,不过目前easyexcel不支持那个版本
