### ISSUE TITLE
ehcache缓存在目录/tmp被系统清理导致异常

### ISSUE THREAD

**Issue by weibin992** [alibaba/easyexcel#2693]
**触发场景描述**
1. 读取Excel大文件使用了ehcache缓存，默认缓存文件存放于/tmp目录下，此目录会被系统定时清理不活跃文件
2. [com.alibaba.excel.cache.Ehcache](https://github.com/alibaba/easyexcel/blob/master/easyexcel-core/src/main/java/com/alibaba/excel/cache/Ehcache.java) 此类的CacheManager为静态变量，在类初始化时缓存路径被固定为/tmp下的某个目录
3. 当我上传一次，之后隔了十几天再次上传大文件，此时缓存根目录已被系统清理，无法创建缓存文件导致异常   

**触发Bug的代码**
```java
EasyExcel.read(stream, listener).sheet(sheetIndex).doRead();
```
**提示的异常**
```
Caused by: org.ehcache.CachePersistenceException: Unable to create or reuse directory: /tmp/e1d50dbf-0368-40f4-a1da-43acb9b18a9b/excache/409492a2-54a9-48e4-bbb5-02e27b297968/file
        at org.ehcache.impl.persistence.FileUtils.create(FileUtils.java:98)
        at org.ehcache.impl.persistence.DefaultLocalPersistenceService.createSafeSpace(DefaultLocalPersistenceService.java:166)
        at org.ehcache.impl.persistence.DefaultDiskResourceService.createSpace(DefaultDiskResourceService.java:150)
        at org.ehcache.impl.persistence.DefaultDiskResourceService.getPersistenceSpaceIdentifier(DefaultDiskResourceService.java:109)
        at org.ehcache.core.EhcacheManager.getStore(EhcacheManager.java:439)
        ... 61 common frames omitted
```
**临时解决方案**
1. 修改java.io.tmpdir为其他目录
2. 通过反射取得类初始化时的缓存根目录，每次调用前检测目录是否存在，不存在则创建

**Comment by zhuangjiaju** [comment]
已经在最新版本修复
