### ISSUE TITLE
3.10读取excel文件出现数组越界异常 java.lang.ArrayIndexOutOfBoundsException: -32768

### ISSUE THREAD

**Issue by CoderM19** [alibaba/easyexcel#2763]
异常堆栈信息如下：
  
java.lang.ArrayIndexOutOfBoundsException: -32768
	at java.util.ArrayList.elementData(ArrayList.java:422)
	at java.util.ArrayList.get(ArrayList.java:435)
	at org.apache.poi.hssf.eventusermodel.FormatTrackingHSSFListener.getFormatIndex(FormatTrackingHSSFListener.java:194)
	at com.alibaba.excel.analysis.v03.handlers.NumberRecordHandler.processRecord(NumberRecordHandler.java:27)
	at com.alibaba.excel.analysis.v03.XlsSaxAnalyser.processRecord(XlsSaxAnalyser.java:157)
	at org.apache.poi.hssf.eventusermodel.MissingRecordAwareHSSFListener.processRecord(MissingRecordAwareHSSFListener.java:201)
	at org.apache.poi.hssf.eventusermodel.FormatTrackingHSSFListener.processRecord(FormatTrackingHSSFListener.java:94)
	at org.apache.poi.hssf.eventusermodel.HSSFRequest.processRecord(HSSFRequest.java:106)
	at org.apache.poi.hssf.eventusermodel.HSSFEventFactory.genericProcessEvents(HSSFEventFactory.java:172)
	at org.apache.poi.hssf.eventusermodel.HSSFEventFactory.processEvents(HSSFEventFactory.java:129)
	at org.apache.poi.hssf.eventusermodel.HSSFEventFactory.processWorkbookEvents(HSSFEventFactory.java:80)
	at org.apache.poi.hssf.eventusermodel.HSSFEventFactory.processWorkbookEvents(HSSFEventFactory.java:53)
	at com.alibaba.excel.analysis.v03.XlsSaxAnalyser.execute(XlsSaxAnalyser.java:136)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.analysis(ExcelAnalyserImpl.java:124)
	at com.alibaba.excel.ExcelReader.read(ExcelReader.java:63)
	at com.alibaba.excel.ExcelReader.read(ExcelReader.java:53)
	at com.alibaba.excel.read.builder.ExcelReaderSheetBuilder.doRead(ExcelReaderSheetBuilder.java:65)

**Comment by gongxuanzhang** [comment]
麻烦提供下excel和代码
