### ISSUE TITLE
读取excel 当中带文件目录的数据 时 报 Illegal character in path at index

### ISSUE THREAD

**Issue by hostkey918** [alibaba/easyexcel#2773]
java.net.URISyntaxException: Illegal character in path at index 75: file://///XXXXXX/
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at org.apache.poi.openxml4j.opc.PackagingURIHelper.toURI(PackagingURIHelper.java:723)
	at org.apache.poi.openxml4j.opc.PackageRelationshipCollection.parseRelationshipsPart(PackageRelationshipCollection.java:358)
	at org.apache.poi.openxml4j.opc.PackageRelationshipCollection.<init>(PackageRelationshipCollection.java:160)
	at org.apache.poi.openxml4j.opc.PackageRelationshipCollection.<init>(PackageRelationshipCollection.java:130)
	at org.apache.poi.openxml4j.opc.PackagePart.loadRelationships(PackagePart.java:565)
	at org.apache.poi.openxml4j.opc.OPCPackage.getParts(OPCPackage.java:751)
	at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:288)
	at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:192)
	at com.alibaba.excel.analysis.v07.XlsxSaxAnalyser.readOpcPackage(XlsxSaxAnalyser.java:191)
	at com.alibaba.excel.analysis.v07.XlsxSaxAnalyser.<init>(XlsxSaxAnalyser.java:89)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.choiceExcelExecutor(ExcelAnalyserImpl.java:103)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.<init>(ExcelAnalyserImpl.java:55)
	at com.alibaba.excel.ExcelReader.<init>(ExcelReader.java:27)
	at com.alibaba.excel.read.builder.ExcelReaderBuilder.build(ExcelReaderBuilder.java:202)

**Comment by hostkey918** [comment]
版本3.1.1

**Comment by zhuangjiaju** [comment]
你直接 `new  File().getAbsolutePath()` 试试

**Comment by gongxuanzhang** [comment]
不知道您是否已经通过其他渠道解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue

**Comment by liyuan-hu** [comment]
我也遇到了这个问题，请问解决了吗

**Comment by hostkey918** [comment]
没有
















在 2024-11-07 17:11:37，"liyuan-hu" ***@***.***> 写道：

我也遇到了这个问题，请问解决了吗
