### ISSUE TITLE
使用EasyExcel.write()方法写入Web数据量大时错误

### ISSUE THREAD

**Issue by blacke97** [alibaba/easyexcel#2778]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**触发场景描述**
使用EasyExcel.write()方法写入Web数据量大时错误，大概几百行的数据，每行有30+列，文件下载大小100kb左右。数据小的时候并没有此异常。
**触发Bug的代码**
```java
               EasyExcel.write(response.getOutputStream()).registerWriteHandler(new CustomCellWriteHandler()).sheet("sheet1").head(headers).doWrite(res);

```
**提示的异常或者没有达到的效果**
经过调试，在doWrite()方法里面出错，控制台异常信息为：
com.alibaba.excel.exception.ExcelGenerateException: Can not close IO.
	at com.alibaba.excel.context.WriteContextImpl.finish(WriteContextImpl.java:420)
	at com.alibaba.excel.write.ExcelBuilderImpl.finish(ExcelBuilderImpl.java:99)
	at com.alibaba.excel.ExcelWriter.finish(ExcelWriter.java:140)
	at com.alibaba.excel.write.builder.ExcelWriterSheetBuilder.doWrite(ExcelWriterSheetBuilder.java:63)；
经过调试抛出提示信息为：java.io.Exception: This archive contains unclosed entries. 于WriteContextImpl.java文件finih()方法

**Comment by zhbotong** [comment]
建议提供可以复现的测试用例

**Comment by blacke97** [comment]
来信已收到。

**Comment by blacke97** [comment]
今天要复现来着，发现复现不了了，没有问题了，很奇怪。
