### ISSUE TITLE
不创建对象的读 使用匿名内部类报错

### ISSUE THREAD

**Issue by peacefulOrchids** [alibaba/easyexcel#2812]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**异常代码**
```java
   EasyExcel.read(file, Map.class, new AnalysisEventListener<Map<Integer, String>>() {
			Map<Integer, String> headMap = new HashMap<>();
			CatalogueRecordBatch crb = null;
			String bibNo = null;
			Long crbId = 0L;
			@Override
			public void invokeHead(Map<Integer, ReadCellData<?>> headMap, AnalysisContext context) {
				log.info("解析到一条头数据:{}", JSON.toJSONString(headMap));
				this.headMap = ConverterUtils.convertToStringMap(headMap, context);
				// 如果想转成成 Map<Integer,String>
				// 方案1： 不要implements ReadListener 而是 extends AnalysisEventListener
				// 方案2： 调用 ConverterUtils.convertToStringMap(headMap, context) 自动会转换
			}
			@Override
			public void invoke(Map<Integer, String> o, AnalysisContext analysisContext) {
				itemCount[0]++;
				crbId = SnowflakeIdUtil.getUUID(CatalogueRecordBatch.class);
				crb = new CatalogueRecordBatch();
				crb.setId(crbId);
				crb.setJobId(batch.getId());
				crb.setJobNo(batch.getJobNo());
				for(Integer key : headMap.keySet()){
					String filedName = headMap.get(key);
					String value = o.get(key);
					if("Identifier.Bibno".equalsIgnoreCase(filedName)){
						bibNo = value;
						CatalogueRecordBatch crb = crbMap.get(filedName);
						if (crb == null) {
							crb = new CatalogueRecordBatch();
							crb.setId(crbId);
							crb.setJobId(batch.getId());
							crb.setJobNo(batch.getJobNo());
							crb.setCatalogueNo(value);
							crb.setStatus(CatalogueItemStatusEnum.NEW.getCode());
//							crb.setCatalogueAccnNo(o.getAccnNo());
							crb.setItemNo(IdUtils.DateTimeIDLong());
							if (!ExistsBibNo(value)) {
								recordBatchService.save(crb);
								successBibNoList.put(value, "添加成功");
								catalogueSuccessMap.put(bf.getFileName() + "-" +value, crb);
								itemCount[1]++;
							} else {
								errorBibNoList.put(value, "数据已存在数据库中");
								catalogueErrorMap.put(bf.getFileName() + "-" + value, crb);
							}
						}else{
							this.crb = crb;
						}
					}else if("Identifier.ACCN".equalsIgnoreCase(filedName)){
						crb.setCatalogueAccnNo(value);
						recordBatchMapper.updateById(crb);
					}
					//解析元数据数据
					addField(filedName, value, crb);
				}
			}

			@Override
			public void doAfterAllAnalysed(AnalysisContext analysisContext) {

			}
		}).sheet().doRead();
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
com.alibaba.excel.exception.ExcelDataConvertException: Can not instance class: java.util.Map
	at com.alibaba.excel.read.listener.ModelBuildEventListener.buildUserModel(ModelBuildEventListener.java:91)
	at com.alibaba.excel.read.listener.ModelBuildEventListener.invoke(ModelBuildEventListener.java:41)
	at com.alibaba.excel.read.listener.ModelBuildEventListener.invoke(ModelBuildEventListener.java:26)
	at com.alibaba.excel.read.processor.DefaultAnalysisEventProcessor.dealData(DefaultAnalysisEventProcessor.java:99)
	at com.alibaba.excel.read.processor.DefaultAnalysisEventProcessor.endRow(DefaultAnalysisEventProcessor.java:46)
	at com.alibaba.excel.analysis.v07.handlers.RowTagHandler.endElement(RowTagHandler.java:66)
	at com.alibaba.excel.analysis.v07.handlers.sax.XlsxRowHandler.endElement(XlsxRowHandler.java:91)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:618)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1728)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2899)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:542)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:889)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:825)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:637)
	at com.alibaba.excel.analysis.v07.XlsxSaxAnalyser.parseXmlSource(XlsxSaxAnalyser.java:203)
	at com.alibaba.excel.analysis.v07.XlsxSaxAnalyser.execute(XlsxSaxAnalyser.java:224)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.analysis(ExcelAnalyserImpl.java:124)
	at com.alibaba.excel.ExcelReader.read(ExcelReader.java:63)
	at com.alibaba.excel.ExcelReader.read(ExcelReader.java:53)
	at com.alibaba.excel.read.builder.ExcelReaderSheetBuilder.doRead(ExcelReaderSheetBuilder.java:65)
	at cn.tcsoft.drm.service.job.BatchUpload.parseFlexExcelNewspaper(BatchUpload.java:1284)
	at cn.tcsoft.drm.service.job.BatchUpload.newspaper(BatchUpload.java:858)
	at cn.tcsoft.drm.service.job.BatchUpload.uploadBatchJob(BatchUpload.java:169)
	at cn.tcsoft.drm.consumer.CatalogueRocketMqConsumer.onMessage(CatalogueRocketMqConsumer.java:41)
	at cn.tcsoft.drm.consumer.CatalogueRocketMqConsumer.onMessage(CatalogueRocketMqConsumer.java:25)
	at org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer.handleMessage(DefaultRocketMQListenerContainer.java:449)
	at org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer.access$100(DefaultRocketMQListenerContainer.java:71)
	at org.apache.rocketmq.spring.support.DefaultRocketMQListenerContainer$DefaultMessageListenerConcurrently.consumeMessage(DefaultRocketMQListenerContainer.java:409)
	at org.apache.rocketmq.client.impl.consumer.ConsumeMessageConcurrentlyService$ConsumeRequest.run(ConsumeMessageConcurrentlyService.java:402)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.InstantiationException: java.util.Map
	at java.base/java.lang.Class.newInstance(Class.java:639)
	at com.alibaba.excel.read.listener.ModelBuildEventListener.buildUserModel(ModelBuildEventListener.java:87)
	... 37 more
Caused by: java.lang.NoSuchMethodException: java.util.Map.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3585)
	at java.base/java.lang.Class.newInstance(Class.java:626)
	... 38 more
**建议描述**
希望能够使用匿名内部类来实现不创建对象的读

**Comment by gongxuanzhang** [comment]
这应该不是匿名类的问题  应该是环境问题

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
