### ISSUE TITLE
1.2.5 beta版本中字符串转数字的时候没有去除尾部空格

### ISSUE THREAD

**Issue by fruitdish** [alibaba/easyexcel#286]
1.2.5 beta版本中字符串转数字的时候没有去除尾部空格
excel的列格式为文本格式，测试的时候刻意加入了数字后的尾部空格。
结果抛出错误：
Caused by: com.alibaba.excel.exception.ExcelGenerateException: java.lang.NumberFormatException: For input string: "100 "
	at com.alibaba.excel.modelbuild.ModelBuildEventListener.invoke(ModelBuildEventListener.java:24) ~[easyexcel-1.1.2-beta5.jar:na]
	at com.alibaba.excel.analysis.BaseSaxAnalyser.notifyListeners(BaseSaxAnalyser.java:72) ~[easyexcel-1.1.2-beta5.jar:na]
	at com.alibaba.excel.analysis.v07.XlsxRowHandler.endRow(XlsxRowHandler.java:132) ~[easyexcel-1.1.2-beta5.jar:na]
	at com.alibaba.excel.analysis.v07.XlsxRowHandler.endElement(XlsxRowHandler.java:110) ~[easyexcel-1.1.2-beta5.jar:na]
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
	at com.alibaba.excel.analysis.v07.XlsxSaxAnalyser.parseXmlSource(XlsxSaxAnalyser.java:97) ~[easyexcel-1.1.2-beta5.jar:na]
	... 108 common frames omitted
Caused by: java.lang.NumberFormatException: For input string: "100 "
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0_151]
	at java.lang.Long.parseLong(Long.java:589) ~[na:1.8.0_151]
	at java.lang.Long.parseLong(Long.java:631) ~[na:1.8.0_151]
	at com.alibaba.excel.util.TypeUtil.convert(TypeUtil.java:72) ~[easyexcel-1.1.2-beta5.jar:na]
	at com.alibaba.excel.util.TypeUtil.getFieldValues(TypeUtil.java:228) ~[easyexcel-1.1.2-beta5.jar:na]
	at com.alibaba.excel.modelbuild.ModelBuildEventListener.buildUserModel(ModelBuildEventListener.java:36) ~[easyexcel-1.1.2-beta5.jar:na]
	at com.alibaba.excel.modelbuild.ModelBuildEventListener.invoke(ModelBuildEventListener.java:21) ~[easyexcel-1.1.2-beta5.jar:na]
	... 121 common frames omitted

虽然有些钻牛角尖，但是这个问题有可能在输入的时候存在。

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。
