### ISSUE TITLE
建议支持对象中的Map数据类型

### ISSUE THREAD

**Issue by bigskyfish** [alibaba/easyexcel#2861]
**问题描述**
对象中某属性类型为Map，出现以下报错：
com.alibaba.excel.exception.ExcelWriteDataConvertException: Can not find 'Converter' support class Map.

	at com.alibaba.excel.write.executor.AbstractExcelWriteExecutor.doConvert(AbstractExcelWriteExecutor.java:323)
	at com.alibaba.excel.write.executor.AbstractExcelWriteExecutor.convert(AbstractExcelWriteExecutor.java:277)
	at com.alibaba.excel.write.executor.AbstractExcelWriteExecutor.converterAndSet(AbstractExcelWriteExecutor.java:58)
	at com.alibaba.excel.write.executor.ExcelWriteAddExecutor.addJavaObjectToExcel(ExcelWriteAddExecutor.java:174)
	at com.alibaba.excel.write.executor.ExcelWriteAddExecutor.addOneRowOfDataToExcel(ExcelWriteAddExecutor.java:82)
	at com.alibaba.excel.write.executor.ExcelWriteAddExecutor.add(ExcelWriteAddExecutor.java:58)
	at com.alibaba.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl.java:59)
	at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:70)
	at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:47)
	at com.alibaba.excel.write.builder.ExcelWriterSheetBuilder.doWrite(ExcelWriterSheetBuilder.java:62)
**建议描述**
将Map转为Json字符串后，作为String进行展示。

**Comment by LoneGunnerMe** [comment]
这玩意你自己写个转换器就行了呗...

**Comment by zhuangjiaju** [comment]
自定义转换器，或者把map对象直接改成string
