### ISSUE TITLE
Poi5和easyexcel 3.1.4冲突

### ISSUE THREAD

**Issue by java-zengguang** [alibaba/easyexcel#2893]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**异常代码**
```java
   这里写你的代码
```
**异常提示**
请提供完整的异常提示,记住是全部异常！
**建议描述**

**Comment by java-zengguang** [comment]
easyexcel和poi冲突，在easyexcel核心包里有poi模块的的包，引入poi模块，报模块从两个模块引入，去掉引用包找不到类
Exception in thread "main" com.alibaba.excel.exception.ExcelGenerateException: java.lang.NoClassDefFoundError: org/apache/poi/util/POILogFactory
	at easyexcel.core@3.1.4/com.alibaba.excel.write.ExcelBuilderImpl.<init>(ExcelBuilderImpl.java:42)
	at easyexcel.core@3.1.4/com.alibaba.excel.ExcelWriter.<init>(ExcelWriter.java:36)
	at easyexcel.core@3.1.4/com.alibaba.excel.write.builder.ExcelWriterBuilder.build(ExcelWriterBuilder.java:114)
	at easyexcel.core@3.1.4/com.alibaba.excel.write.builder.ExcelWriterBuilder.sheet(ExcelWriterBuilder.java:130)
	at easyexcel.core@3.1.4/com.alibaba.excel.write.builder.ExcelWriterBuilder.sheet(ExcelWriterBuilder.java:118)
	at sql.check.sonar/com.zg.sqlcheck.sonar.SonarData.getAlasy(SonarData.java:123)
	at sql.check.sonar/com.zg.sqlcheck.sonar.SonarData.doMain(SonarData.java:237)
	at sql.check.sonar/com.zg.sqlcheck.sonar.SonarData.main(SonarData.java:245)
Caused by: java.lang.NoClassDefFoundError: org/apache/poi/util/POILogFactory
	at org.apache.poi.ooxml.POIXMLDocumentPart.<clinit>(POIXMLDocumentPart.java:56)
	at easyexcel.core@3.1.4/com.alibaba.excel.util.WorkBookUtil.createWorkBook(WorkBookUtil.java:35)
	at easyexcel.core@3.1.4/com.alibaba.excel.context.WriteContextImpl.<init>(WriteContextImpl.java:96)
	at easyexcel.core@3.1.4/com.alibaba.excel.write.ExcelBuilderImpl.<init>(ExcelBuilderImpl.java:36)
	... 7 more
Caused by: java.lang.ClassNotFoundException: org.apache.poi.util.POILogFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 11 more

**Comment by zhuangjiaju** [comment]
参照下这个：https://easyexcel.opensource.alibaba.com/qa/#%E5%85%B3%E4%BA%8E%E7%89%88%E6%9C%AC%E9%80%89%E6%8B%A9
