### ISSUE TITLE
java.lang.StackOverflowError	at com.alibaba.excel.converters.ConverterKeyBuild$ConverterKey.hashCode(ConverterKeyBuild.java:47) ~[easyexcel-3.0.5.jar:?]	

### ISSUE THREAD

**Issue by Nisus-Liu** [alibaba/easyexcel#2904]
**建议先去看文档**
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
**异常代码**
```java
 EasyExcel.write(outputStream, DoneTaskDownloadVo.class)
                    .autoCloseStream(Boolean.FALSE)
                    .inMemory(true)
                    .sheet("Sheet1")
                    .doWrite(data); //  List<DoneTaskDownloadVo> data
```

Head class DoneTaskDownloadVo
```
...
// tags null没问题, 有元素时不行
// @ExcelProperty("标签") //打开有问题
@ExcelIgnore //忽略就没事
private Set<String> tags = new LinkedHashSet<>();

public void appendTag(String tag) {
    if (tag == null) {
        return;
    }
    if (this.tags == null) {
        this.tags = new LinkedHashSet<>();
    }
    this.tags.add(tag);
}
...
```

tags 虽然字段有默认值, 但实际运行中, 有个地方复制字段 null 值覆盖了它.
添加 tag 时, 调用 `appendTag` , 就是说会重新 new LinkedHashSet .
tags 换成 String 类型就行了.

**异常提示**
```
Caused by: java.lang.StackOverflowError	at com.alibaba.excel.converters.ConverterKeyBuild$ConverterKey.hashCode(ConverterKeyBuild.java:47) ~[easyexcel-3.0.5.jar:?]	
at java.util.Objects.hashCode(Objects.java:98) ~[?:1.8.0_292]	at java.util.HashMap$Node.hashCode(HashMap.java:297) ~[?:1.8.0_292]	
at java.util.AbstractMap.hashCode(AbstractMap.java:530) ~[?:1.8.0_292]	at com.alibaba.excel.metadata.AbstractHolder.hashCode(AbstractHolder.java:21) ~[easyexcel-3.0.5.jar:?]	
at com.alibaba.excel.write.metadata.holder.AbstractWriteHolder.hashCode(AbstractWriteHolder.java:57) ~[easyexcel-3.0.5.jar:?]	
at com.alibaba.excel.write.metadata.holder.WriteWorkbookHolder.hashCode(WriteWorkbookHolder.java:48) ~[easyexcel-3.0.5.jar:?]	
at com.alibaba.excel.write.metadata.holder.WriteSheetHolder.hashCode(WriteSheetHolder.java:27) ~[easyexcel-3.0.5.jar:?]	at java.util.Objects.hashCode(Objects.java:98) ~[?:1.8.0_292]	
at java.util.HashMap$Node.hashCode(HashMap.java:297) ~[?:1.8.0_292]	
at java.util.AbstractMap.hashCode(AbstractMap.java:530) ~[?:1.8.0_292]
```

**建议描述**

**Comment by zhuangjiaju** [comment]
升级到最新版本试试，实际测试  没有问题
```java
public class DemoData {
    @ExcelProperty("字符串标题")
    private String string;
    @ExcelProperty("日期标题")
    private Date date;
    @ExcelProperty("数字标题")
    private Double doubleData;
    /**
     * 忽略这个字段
     */
    @ExcelIgnore
    private String ignore;

     @ExcelProperty("标签") //打开有问题
    private Set<String> tags;
}

```java
  fileName = TestFileUtil.getPath() + "simpleWrite" + System.currentTimeMillis() + ".xlsx";
        // 这里 需要指定写用哪个class去写
        try (ExcelWriter excelWriter = EasyExcel.write(fileName, DemoData.class).build()) {
            WriteSheet writeSheet = EasyExcel.writerSheet("模板").build();
            excelWriter.write(data(), writeSheet);
        }
```

**Comment by zhuangjiaju** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue.
