### ISSUE TITLE
一定概率出现 IndexOutOfBoundsException 

### ISSUE THREAD

**Issue by zhouchengfei** [alibaba/easyexcel#2988]
线上有一定概率出现这个报错,单独跑是正常的
测试原文件我放oss上,可以下载: https://cmdy-cdn.oss-cn-hangzhou.aliyuncs.com/xls/doAnalisysImportXls/23e3660a00c64e3c8b72289e2879ad2a.xls
# 触发Bug的代码
2023-02-17 12:11:54.230[ http-nio-8080-exec-2 ] [1626434234711277568] - [ DEBUG ] [ c.a.e.analysis.v03.handlers.FormulaRecordHandler : 45 ] : Get formula value error.
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:657)
        at java.util.ArrayList.get(ArrayList.java:433)
        at org.apache.poi.hssf.model.LinkTable.getNameRecord(LinkTable.java:321)
        at org.apache.poi.hssf.model.InternalWorkbook.getNameRecord(InternalWorkbook.java:1591)
        at org.apache.poi.hssf.usermodel.HSSFEvaluationWorkbook.getNameText(HSSFEvaluationWorkbook.java:215)
        at org.apache.poi.ss.formula.ptg.NamePtg.toFormulaString(NamePtg.java:76)
        at org.apache.poi.ss.formula.FormulaRenderer.toFormulaString(FormulaRenderer.java:91)
        at org.apache.poi.hssf.model.HSSFFormulaParser.toFormulaString(HSSFFormulaParser.java:90)
        at com.alibaba.excel.analysis.v03.handlers.FormulaRecordHandler.processRecord(FormulaRecordHandler.java:42)
        at com.alibaba.excel.analysis.v03.XlsSaxAnalyser.processRecord(XlsSaxAnalyser.java:157)
        at org.apache.poi.hssf.eventusermodel.MissingRecordAwareHSSFListener.processRecord(MissingRecordAwareHSSFListener.java:201)
        at org.apache.poi.hssf.eventusermodel.FormatTrackingHSSFListener.processRecord(FormatTrackingHSSFListener.java:92)
        at org.apache.poi.hssf.eventusermodel.HSSFRequest.processRecord(HSSFRequest.java:106)
        at org.apache.poi.hssf.eventusermodel.HSSFEventFactory.genericProcessEvents(HSSFEventFactory.java:172)
        at org.apache.poi.hssf.eventusermodel.HSSFEventFactory.processEvents(HSSFEventFactory.java:129)
        at org.apache.poi.hssf.eventusermodel.HSSFEventFactory.processWorkbookEvents(HSSFEventFactory.java:80)
        at org.apache.poi.hssf.eventusermodel.HSSFEventFactory.processWorkbookEvents(HSSFEventFactory.java:53)
        at com.alibaba.excel.analysis.v03.XlsSaxAnalyser.execute(XlsSaxAnalyser.java:136)
        at com.alibaba.excel.analysis.ExcelAnalyserImpl.analysis(ExcelAnalyserImpl.java:124)
        at com.alibaba.excel.ExcelReader.read(ExcelReader.java:66)

**Comment by gongxuanzhang** [comment]
发份代码
