### ISSUE TITLE
easyexcel读取会计格式是欧元的时候会抛异常,java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by yeemi22** [alibaba/easyexcel#2997]
easyexcel 读取会计格式的单元格数据，无法解析欧元货币符号： €

![image](https://user-images.githubusercontent.com/104047337/220501486-05c4d811-937d-4204-ba73-41b6eea867f8.png)

报错如下：
java.lang.IllegalArgumentException:Unquotedspecialcharacter';'inpattern"€#,##0.00;€(#,##0.00);€-??"

2023-02-22 09:19:51.534 [main] WARN  org.apache.poi.ss.format.CellFormatter - Invalid format: "_([$€-2]* #,##0.00_);"
java.lang.IllegalArgumentException: Unsupported [] format block '[' in '_([$€-2]* #,##0.00_)' with c2: null
	at org.apache.poi.ss.format.CellFormatPart.formatType(CellFormatPart.java:373)
	at org.apache.poi.ss.format.CellFormatPart.getCellFormatType(CellFormatPart.java:287)
	at org.apache.poi.ss.format.CellFormatPart.<init>(CellFormatPart.java:191)
	at org.apache.poi.ss.format.CellFormat.<init>(CellFormat.java:189)
	at org.apache.poi.ss.format.CellFormat.getInstance(CellFormat.java:163)
	at com.alibaba.excel.metadata.format.DataFormatter.getFormat(DataFormatter.java:212)
	at com.alibaba.excel.metadata.format.DataFormatter.getFormattedNumberString(DataFormatter.java:648)
	at com.alibaba.excel.metadata.format.DataFormatter.format(DataFormatter.java:664)
	at com.alibaba.excel.util.NumberDataFormatterUtils.format(NumberDataFormatterUtils.java:57)
	at com.alibaba.excel.util.NumberDataFormatterUtils.format(NumberDataFormatterUtils.java:35)
	at com.alibaba.excel.converters.string.StringNumberConverter.convertToJavaData(StringNumberConverter.java:54)
	at com.alibaba.excel.converters.string.StringNumberConverter.convertToJavaData(StringNumberConverter.java:23)
	at com.alibaba.excel.converters.Converter.convertToJavaData(Converter.java:57)
	at com.alibaba.excel.util.ConverterUtils.doConvertToJavaObject(ConverterUtils.java:153)
	at com.alibaba.excel.util.ConverterUtils.convertToJavaObject(ConverterUtils.java:100)
	at com.alibaba.excel.read.listener.ModelBuildEventListener.buildUserModel(ModelBuildEventListener.java:103)
	at com.alibaba.excel.read.listener.ModelBuildEventListener.invoke(ModelBuildEventListener.java:41)
	at com.alibaba.excel.read.listener.ModelBuildEventListener.invoke(ModelBuildEventListener.java:26)
	at com.alibaba.excel.read.processor.DefaultAnalysisEventProcessor.dealData(DefaultAnalysisEventProcessor.java:99)
	at com.alibaba.excel.read.processor.DefaultAnalysisEventProcessor.endRow(DefaultAnalysisEventProcessor.java:46)
	at com.alibaba.excel.analysis.v07.handlers.RowTagHandler.endElement(RowTagHandler.java:66)
	at com.alibaba.excel.analysis.v07.handlers.sax.XlsxRowHandler.endElement(XlsxRowHandler.java:91)

**Comment by gaoguozhen** [comment]
你好，请提供一下代码全部代码

**Comment by gaoguozhen** [comment]
或者提供一下excel 文档

**Comment by gongxuanzhang** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue
