### ISSUE TITLE
java.io.IOException: (startline 4) EOF reached before encapsulated token finished

### ISSUE THREAD

**Issue by ttangyang** [alibaba/easyexcel#3075]
java.lang.IllegalStateException: IOException reading next record: java.io.IOException: (startline 4) EOF reached before encapsulated token finished
	at org.apache.commons.csv.CSVParser$CSVRecordIterator.getNextRecord(CSVParser.java:145)
	at org.apache.commons.csv.CSVParser$CSVRecordIterator.hasNext(CSVParser.java:155)
	at com.alibaba.excel.analysis.csv.CsvExcelReadExecutor.execute(CsvExcelReadExecutor.java:73)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.analysis(ExcelAnalyserImpl.java:124)
	at com.alibaba.excel.ExcelReader.read(ExcelReader.java:63)
	at com.alibaba.excel.ExcelReader.read(ExcelReader.java:53)
	at com.alibaba.excel.read.builder.ExcelReaderSheetBuilder.doRead(ExcelReaderSheetBuilder.java:65)

**Comment by gongxuanzhang** [comment]
你想问什么

**Comment by ttangyang** [comment]
这个bug有办法解决吗？就是读取csv文件的时候，有行数数据有问题，缺少双引号。数据如："	2023-03-21 00:00:00","	2-share","	127.18","	SJZ-TTF-share","	18","	1  最后这个1这里少了双引号，数据解析不出来了，怎么能让它跳过这行继续执行

**Comment by gongxuanzhang** [comment]
你csv格式不对解析失败 把csv整理好再解析啊 这不是bug
异常处理在 readlistener的onException方法中解决

**Comment by gongxuanzhang** [comment]
csv解析是用apache的csvParser解析的  报错了貌似没什么办法  要改源码

**Comment by ttangyang** [comment]
好的，谢谢
