### ISSUE TITLE
org.apache.poi.hssf.record.RecordInputStream$LeftoverDataException: Initialisation of record 0x31(FontRecord) left 4 bytes remaining still to be read.

### ISSUE THREAD

**Issue by Lincoln-Bruce** [alibaba/easyexcel#3198]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 触发场景描述
  在另一个系统中导出的excel，需要在这边进行导入，但是可能excel本身存在问题，导致读取excel的时候报错，如果手动保存过之后，是可以正常读取数据的。
# 触发Bug的代码
```java
   `public static void main(String[] args) {
        String filePath = "F:\\1号.xls";

        try(FileInputStream fileInputStream = new FileInputStream(filePath)) {
            EasyExcel.read(fileInputStream, EvalData.class,
                            new PageReadListener<EvalData>(dataList-> {
                                System.out.println("读取到一条数据："+dataList.get(0));
                                System.out.println("读取到一条数据："+dataList.get(5));
                            }))
                    .headRowNumber(0)
                    .sheet()
                    .doRead();
        } catch (IOException e) {
            e.printStackTrace();
        }

    }`
```
# 提示的异常或者没有达到的效果
`Exception in thread "main" org.apache.poi.hssf.record.RecordInputStream$LeftoverDataException: Initialisation of record 0x31(FontRecord) left 4 bytes remaining still to be read.
	at org.apache.poi.hssf.record.RecordInputStream.hasNextRecord(RecordInputStream.java:188)
	at org.apache.poi.hssf.record.RecordFactoryInputStream.nextRecord(RecordFactoryInputStream.java:235)
	at org.apache.poi.hssf.eventusermodel.HSSFEventFactory.genericProcessEvents(HSSFEventFactory.java:168)
	at org.apache.poi.hssf.eventusermodel.HSSFEventFactory.processEvents(HSSFEventFactory.java:129)
	at org.apache.poi.hssf.eventusermodel.HSSFEventFactory.processWorkbookEvents(HSSFEventFactory.java:80)
	at org.apache.poi.hssf.eventusermodel.HSSFEventFactory.processWorkbookEvents(HSSFEventFactory.java:53)
	at com.alibaba.excel.analysis.v03.XlsSaxAnalyser.execute(XlsSaxAnalyser.java:136)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.analysis(ExcelAnalyserImpl.java:124)
	at com.alibaba.excel.ExcelReader.read(ExcelReader.java:66)
	at com.alibaba.excel.ExcelReader.read(ExcelReader.java:56)
	at com.alibaba.excel.read.builder.ExcelReaderSheetBuilder.doRead(ExcelReaderSheetBuilder.java:65)
	at com.jpc.excelimport.InputStreamExcelReader2.main(InputStreamExcelReader2.java:27)`

**Comment by gongxuanzhang** [comment]
手动保存可能wps会帮你调整，你需要让导出的人给你解决

**Comment by xiaOoOxia** [comment]
请教下，这个问题有在新版本解决吗？
