### ISSUE TITLE
400w+数据分sheet导出，报错 Can not close IO

### ISSUE THREAD

**Issue by dalongmyself** [alibaba/easyexcel#3222]
请教给问题：
使用easyExcel导出400W+的数据，每行4列。分多sheet，每个sheet100w数据。在最后执行excelWriter.finish()报错,错误信息如下：
com.alibaba.excel.exception.ExcelGenerateException: Can not close IO.
        at com.alibaba.excel.context.WriteContextImpl.finish(WriteContextImpl.java:420)
        at com.alibaba.excel.write.ExcelBuilderImpl.finish(ExcelBuilderImpl.java:99)
        at com.alibaba.excel.ExcelWriter.finish(ExcelWriter.java:143).      Caused by: java.io.IOException: This archive contains unclosed entries.
        at org.apache.commons.compress.archivers.zip.ZipArchiveOutputStream.finish(ZipArchiveOutputStream.java:467)
        at org.apache.poi.xssf.streaming.SXSSFWorkbook.injectData(SXSSFWorkbook.java:419)
在验证过程中：
1:使用100w数据，每个sheet50w，是可以正常导出的。
2:使用200w数据，每个sheet50w，每行1列，是可以导出的。

**Comment by gongxuanzhang** [comment]
https://github.com/alibaba/easyexcel/issues/2291
看看这个是不是你的问题

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
