### ISSUE TITLE
com.alibaba.excel.exception.ExcelGenerateException: java.lang.InternalError: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by Diviner-Q** [alibaba/easyexcel#3273]
JDK11
easyexcel版本3.1.3和3.3.2都试过 
导出Excel本地没有问题，Linux上就报错
com.alibaba.excel.exception.ExcelGenerateException: java.lang.InternalError: java.lang.reflect.InvocationTargetException
 at com.alibaba.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl.java:65)
 at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:73)
 at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:50)
 at com.alibaba.excel.write.builder.ExcelWriterSheetBuilder.doWrite(ExcelWriterSheetBuilder.java:62)

 at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
 at org.springframework.aop.framework.CglibAopProxy.invokeMethod(CglibAopProxy.java:386)
 at org.springframework.aop.framework.CglibAopProxy.access$000(CglibAopProxy.java:85)
 at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:704)

 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
 at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
 at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
 at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
 at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
 at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
 at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
 at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
 at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
 at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
 at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
 at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
 at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
 at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
 at com.jundragon.common.filtter.LogFilter.doFilterInternal(LogFilter.java:93)
 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
 at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
 at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
 at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
 at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
 at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
 at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
 at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
 at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
 at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
 at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
 at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
 at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
 at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
 at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
 at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
 at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
 at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
 at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
 at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
 at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
 at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
 at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
 at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.InternalError: java.lang.reflect.InvocationTargetException
 at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:86)
 at java.base/java.security.AccessController.doPrivileged(Native Method)
 at java.desktop/sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
 at java.desktop/java.awt.Font.getFont2D(Font.java:497)
 at java.desktop/java.awt.Font.canDisplayUpTo(Font.java:2250)
 at java.desktop/java.awt.font.TextLayout.singleFont(TextLayout.java:469)
 at java.desktop/java.awt.font.TextLayout.<init>(TextLayout.java:530)
 at org.apache.poi.ss.util.SheetUtil.getDefaultCharWidth(SheetUtil.java:273)
 at org.apache.poi.xssf.streaming.AutoSizeColumnTracker.<init>(AutoSizeColumnTracker.java:117)
 at org.apache.poi.xssf.streaming.SXSSFSheet.<init>(SXSSFSheet.java:82)
 at org.apache.poi.xssf.streaming.SXSSFWorkbook.createAndRegisterSXSSFSheet(SXSSFWorkbook.java:684)
 at org.apache.poi.xssf.streaming.SXSSFWorkbook.createSheet(SXSSFWorkbook.java:705)
 at org.apache.poi.xssf.streaming.SXSSFWorkbook.createSheet(SXSSFWorkbook.java:88)
 at com.alibaba.excel.util.WorkBookUtil.createSheet(WorkBookUtil.java:86)
 at com.alibaba.excel.context.WriteContextImpl.createSheet(WriteContextImpl.java:223)
 at com.alibaba.excel.context.WriteContextImpl.initSheet(WriteContextImpl.java:203)
 at com.alibaba.excel.context.WriteContextImpl.currentSheet(WriteContextImpl.java:135)
 at com.alibaba.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl.java:54)
 ... 69 more
Caused by: java.lang.reflect.InvocationTargetException
 at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
 at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
 at java.desktop/sun.font.FontManagerFactory$1.run(FontManagerFactory.java:84)
 ... 86 more
Caused by: java.lang.NullPointerException
 at java.desktop/sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1262)
 at java.desktop/sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:225)
 at java.desktop/sun.awt.FontConfiguration.init(FontConfiguration.java:107)
 at java.desktop/sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:719)
 at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:379)
 at java.base/java.security.AccessController.doPrivileged(Native Method)
 at java.desktop/sun.font.SunFontManager.<init>(SunFontManager.java:324)
 at java.desktop/sun.awt.FcFontManager.<init>(FcFontManager.java:35)
 at java.desktop/sun.awt.X11FontManager.<init>(X11FontManager.java:56)
 ... 91 more

**Comment by gongxuanzhang** [comment]
检查linux环境问题

**Comment by lurunze** [comment]
> 

能说具体一点吗

**Comment by lurunze** [comment]
> 检查linux环境问题

能说具体一点吗

**Comment by Diviner-Q** [comment]
> > 检查linux环境问题
> 
> 能说具体一点吗


我的情况是发现是在docker.file里面没有把字体文件加入到容器中，后面加进去就好了
![image](https://github.com/alibaba/easyexcel/assets/60611451/727a408b-683d-4b7d-842b-3292c7059aa9)

**Comment by softsheng** [comment]
If you have to put it simply, your Linux server does not have fonts, you need to add fonts.

> > 检查linux环境问题
> 
> 能说具体一点吗

If you have to put it simply, your Linux server does not have fonts, you need to add fonts.
