### ISSUE TITLE
XLS文件无法识别--Convert excel format exception.You can try specifying the 'excelType' yourself

### ISSUE THREAD

**Issue by lkee6760** [alibaba/easyexcel#3296]
### 问题描述
解析excel 文件时报错, 提示无法识别文件类型。该文件使用WPS能正常打开及编辑。
初步怀疑是文件格式比较特殊, 尝试是用CSV格式解析, 能识别出部分信息。

### 解析代码
```
String path = "111.XLS";
EasyExcel.read(path, DemoData.class, new PageReadListener<DemoData>(dataList -> {
    for (DemoData demoData : dataList) {
        log.info("读取到一条数据{}", JSON.toJSONString(demoData));
    }
})).sheet().doRead();
```
### 报错内容
```
com.alibaba.excel.exception.ExcelCommonException: Convert excel format exception.You can try specifying the 'excelType' yourself

	at com.alibaba.excel.support.ExcelTypeEnum.recognitionExcelType(ExcelTypeEnum.java:104)
	at com.alibaba.excel.support.ExcelTypeEnum.valueOf(ExcelTypeEnum.java:77)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.choiceExcelExecutor(ExcelAnalyserImpl.java:66)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.<init>(ExcelAnalyserImpl.java:55)
	at com.alibaba.excel.ExcelReader.<init>(ExcelReader.java:30)
	at com.alibaba.excel.read.builder.ExcelReaderBuilder.build(ExcelReaderBuilder.java:214)
	at com.alibaba.excel.read.builder.ExcelReaderBuilder.sheet(ExcelReaderBuilder.java:251)
	at com.alibaba.excel.read.builder.ExcelReaderBuilder.sheet(ExcelReaderBuilder.java:239)
	at com.xueqiu.bigdata.common.utils.Utils.func10(Utils.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
```

### 文件链接
https://pan.baidu.com/s/1bUPrY2LVgLQ-9di6RpKaFw?pwd=vs83 提取码: vs83

**Comment by gongxuanzhang** [comment]
我使用 EasyExcel.read(fileName).sheet().doReadSync() 可以正常读取文件,但是内容乱码
你可以通过 EasyExcel.read(fileName).excelType(xxx) 手动指定读取类型
如果你文件有问题那没办法 需要从"如何把文件变成合法"的考虑解决问题

**Comment by lkee6760** [comment]
> 我使用 EasyExcel.read(fileName).sheet().doReadSync() 可以正常读取文件,但是内容乱码 你可以通过 EasyExcel.read(fileName).excelType(xxx) 手动指定读取类型 如果你文件有问题那没办法 需要从"如何把文件变成合法"的考虑解决问题

非常感谢您的回复。
我已经试图过找文件的源头，确定生成excel的方法，但是没有结果。
您是否知道文件的准确类型呢?

**Comment by lkee6760** [comment]
> 我使用 EasyExcel.read(fileName).sheet().doReadSync() 可以正常读取文件,但是内容乱码 你可以通过 EasyExcel.read(fileName).excelType(xxx) 手动指定读取类型 如果你文件有问题那没办法 需要从"如何把文件变成合法"的考虑解决问题

非常感谢您的回复。
我已经试图过找文件的源头，确定生成excel的方法，但是没有结果。
您是否知道文件的准确类型呢?

**Comment by gongxuanzhang** [comment]
我不知道呀，这怎么知道..
