### ISSUE TITLE
4.1.2版本的POI解析加密excel有时会抛出Name is too long异常

### ISSUE THREAD

**Issue by yanpin1994** [alibaba/easyexcel#3329]
# 触发Bug的代码
        List<XXX> exportList = EasyExcel.read(new BufferedInputStream(file.getInputStream())).password("123456").head(XXX.class).sheet().doReadSync();

# 提示的异常
org.apache.poi.util.RecordFormatException: Unable to construct record instance
	at org.apache.poi.hssf.record.RecordFactory$ReflectionConstructorRecordCreator.create(RecordFactory.java:94) ~[poi-4.1.2.jar:4.1.2]
	at org.apache.poi.hssf.record.RecordFactory.createSingleRecord(RecordFactory.java:339) ~[poi-4.1.2.jar:4.1.2]
	at org.apache.poi.hssf.record.RecordFactoryInputStream.readNextRecord(RecordFactoryInputStream.java:289) ~[poi-4.1.2.jar:4.1.2]
	at org.apache.poi.hssf.record.RecordFactoryInputStream.nextRecord(RecordFactoryInputStream.java:255) ~[poi-4.1.2.jar:4.1.2]
	at org.apache.poi.hssf.eventusermodel.HSSFEventFactory.genericProcessEvents(HSSFEventFactory.java:168) ~[poi-4.1.2.jar:4.1.2]
	at org.apache.poi.hssf.eventusermodel.HSSFEventFactory.processEvents(HSSFEventFactory.java:129) ~[poi-4.1.2.jar:4.1.2]
	at org.apache.poi.hssf.eventusermodel.HSSFEventFactory.processWorkbookEvents(HSSFEventFactory.java:80) ~[poi-4.1.2.jar:4.1.2]
	at org.apache.poi.hssf.eventusermodel.HSSFEventFactory.processWorkbookEvents(HSSFEventFactory.java:53) ~[poi-4.1.2.jar:4.1.2]
	at com.alibaba.excel.analysis.v03.XlsSaxAnalyser.execute(XlsSaxAnalyser.java:136) ~[easyexcel-core-3.1.0.jar:na]
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.analysis(ExcelAnalyserImpl.java:124) ~[easyexcel-core-3.1.0.jar:na]
	at com.alibaba.excel.ExcelReader.read(ExcelReader.java:63) ~[easyexcel-core-3.1.0.jar:na]
	at com.alibaba.excel.ExcelReader.read(ExcelReader.java:53) ~[easyexcel-core-3.1.0.jar:na]
	at com.alibaba.excel.read.builder.ExcelReaderSheetBuilder.doReadSync(ExcelReaderSheetBuilder.java:80) ~[easyexcel-core-3.1.0.jar:na]
	...
Caused by: java.lang.IllegalArgumentException: Name is too long: O�Ht d�@����ssJ��
��f���r�墔C�:r6����-NQ�
��@�ߜ��[���}oiw�����E�j�s�*Al���zW_��к;E��ٱ�c
	at org.apache.poi.hssf.record.WriteAccessRecord.setUsername(WriteAccessRecord.java:107) ~[poi-4.1.2.jar:4.1.2]
	at org.apache.poi.hssf.record.WriteAccessRecord.<init>(WriteAccessRecord.java:75) ~[poi-4.1.2.jar:4.1.2]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[na:na]
	at org.apache.poi.hssf.record.RecordFactory$ReflectionConstructorRecordCreator.create(RecordFactory.java:84) ~[poi-4.1.2.jar:4.1.2]
	... 143 common frames omitted

#异常分析:
     该异常是我在使用easyexcel根据模板生成加密excel文件并解析该文件时发生的，生成的有一些excel文件会无法解析并抛出上述异常。
     原因是POI 4.1.2解析加密excel会随机生成username（WriteAccessRecord.102），username名称超过112个字符则会抛出上述异常
     该问题我通过单独引入POI 5.2.3已经解决（这个版本解析加密excel时不会生成username）

**Comment by gongxuanzhang** [comment]
目前easyexcel没有引用最高版本的poi
如果需要使用到poi的高级功能需要像你这种方式自行替换。
从报错上看可能是因为编码问题导致的username过长。
以后easyexcel的引用poi版本更新 会解决。
感谢提交
