### ISSUE TITLE
java.lang.IllegalAccessError-->superclass access check failed

### ISSUE THREAD

**Issue by hyz19910303** [alibaba/easyexcel#3397]
# 异常代码
```java
 public static void main(String[] args) {
        ArrayList<Entity> data = new ArrayList<>();
        Entity entity = new Entity();
        entity.setCje(122455F);
        data.add(entity);
        ExcelWriter writer = EasyExcel.write(new File("E:\\data\\a.xlsx")).head(Entity.class).build();
        writer.write(data, EasyExcel.writerSheet().build());
        writer.finish();
    }
  
# module  信息
      module-info.java
      open module nativetest{
      
          requires jdk.incubator.concurrent;
          requires junit;
          requires jdk17Synax;
          requires jdk.incubator.vector;
          requires com.fasterxml.jackson.databind;
          requires easyexcel.core;
          requires poi;
          requires jdk.httpserver;
          exports org.jdk.feature;
          exports org.jdk.feature.sealed;
          exports org.demo ;
      }


```
# 异常提示
 Exception in thread "main" com.alibaba.excel.support.cglib.core.CodeGenerationException: java.lang.IllegalAccessError-->superclass access check failed: class org.demo.Entity$$BeanMapByEasyExcelCGLIB$$4e871fcd (in module nativetest) cannot access class com.alibaba.excel.support.cglib.beans.BeanMap (in unnamed module @0x35aea049) because module nativetest does not read unnamed module @0x35aea049
	at com.alibaba.excel.support.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:511)
	at com.alibaba.excel.support.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:363)
	at com.alibaba.excel.support.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:110)
	at com.alibaba.excel.support.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:108)
	at com.alibaba.excel.support.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:317)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at com.alibaba.excel.support.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
	at com.alibaba.excel.support.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
	at com.alibaba.excel.support.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:134)
	at com.alibaba.excel.support.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:319)
	at com.alibaba.excel.support.cglib.beans.BeanMap$Generator.create(BeanMap.java:140)
	at easyexcel.core@3.3.2/com.alibaba.excel.util.BeanMapUtils.create(BeanMapUtils.java:29)
	at easyexcel.core@3.3.2/com.alibaba.excel.write.executor.ExcelWriteAddExecutor.addJavaObjectToExcel(ExcelWriteAddExecutor.java:142)
	at easyexcel.core@3.3.2/com.alibaba.excel.write.executor.ExcelWriteAddExecutor.addOneRowOfDataToExcel(ExcelWriteAddExecutor.java:81)
	at easyexcel.core@3.3.2/com.alibaba.excel.write.executor.ExcelWriteAddExecutor.add(ExcelWriteAddExecutor.java:58)
	at easyexcel.core@3.3.2/com.alibaba.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl.java:59)
	at easyexcel.core@3.3.2/com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:73)
	at easyexcel.core@3.3.2/com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:50)
	at nativetest/org.demo.MuduleInfoTest.main(MuduleInfoTest.java:17)
# 问题描述
 使用maven ，openjdk20。在写入excel 时候，出现异常。Easyxcel 为3.3.2.
如果module-info.java 同时requires easyexcel.core 和easyexcel.support .编译会过不去。
只requires easyexcel.core 。则会出现以上情况。
查询了相关issues.除了手动合并包，没有其他办法嘛？还是希望Easyexcel  能官方支持下。

**Comment by OneFAnn** [comment]
JDK17,Easyxcel 3.3.2
我也遇到了类似的问题
`module BillParser {
    requires javafx.controls;
    requires javafx.fxml;
    requires easyexcel.core;
    
    opens com.gzf.bill to javafx.fxml;
    opens com.gzf.bill.dto;
    
    exports com.gzf.bill;
}`
异常信息
Caused by: java.lang.IllegalAccessError: superclass access check failed: class com.gzf.bill.dto.AliPayTradeDto$$BeanMapByEasyExcelCGLIB$$1a79f748 (in module BillParser) cannot access class com.alibaba.excel.support.cglib.beans.BeanMap (in unnamed module @0x3eedc43c) because module BillParser does not read unnamed module @0x3eedc43c

**Comment by OneFAnn** [comment]
这个问题是因为core和support都存在com.alibaba.excel.support包，然后导致 easyexcel.core和easyexcel.support不能同时requires吗？

**Comment by gongxuanzhang** [comment]
你好，我们发现此Issue已经超过三个月没有活动了，为了更好的帮助您解决问题，我们将在7天后关闭此Issue，如果您仍然有问题，请在7天内回复此Issue，谢谢！如果您已经解决或者不需要帮助，请忽略此消息。
