### ISSUE TITLE
1.1.2版本FileMagic.valueOf(inputStream);报错NoClassDefFoundError

### ISSUE THREAD

**Issue by CQHui** [alibaba/easyexcel#341]

**Comment by CQHui** [comment]
java1.7版本使用时报错
使用如下：
`EasyExcelFactory.read(inputStream, new Sheet(1, 1, Model.class));`
异常信息：

> java.lang.NoClassDefFoundError: org/apache/poi/poifs/filesystem/FileMagic
	at com.alibaba.excel.support.ExcelTypeEnum.valueOf(ExcelTypeEnum.java:34)
	at com.alibaba.excel.ExcelReader.<init>(ExcelReader.java:94)
	at com.alibaba.excel.EasyExcelFactory.read(EasyExcelFactory.java:30)

**Comment by CQHui** [comment]
找到原因了，是因为和自己项目中依赖的common包里的apache-poi包冲突，把自身的exclude掉解决
