### ISSUE TITLE
com.alibaba.excel.exception.ExcelGenerateException: java.lang.NoSuchFieldError: Factory

### ISSUE THREAD

**Issue by wxyn** [alibaba/easyexcel#3432]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 触发场景描述
项目中已经引入了poi-ooxml版本为5.2.3
```
<dependency>
    <groupId>org.apache.poi</groupId>
    <artifactId>poi-ooxml</artifactId>
    <version>5.2.3</version>
</dependency>
```
# 触发Bug的代码
```java
try (ExcelWriter excelWriter = EasyExcelFactory.write(response.getOutputStream(), DataInfoVo.class).autoCloseStream(Boolean.FALSE).build()){
}
```
# 提示的异常或者没有达到的效果
```
com.alibaba.excel.exception.ExcelGenerateException: java.lang.NoSuchFieldError: Factory
        at com.alibaba.excel.write.ExcelBuilderImpl.<init>(ExcelBuilderImpl.java:42) ~[easyexcel-core-3.2.1.jar:?]
        at com.alibaba.excel.ExcelWriter.<init>(ExcelWriter.java:39) ~[easyexcel-core-3.2.1.jar:?]
        at com.alibaba.excel.write.builder.ExcelWriterBuilder.build(ExcelWriterBuilder.java:124) ~[easyexcel-core-3.2.1.jar:?]
       ...
 Caused by: java.lang.NoSuchFieldError: Factory
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.onWorkbookCreate(XSSFWorkbook.java:476) ~[poi-ooxml-5.2.3.jar:5.2.3]
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:233) ~[poi-ooxml-5.2.3.jar:5.2.3]
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:227) ~[poi-ooxml-5.2.3.jar:5.2.3]
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:215) ~[poi-ooxml-5.2.3.jar:5.2.3]
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.<init>(SXSSFWorkbook.java:264) ~[poi-ooxml-5.2.3.jar:5.2.3]
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.<init>(SXSSFWorkbook.java:234) ~[poi-ooxml-5.2.3.jar:5.2.3]
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.<init>(SXSSFWorkbook.java:209) ~[poi-ooxml-5.2.3.jar:5.2.3]
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.<init>(SXSSFWorkbook.java:184) ~[poi-ooxml-5.2.3.jar:5.2.3]
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.<init>(SXSSFWorkbook.java:145) ~[poi-ooxml-5.2.3.jar:5.2.3]
	at com.alibaba.excel.util.WorkBookUtil.createWorkBook(WorkBookUtil.java:48) ~[easyexcel-core-3.2.1.jar:na]
	at com.alibaba.excel.context.WriteContextImpl.<init>(WriteContextImpl.java:96) ~[easyexcel-core-3.2.1.jar:na]
	at com.alibaba.excel.write.ExcelBuilderImpl.<init>(ExcelBuilderImpl.java:36) ~[easyexcel-core-3.2.1.jar:na]
	... 56 common frames omitted
```

**Comment by youlingdada** [comment]
easyexcel 3.3.2所依赖的poi版本是4.1.2，5.x版本会造成依赖冲突，建议poi降低版本到4.1.2

**Comment by youlingdada** [comment]
easyexcel 3.3.2所依赖的poi版本是4.1.2，5.x版本会造成依赖冲突，建议poi降低版本到4.1.2

**Comment by wxyn** [comment]
如果有 ooxml-schemas 和 poi-ooxml-schemas 这 2 个 jar，会与5.x 版本 poi 不兼容，具有同名类导致加载到不适配的类，移除这 2 个 jar 就可以

**Comment by DimpleBoy** [comment]
楼上的言论是正确的，在poi5.2.X的版本中，已经去除了poi-ooxml-schemas的依赖，作了代码合并，如果依赖5.2.X的poi，请手动排除所有的ooxml-schemas 和 poi-ooxml-schemas 这 2 个 jar
