### ISSUE TITLE
读取一个大小为 9kb 的 xlsx 文件；Metaspace  OOM 了

### ISSUE THREAD

**Issue by wxiaohui** [alibaba/easyexcel#3446]
[ERROR][2023-09-02T12:40:41.144+0800][org.springframework.aop.interceptor.SimpleAsyncUncaughtExceptionHandler] _undef||traceid=z188bef60b6d7668hdskfZKWykmZOQa0||spanid=000162306689145a||cspanid=||_msg=Unexpected error occurred invoking async method 'public void biz.impl.syncut.ParseExcelEventHandler.onApplicationEvent(com.biz.impl.syncut.ParseExcelEvent)'.||exception=com.alibaba.excel.exception.ExcelAnalysisException: java.lang.OutOfMemoryError: Metaspace
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.<init>(ExcelAnalyserImpl.java:61)
	at com.alibaba.excel.ExcelReader.<init>(ExcelReader.java:30)
	at com.alibaba.excel.read.builder.ExcelReaderBuilder.build(ExcelReaderBuilder.java:214)
	at com.alibaba.excel.read.builder.ExcelReaderBuilder.doReadAll(ExcelReaderBuilder.java:218)

想咨询下这里异常的场景有哪些啊

**Comment by youlingdada** [comment]
请提供一下可供复现的代码和对应的文件
