### ISSUE TITLE
错误：invalid char between encapsulated token and delimiter

### ISSUE THREAD

**Issue by kimilai888** [alibaba/easyexcel#3450]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 建议描述
excel内容中如果带有双引号， 比如“1235 ，会报错invalid char between encapsulated token and delimiter

**Comment by hebian1994** [comment]
是的，我也遇到了，比如我有个CSV，里面的数据是1,"2,3   如图
![image](https://github.com/alibaba/easyexcel/assets/35398326/6fc1cfd6-db3e-4a00-a01b-8b2cddf9e347)
然后我创建一个读取类
public class TestVO {
    @ExcelProperty("name")
    private String name ;
    @ExcelProperty("age")
    private String age ;
    @ExcelProperty("phone")
    private String phone ;
}
读取的时候就会报错了，错误信息如下
Caused by: java.io.IOException: (startline 2) EOF reached before encapsulated token finished
	at org.apache.commons.csv.Lexer.parseEncapsulatedToken(Lexer.java:288)
	at org.apache.commons.csv.Lexer.nextToken(Lexer.java:158)
	at org.apache.commons.csv.CSVParser.nextRecord(CSVParser.java:674)
	at org.apache.commons.csv.CSVParser$CSVRecordIterator.getNextRecord(CSVParser.java:142)
这种格式的CSV如果是直接从DB导出生成的CSV，会经常遇到逗号后面紧跟着双引号的情况。
感觉这应该是个ISSUE吧

**Comment by fish-liu** [comment]
有人解决这个问题了吗？
