### ISSUE TITLE
EOF reached before encapsulated token finished

### ISSUE THREAD

**Issue by hebian1994** [alibaba/easyexcel#3552]
你好，我在使用easyexcel 3.1.1来读取CSV文件。
CSV，里面的数据是1,"2,3 如图
![image](https://github.com/alibaba/easyexcel/assets/35398326/c18334e6-b3cf-480d-bcd8-3ccae3a02688)

然后我创建一个读取类
public class TestVO {
@ExcelProperty("name")
private String name ;
@ExcelProperty("age")
private String age ;
@ExcelProperty("phone")
private String phone ;
}

读取的时候就会报错了，错误信息如下
Caused by: java.io.IOException: (startline 2) EOF reached before encapsulated token finished
at org.apache.commons.csv.Lexer.parseEncapsulatedToken(Lexer.java:288)
at org.apache.commons.csv.Lexer.nextToken(Lexer.java:158)
at org.apache.commons.csv.CSVParser.nextRecord(CSVParser.java:674)
at org.apache.commons.csv.CSVParser$CSVRecordIterator.getNextRecord(CSVParser.java:142)

这种格式的CSV如果是直接从DB导出生成的CSV，会经常遇到逗号后面紧跟着双引号的情况。
感觉这应该是个ISSUE吧，谢谢

**Comment by qianqi0614** [comment]
我也遇到同样的问题了，请问有解决方案吗？
