### ISSUE TITLE
csv文件解析到特殊字符直接异常终止，有没有办法跳过这一行或者解析这行

### ISSUE THREAD

**Issue by nfpss** [alibaba/easyexcel#3568]
"java.lang.IllegalStateException: IOException reading next record: java.io.IOException: (line 9) invalid char between encapsulated token and delimiter
at org.apache.commons.csv.CSVParserCSVRecordIterator.getNextRecord(CSVParser.java:145)atorg.apache.commons.csv.CSVParser
CSVRecordIterator.hasNext(CSVParser.java:155)
at com.alibaba.excel.analysis.csv.CsvExcelReadExecutor.execute(CsvExcelReadExecutor.java:73)
at com.alibaba.excel.analysis.ExcelAnalyserImpl.analysis(ExcelAnalyserImpl.java:124)
at com.alibaba.excel.ExcelReader.read(ExcelReader.java:66)
at com.alibaba.excel.ExcelReader.read(ExcelReader.java:56)
at com.alibaba.excel.read.builder.ExcelReaderSheetBuilder.doRead(ExcelReaderSheetBuilder.java:65)
at com.xhqb.soc.datacollect.util.ExcelUtils.read(ExcelUtils.java:31)

数据如下：
"Operation Triangulation" 卡巴斯基被黑 - 续, [https://mp.weixin.qq.com/s/ESi0bWF_jQ4nS1-CwjxlEQ](https://gitee.com/link?target=https%3A%2F%2Fmp.weixin.qq.com%2Fs%2FESi0bWF_jQ4nS1-CwjxlEQ), 2023-11-19

**Comment by unnoc** [comment]
读取的时候就报错了
