### ISSUE TITLE
DateUtils.switchDateFormat 限制了部分可解析的日期字符串

### ISSUE THREAD

**Issue by yichengxian** [alibaba/easyexcel#3661]
# 版本
 3.1.1
# 描述
  hi, 该问题不知是作者有意为之还是为何，最终发现是switchDateFormat限制导致不能执行，是一个比较简单的问题
以下是异常信息: 
java.lang.IllegalArgumentException: can not find date format for：2024-01-20 8:30
	at com.alibaba.excel.util.DateUtils.switchDateFormat(DateUtils.java:133)
	at com.alibaba.excel.util.DateUtils.parseDate(DateUtils.java:102)

# 触发Bug的代码
```java
   // 从源码得出原方法是可以解析
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm");
        dateFormat.parse("2024-01-20 8:30");
   // 封装的工具不行
        DateUtils.parseDate("2024-01-20 8:30");
```

**Comment by yichengxian** [comment]
从代码上看，这是一个非常难判断的问题
