### ISSUE TITLE
xls导入失败

### ISSUE THREAD

**Issue by masterchengsheng** [alibaba/easyexcel#368]
Exception in thread "main" com.alibaba.excel.exception.ExcelAnalysisException: File type error，io must be available markSupported,you can do like this <code> new BufferedInputStream(new FileInputStream(\"/xxxx\"))</code> "
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.getSaxAnalyser(ExcelAnalyserImpl.java:58)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.getSheets(ExcelAnalyserImpl.java:80)
	at com.alibaba.excel.ExcelReader.getSheets(ExcelReader.java:133)
	at com.aimsphm.server.filemanager.file.impl.FileImportServiceImpl.readExcel03(FileImportServiceImpl.java:80)
	at com.aimsphm.server.filemanager.file.impl.FileImportServiceImpl.main(FileImportServiceImpl.java:56)
Caused by: com.alibaba.excel.exception.ExcelAnalysisException: Xls must be available markSupported,you can do like this <code> new BufferedInputStream(new FileInputStream("/xxxx"))</code> 
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.getSaxAnalyser(ExcelAnalyserImpl.java:50)
一直提示上面的一次信息

**Comment by Qwenjin** [comment]
用BufferedInputStream包一层？

**Comment by dear-Alice-moon** [comment]
请问一下，你是如何使用EasyExcel这款开源工具的？我都不知道该如何使用！

**Comment by masterchengsheng** [comment]
public List<BomInfoExcelDTO> readExcel03(InputStream inputStream) {
        ExcelListener excelListener = new ExcelListener();
        ExcelReader excelReader = new ExcelReader(inputStream, ExcelTypeEnum.XLS, null, excelListener);
        List<Sheet> sheets = excelReader.getSheets();
        for (Sheet sheet : sheets) {
            if (sheet.getSheetNo() == 1) {
                excelReader.read(sheet);
            } else {
                sheet.setHeadLineMun(2);
                sheet.setClazz(BomInfoDTO.class);
                excelReader.read(sheet);
            }
        }
        return excelListener.getData();
    }
这样写可以  如果把构造方法改成 跟07 一样的EasyExcelFactory.readBySax(inputStream, new Sheet(2, 1, BomInfoDTO.class), excelListener); 就GG啦 就直接抛上面那个异常

**Comment by masterchengsheng** [comment]
<dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>easyexcel</artifactId>
            <version>1.1.2-beta5</version>
        </dependency>

**Comment by fish7790714** [comment]
看异常是打开流有问题 直接上异常代码

**Comment by seaguil** [comment]
> Exception in thread "main" com.alibaba.excel.exception.ExcelAnalysisException: File type error，io must be available markSupported,you can do like this ` new BufferedInputStream(new FileInputStream("/xxxx"))` "
> at com.alibaba.excel.analysis.ExcelAnalyserImpl.getSaxAnalyser(ExcelAnalyserImpl.java:58)
> at com.alibaba.excel.analysis.ExcelAnalyserImpl.getSheets(ExcelAnalyserImpl.java:80)
> at com.alibaba.excel.ExcelReader.getSheets(ExcelReader.java:133)
> at com.aimsphm.server.filemanager.file.impl.FileImportServiceImpl.readExcel03(FileImportServiceImpl.java:80)
> at com.aimsphm.server.filemanager.file.impl.FileImportServiceImpl.main(FileImportServiceImpl.java:56)
> Caused by: com.alibaba.excel.exception.ExcelAnalysisException: Xls must be available markSupported,you can do like this ` new BufferedInputStream(new FileInputStream("/xxxx"))`
> at com.alibaba.excel.analysis.ExcelAnalyserImpl.getSaxAnalyser(ExcelAnalyserImpl.java:50)
> 一直提示上面的一次信息

2019-05-30 16:57:09.368  WARN 22892 --- [l-1 housekeeper] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=58s710ms615?s623ns).
com.alibaba.excel.exception.ExcelAnalysisException: File type error，io must be available markSupported,you can do like this <code> new BufferedInputStream(new FileInputStream(\"/xxxx/xxx/77.xlsx\"))</code> "
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.getSaxAnalyser(ExcelAnalyserImpl.java:59)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.analysis(ExcelAnalyserImpl.java:73)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.analysis(ExcelAnalyserImpl.java:68)
	at com.alibaba.excel.ExcelReader.read(ExcelReader.java:112)
	at com.alibaba.excel.EasyExcelFactory.readBySax(EasyExcelFactory.java:50)
我也是报了和你差不多的错误，但是我上次xlsx是没有问题的，就是xls又问题的？
请问你是如何解决的？

**Comment by masterchengsheng** [comment]
没有呢

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: seaguil <notifications@github.com>
发送时间: Thursday, May 30, 2019 5:11:05 PM
收件人: alibaba/easyexcel
抄送: 程胜; Author
主题: Re: [alibaba/easyexcel] xls导入失败 (#368)


Exception in thread "main" com.alibaba.excel.exception.ExcelAnalysisException: File type error，io must be available markSupported,you can do like this new BufferedInputStream(new FileInputStream("/xxxx")) "
at com.alibaba.excel.analysis.ExcelAnalyserImpl.getSaxAnalyser(ExcelAnalyserImpl.java:58)
at com.alibaba.excel.analysis.ExcelAnalyserImpl.getSheets(ExcelAnalyserImpl.java:80)
at com.alibaba.excel.ExcelReader.getSheets(ExcelReader.java:133)
at com.aimsphm.server.filemanager.file.impl.FileImportServiceImpl.readExcel03(FileImportServiceImpl.java:80)
at com.aimsphm.server.filemanager.file.impl.FileImportServiceImpl.main(FileImportServiceImpl.java:56)
Caused by: com.alibaba.excel.exception.ExcelAnalysisException: Xls must be available markSupported,you can do like this new BufferedInputStream(new FileInputStream("/xxxx"))
at com.alibaba.excel.analysis.ExcelAnalyserImpl.getSaxAnalyser(ExcelAnalyserImpl.java:50)
一直提示上面的一次信息

2019-05-30 16:57:09.368 WARN 22892 --- [l-1 housekeeper] com.zaxxer.hikari.pool.HikariPool : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=58s710ms615?s623ns).
com.alibaba.excel.exception.ExcelAnalysisException: File type error，io must be available markSupported,you can do like this new BufferedInputStream(new FileInputStream("/xxxx/xxx/77.xlsx")) "
at com.alibaba.excel.analysis.ExcelAnalyserImpl.getSaxAnalyser(ExcelAnalyserImpl.java:59)
at com.alibaba.excel.analysis.ExcelAnalyserImpl.analysis(ExcelAnalyserImpl.java:73)
at com.alibaba.excel.analysis.ExcelAnalyserImpl.analysis(ExcelAnalyserImpl.java:68)
at com.alibaba.excel.ExcelReader.read(ExcelReader.java:112)
at com.alibaba.excel.EasyExcelFactory.readBySax(EasyExcelFactory.java:50)
我也是报了和你差不多的错误，但是我上次xlsx是没有问题的，就是xls又问题的？
请问你是如何解决的？

―

**Comment by seaguil** [comment]
> 没有呢 发送自 Windows 10 版邮件<[https://go.microsoft.com/fwlink/?LinkId=550986>应用](https://go.microsoft.com/fwlink/?LinkId=550986>%E5%BA%94%E7%94%A8)
> […](#)
> ________________________________ 发件人: seaguil <notifications@github.com> 发送时间: Thursday, May 30, 2019 5:11:05 PM 收件人: alibaba/easyexcel 抄送: 程胜; Author 主题: Re: [alibaba/easyexcel] xls导入失败 (#368) Exception in thread "main" com.alibaba.excel.exception.ExcelAnalysisException: File type error，io must be available markSupported,you can do like this new BufferedInputStream(new FileInputStream("/xxxx")) " at com.alibaba.excel.analysis.ExcelAnalyserImpl.getSaxAnalyser(ExcelAnalyserImpl.java:58) at com.alibaba.excel.analysis.ExcelAnalyserImpl.getSheets(ExcelAnalyserImpl.java:80) at com.alibaba.excel.ExcelReader.getSheets(ExcelReader.java:133) at com.aimsphm.server.filemanager.file.impl.FileImportServiceImpl.readExcel03(FileImportServiceImpl.java:80) at com.aimsphm.server.filemanager.file.impl.FileImportServiceImpl.main(FileImportServiceImpl.java:56) Caused by: com.alibaba.excel.exception.ExcelAnalysisException: Xls must be available markSupported,you can do like this new BufferedInputStream(new FileInputStream("/xxxx")) at com.alibaba.excel.analysis.ExcelAnalyserImpl.getSaxAnalyser(ExcelAnalyserImpl.java:50) 一直提示上面的一次信息 2019-05-30 16:57:09.368 WARN 22892 --- [l-1 housekeeper] com.zaxxer.hikari.pool.HikariPool : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=58s710ms615?s623ns). com.alibaba.excel.exception.ExcelAnalysisException: File type error，io must be available markSupported,you can do like this new BufferedInputStream(new FileInputStream("/xxxx/xxx/77.xlsx")) " at com.alibaba.excel.analysis.ExcelAnalyserImpl.getSaxAnalyser(ExcelAnalyserImpl.java:59) at com.alibaba.excel.analysis.ExcelAnalyserImpl.analysis(ExcelAnalyserImpl.java:73) at com.alibaba.excel.analysis.ExcelAnalyserImpl.analysis(ExcelAnalyserImpl.java:68) at com.alibaba.excel.ExcelReader.read(ExcelReader.java:112) at com.alibaba.excel.EasyExcelFactory.readBySax(EasyExcelFactory.java:50) 我也是报了和你差不多的错误，但是我上次xlsx是没有问题的，就是xls又问题的？ 请问你是如何解决的？ ― You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Falibaba%2Feasyexcel%2Fissues%2F368%3Femail_source%3Dnotifications%26email_token%3DAETIOBI77LN73ERO6GDZOJ3PX6K2TA5CNFSM4HNKEZA2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWRZ5VI%23issuecomment-497262293&data=02%7C01%7C%7Cf13be470c361408f5f6c08d6e4dec01e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636948042684451351&sdata=NWgSyo43wRIdIxmqMylhY9cY3wRgHPUaE5olEIQMlDk%3D&reserved=0>, or mute the thread<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAETIOBLUL5AZIOPYA6Q2EXLPX6K2TANCNFSM4HNKEZAQ&data=02%7C01%7C%7Cf13be470c361408f5f6c08d6e4dec01e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636948042684461362&sdata=UsZKCDNff%2BxiIgoUISvSAzg88t%2BwfdEXJ5MjpVlxqL4%3D&reserved=0>.

那你不打算解决了嘛？难受啊？我最新的问题置顶了，你顺便可以看看下楼主如何帮忙的

**Comment by moondrink** [comment]
试试这样InputStream inputStream = new BufferedInputStream(new FileInputStream(filepath));

**Comment by seaguil** [comment]
> 试试这样InputStream inputStream = new BufferedInputStream（new FileInputStream（filepath））;

已经解决了。

**Comment by yijiemanong** [comment]
@seaguil   怎么解决的  大佬?

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。
