### ISSUE TITLE
  java.lang.RuntimeException: java.io.IOException: Permission denied

### ISSUE THREAD

**Issue by xqgmzzmzmn** [alibaba/easyexcel#369]
at org.apache.poi.xssf.streaming.SXSSFWorkbook.createAndRegisterSXSSFSheet(SXSSFWorkbook.java:662)
at org.apache.poi.xssf.streaming.SXSSFWorkbook.createSheet(SXSSFWorkbook.java:679)
at org.apache.poi.xssf.streaming.SXSSFWorkbook.createSheet(SXSSFWorkbook.java:90)
at com.alibaba.excel.util.WorkBookUtil.createSheet(WorkBookUtil.java:51)
at com.alibaba.excel.context.WriteContext.currentSheet(WriteContext.java:118)
at com.alibaba.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl.java:71)
at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:91)

这是报的异常信息，在集群环境中，用POI导出excel数据没问题，用excel就报了这个异常，查过源码，easyexcel创建临时(获取临时)文件的方式和POI是一样的，可能不同的是POI是读完再写，easyexcel是边读边写，请问出现这个问题的原因是什么呢？

**Comment by xqgmzzmzmn** [comment]
问题找到了，因为我们用的是集群，主服务器有该临时目录的权限，但是从服务器没有配相应的权限，索引会出现这个问题，其实就是这个文件夹/tmp/poifiles
