### ISSUE TITLE
生成Excel报错ang.NoClassDefFoundError: Failed resolution of: Ljavax/xml/stream/XMLStreamReader

### ISSUE THREAD

**Issue by zengli199447** [alibaba/easyexcel#3690]
触发代码：EasyExcel.write(filePath, xx.class).sheet("sheet").doWrite(list);

com.alibaba.excel.exception.ExcelGenerateException: java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/xml/stream/XMLStreamReader;
                                                                                                    	at com.alibaba.excel.write.ExcelBuilderImpl.<init>(ExcelBuilderImpl.java:42)
                                                                                                    	at com.alibaba.excel.ExcelWriter.<init>(ExcelWriter.java:36)
                                                                                                    	at com.alibaba.excel.write.builder.ExcelWriterBuilder.build(ExcelWriterBuilder.java:114)
                                                                                                    	at com.alibaba.excel.write.builder.ExcelWriterBuilder.sheet(ExcelWriterBuilder.java:130)
                                                                                                    	at com.alibaba.excel.write.builder.ExcelWriterBuilder.sheet(ExcelWriterBuilder.java:126)
                                                                                                    	at com.hbmcc.zl.ui.module.publicList.type.capacity.CapacityAutoOptimizationLifecycle.lambda$outPutCsv$4$CapacityAutoOptimizationLifecycle(CapacityAutoOptimizationLifecycle.java:442)
                                                                                                    	at com.hbmcc.zl.ui.module.publicList.type.capacity.-$$Lambda$CapacityAutoOptimizationLifecycle$SnZ_BLivfeKM_NzHdXP8ZmNo7N4.run(Unknown Source:4)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/xml/stream/XMLStreamReader;
                                                                                                    	at org.apache.xmlbeans.XmlBeans.buildStreamToNodeMethod(XmlBeans.java:251)
                                                                                                    	at org.apache.xmlbeans.XmlBeans.<clinit>(XmlBeans.java:138)
                                                                                                    	at org.apache.xmlbeans.XmlBeans.typeLoaderForClassLoader(XmlBeans.java:719)
                                                                                                    	at org.openxmlformats.schemas.spreadsheetml.x2006.main.CTWorkbook$Factory.getTypeLoader(Unknown Source:23)
                                                                                                    	at org.openxmlformats.schemas.spreadsheetml.x2006.main.CTWorkbook$Factory.newInstance(Unknown Source:0)
                                                                                                    	at org.apache.poi.xssf.usermodel.XSSFWorkbook.onWorkbookCreate(XSSFWorkbook.java:462)
                                                                                                    	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:265)
                                                                                                    	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:259)
                                                                                                    	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:247)
                                                                                                    	at org.apache.poi.xssf.streaming.SXSSFWorkbook.<init>(SXSSFWorkbook.java:241)
                                                                                                    	at org.apache.poi.xssf.streaming.SXSSFWorkbook.<init>(SXSSFWorkbook.java:211)
                                                                                                    	at org.apache.poi.xssf.streaming.SXSSFWorkbook.<init>(SXSSFWorkbook.java:186)
                                                                                                    	at org.apache.poi.xssf.streaming.SXSSFWorkbook.<init>(SXSSFWorkbook.java:161)
                                                                                                    	at org.apache.poi.xssf.streaming.SXSSFWorkbook.<init>(SXSSFWorkbook.java:122)
                                                                                                    	at com.alibaba.excel.util.WorkBookUtil.createWorkBook(WorkBookUtil.java:48)
                                                                                                    	at com.alibaba.excel.context.WriteContextImpl.<init>(WriteContextImpl.java:96)
                                                                                                    	at com.alibaba.excel.write.ExcelBuilderImpl.<init>(ExcelBuilderImpl.java:36)
                                                                                                    	at com.alibaba.excel.ExcelWriter.<init>(ExcelWriter.java:36) 
                                                                                                    	at com.alibaba.excel.write.builder.ExcelWriterBuilder.build(ExcelWriterBuilder.java:114) 
                                                                                                    	at com.alibaba.excel.write.builder.ExcelWriterBuilder.sheet(ExcelWriterBuilder.java:130) 
                                                                                                    	at com.alibaba.excel.write.builder.ExcelWriterBuilder.sheet(ExcelWriterBuilder.java:126) 
                                                                                                    	at com.hbmcc.zl.ui.module.publicList.type.capacity.CapacityAutoOptimizationLifecycle.lambda$outPutCsv$4$CapacityAutoOptimizationLifecycle(CapacityAutoOptimizationLifecycle.java:442) 
                                                                                                    	at com.hbmcc.zl.ui.module.publicList.type.capacity.-$$Lambda$CapacityAutoOptimizationLifecycle$SnZ_BLivfeKM_NzHdXP8ZmNo7N4.run(Unknown Source:4) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)

**Comment by psxjoy** [comment]
看上去似乎是项目依赖的jar包冲突，目前是否是否解决了呢？ @zengli199447 
如果仍需要协助的话，请提供demo。

**Comment by psxjoy** [comment]
不知道您是否已经解决该问题？我们先暂时关闭这个问题，如果还存在问题请重新Reopen这个issue.
