### ISSUE TITLE
easyexcel 3.0.2 jdk1.8 解析数据报错

### ISSUE THREAD

**Issue by Linn-chen** [alibaba/easyexcel#3691]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 触发场景描述
上传excel 解析报错
# 触发Bug的代码
```java
     read(inputStream, clazz, listener).sheet(sheetNo).headRowNumber(rowNumber).doRead();
```
# 提示的异常或者没有达到的效果
anager.
2024-02-06 13:43:02.175 com.yotta.liangyi.securedb.business.service.MainService:chooseService:28 [http-nio-8087-exec-7] [] ERROR - Excel 处理异常: {}
com.alibaba.excel.exception.ExcelAnalysisException: java.lang.UnsatisfiedLinkError: sun.misc.Unsafe.copySwapMemory0(Ljava/lang/Object;JLjava/lang/Object;JJJ)V
        at com.alibaba.excel.analysis.ExcelAnalyserImpl.<init>(ExcelAnalyserImpl.java:60)
        at com.alibaba.excel.ExcelReader.<init>(ExcelReader.java:30)
        at com.alibaba.excel.read.builder.ExcelReaderBuilder.build(ExcelReaderBuilder.java:193)
        at com.alibaba.excel.read.builder.ExcelReaderBuilder.sheet(ExcelReaderBuilder.java:229)
        at com.alibaba.excel.read.builder.ExcelReaderBuilder.sheet(ExcelReaderBuilder.java:221)
        at com.yotta.liangyi.securedb.utils.EasyExcelUtils.readExcelWithModel(EasyExcelUtils.java:137)
        at com.yotta.liangyi.securedb.business.service.CustomerDataService.parseExcel(CustomerDataService.java:34)
        at com.yotta.liangyi.securedb.business.service.CustomerDataService.handle(CustomerDataService.java:99)
        at com.yotta.liangyi.securedb.business.service.MainService.chooseService(MainService.java:26)
        at com.yotta.liangyi.securedb.business.controller.ExcelHandleController.importCumstomer(ExcelHandleController.java:49)
        at com.yotta.liangyi.securedb.business.controller.ExcelHandleController$$FastClassBySpringCGLIB$$a1983bcf.invoke(<generated>)

**Comment by youlingdada** [comment]
能否贴出完整一点的代码，这样复现不了
