### ISSUE TITLE
使用easyexcle导出时异常ExcelGenerateException: Can not close IO，并且下载到异常zip包，Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.build.AbstractStreamBuilder

### ISSUE THREAD

**Issue by coder-tpc** [alibaba/easyexcel#3744]
# 触发场景描述
easyexcel  3.3.4
使用easyexcel  填充excel时出现Can not close IO

# 触发Bug的代码
```java
            String templateFileName = FileUtils.getPath() + TEM_PATH;
            String fileName = plan.getPlanName() + "-" + df1.format(record.getExecEndTime()) + "巡检报告";
            File file = new File(FileUtils.getPath() + fileName + ".xlsx");
            CustomCellWriteStrategy customCellWriteStrategy = new CustomCellWriteStrategy();
            try (ExcelWriter excelWriter = EasyExcel.write(file).registerWriteHandler(customCellWriteStrategy)
                    .withTemplate(templateFileName).build()) {
                WriteSheet writeSheet = EasyExcel.writerSheet().build();
                FillConfig fillConfig = FillConfig.builder().forceNewRow(Boolean.TRUE).build();
                excelWriter.fill(data, fillConfig, writeSheet);
                Map<String, Object> map = MapUtils.newHashMap();
                map.put("plan_name", plan.getPlanName());
                map.put("finish_date", df.format(record.getExecEndTime()));
                excelWriter.fill(map, writeSheet);
            } catch (Exception e) {
                log.error("巡检报告文件渲染失败:{}", e.getMessage(), e);
                record.setReportFailReason("巡检报告文件渲染失败");
                record.setExecStatus(1);
                upsertRecord(record, false, false);
                plan.setState(1);
                smartToolsInspPlanRepository.upsert(plan);
                if (file != null) {
                    FileUtil.del(file);
                }
                return;
            }
```
# 提示的异常或者没有达到的效果
```
com.alibaba.excel.exception.ExcelGenerateException: Can not close IO.
	at com.alibaba.excel.context.WriteContextImpl.finish(WriteContextImpl.java:420) ~[easyexcel-core-3.3.4.jar:?]
	at com.alibaba.excel.write.ExcelBuilderImpl.finish(ExcelBuilderImpl.java:99) ~[easyexcel-core-3.3.4.jar:?]
	at com.alibaba.excel.ExcelWriter.finish(ExcelWriter.java:143) ~[easyexcel-core-3.3.4.jar:?]
	at com.alibaba.excel.ExcelWriter.close(ExcelWriter.java:158) ~[easyexcel-core-3.3.4.jar:?]
	at com.qax.dayu.sdm.devops.application.service.SmartToolsInspManageService.execReport(SmartToolsInspManageService.java:378) ~[classes/:?]
	at com.qax.dayu.sdm.devops.facade.endpoint.MonitorSmartToolsInspPlanEndpoint.reports(MonitorSmartToolsInspPlanEndpoint.java:90) ~[classes/:?]
	at com.qax.dayu.sdm.devops.facade.endpoint.MonitorSmartToolsInspPlanEndpoint$$FastClassBySpringCGLIB$$8fc2dc8a.invoke(<generated>) ~[classes/:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.33.jar:5.3.33]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:792) ~[spring-aop-5.3.33.jar:5.3.33]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.33.jar:5.3.33]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762) ~[spring-aop-5.3.33.jar:5.3.33]
	at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:123) ~[spring-context-5.3.33.jar:5.3.33]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.33.jar:5.3.33]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:762) ~[spring-aop-5.3.33.jar:5.3.33]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:707) ~[spring-aop-5.3.33.jar:5.3.33]
	at com.qax.dayu.sdm.devops.facade.endpoint.MonitorSmartToolsInspPlanEndpoint$$EnhancerBySpringCGLIB$$59a16efa.reports(<generated>) ~[classes/:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.33.jar:5.3.33]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.33.jar:5.3.33]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.33.jar:5.3.33]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:903) ~[spring-webmvc-5.3.33.jar:5.3.33]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:809) ~[spring-webmvc-5.3.33.jar:5.3.33]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.33.jar:5.3.33]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072) ~[spring-webmvc-5.3.33.jar:5.3.33]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965) ~[spring-webmvc-5.3.33.jar:5.3.33]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.33.jar:5.3.33]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.3.33.jar:5.3.33]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:523) ~[jboss-servlet-api_4.0_spec-2.0.0.Final.jar:2.0.0.Final]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.33.jar:5.3.33]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:590) ~[jboss-servlet-api_4.0_spec-2.0.0.Final.jar:2.0.0.Final]
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74) ~[undertow-servlet-2.2.30.Final.jar:2.2.30.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129) ~[undertow-servlet-2.2.30.Final.jar:2.2.30.Final]
	at com.qax.needle.framework.boot.filter.LogFilter.doFilter(LogFilter.java:66) ~[needle-boot-starter-2.1.23.jar:2.1.23]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67) ~[undertow-servlet-2.2.30.Final.jar:2.2.30.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.2.30.Final.jar:2.2.30.Final]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.33.jar:5.3.33]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.33.jar:5.3.33]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67) ~[undertow-servlet-2.2.30.Final.jar:2.2.30.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.2.30.Final.jar:2.2.30.Final]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.33.jar:5.3.33]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.33.jar:5.3.33]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67) ~[undertow-servlet-2.2.30.Final.jar:2.2.30.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.2.30.Final.jar:2.2.30.Final]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96) ~[spring-boot-actuator-2.7.18.jar:2.7.18]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.33.jar:5.3.33]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67) ~[undertow-servlet-2.2.30.Final.jar:2.2.30.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.2.30.Final.jar:2.2.30.Final]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.33.jar:5.3.33]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.33.jar:5.3.33]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:67) ~[undertow-servlet-2.2.30.Final.jar:2.2.30.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131) ~[undertow-servlet-2.2.30.Final.jar:2.2.30.Final]
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84) ~[undertow-servlet-2.2.30.Final.jar:2.2.30.Final]
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) ~[undertow-servlet-2.2.30.Final.jar:2.2.30.Final]
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68) ~[undertow-servlet-2.2.30.Final.jar:2.2.30.Final]
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) ~[undertow-servlet-2.2.30.Final.jar:2.2.30.Final]
	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68) ~[undertow-servlet-2.2.30.Final.jar:2.2.30.Final]
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117) ~[undertow-servlet-2.2.30.Final.jar:2.2.30.Final]
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) ~[undertow-servlet-2.2.30.Final.jar:2.2.30.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.2.30.Final.jar:2.2.30.Final]
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) ~[undertow-core-2.2.30.Final.jar:2.2.30.Final]
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) ~[undertow-servlet-2.2.30.Final.jar:2.2.30.Final]
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60) ~[undertow-core-2.2.30.Final.jar:2.2.30.Final]
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) ~[undertow-servlet-2.2.30.Final.jar:2.2.30.Final]
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) ~[undertow-core-2.2.30.Final.jar:2.2.30.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.2.30.Final.jar:2.2.30.Final]
	at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52) ~[undertow-servlet-2.2.30.Final.jar:2.2.30.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-2.2.30.Final.jar:2.2.30.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:275) ~[undertow-servlet-2.2.30.Final.jar:2.2.30.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79) ~[undertow-servlet-2.2.30.Final.jar:2.2.30.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134) ~[undertow-servlet-2.2.30.Final.jar:2.2.30.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131) ~[undertow-servlet-2.2.30.Final.jar:2.2.30.Final]
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) ~[undertow-servlet-2.2.30.Final.jar:2.2.30.Final]
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) ~[undertow-servlet-2.2.30.Final.jar:2.2.30.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:255) ~[undertow-servlet-2.2.30.Final.jar:2.2.30.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79) ~[undertow-servlet-2.2.30.Final.jar:2.2.30.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100) ~[undertow-servlet-2.2.30.Final.jar:2.2.30.Final]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:393) ~[undertow-core-2.2.30.Final.jar:2.2.30.Final]
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852) ~[undertow-core-2.2.30.Final.jar:2.2.30.Final]
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35) ~[jboss-threads-3.1.0.Final.jar:3.1.0.Final]
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019) ~[jboss-threads-3.1.0.Final.jar:3.1.0.Final]
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558) ~[jboss-threads-3.1.0.Final.jar:3.1.0.Final]
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1423) ~[jboss-threads-3.1.0.Final.jar:3.1.0.Final]
	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1282) ~[xnio-api-3.8.12.Final.jar:3.8.12.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/io/build/AbstractStreamBuilder
	at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[?:?]
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800) ~[?:?]
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698) ~[?:?]
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621) ~[?:?]
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579) ~[?:?]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:859) ~[commons-compress-1.26.1.jar:1.26.1]
	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:931) ~[commons-compress-1.26.1.jar:1.26.1]
	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:819) ~[commons-compress-1.26.1.jar:1.26.1]
	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:795) ~[commons-compress-1.26.1.jar:1.26.1]
	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:715) ~[commons-compress-1.26.1.jar:1.26.1]
	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:702) ~[commons-compress-1.26.1.jar:1.26.1]
	at org.apache.poi.openxml4j.util.ZipSecureFile.<init>(ZipSecureFile.java:122) ~[poi-ooxml-4.1.2.jar:4.1.2]
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.write(SXSSFWorkbook.java:957) ~[poi-ooxml-4.1.2.jar:4.1.2]
	at com.alibaba.excel.context.WriteContextImpl.finish(WriteContextImpl.java:381) ~[easyexcel-core-3.3.4.jar:?]
	... 86 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.build.AbstractStreamBuilder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[?:?]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[?:?]
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800) ~[?:?]
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698) ~[?:?]
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621) ~[?:?]
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579) ~[?:?]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:859) ~[commons-compress-1.26.1.jar:1.26.1]
	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:931) ~[commons-compress-1.26.1.jar:1.26.1]
	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:819) ~[commons-compress-1.26.1.jar:1.26.1]
	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:795) ~[commons-compress-1.26.1.jar:1.26.1]
	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:715) ~[commons-compress-1.26.1.jar:1.26.1]
	at org.apache.commons.compress.archivers.zip.ZipFile.<init>(ZipFile.java:702) ~[commons-compress-1.26.1.jar:1.26.1]
	at org.apache.poi.openxml4j.util.ZipSecureFile.<init>(ZipSecureFile.java:122) ~[poi-ooxml-4.1.2.jar:4.1.2]
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.write(SXSSFWorkbook.java:957) ~[poi-ooxml-4.1.2.jar:4.1.2]
	at com.alibaba.excel.context.WriteContextImpl.finish(WriteContextImpl.java:381) ~[easyexcel-core-3.3.4.jar:?]
	... 86 more

```

**Comment by coder-tpc** [comment]
卡了两天，已解决，easyexcel的引用commons-io版本和直接引用的commons-io依赖有冲突

**Comment by LuuucasChen** [comment]
> 卡了两天，已解决，easyexcel的引用commons-io版本和直接引用的commons-io依赖有冲突

我也有这个问题，请问是如何解决冲突的。我项目commons-io版本是2.1.1

**Comment by huangsht** [comment]
请问具体是咋解决的，改pom包
