### ISSUE TITLE
下载demo报错，readme的demo顺序存在错误

### ISSUE THREAD

**Issue by evanyangg** [alibaba/easyexcel#381]
#### JDK version
```
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
```
#### easyexcel version
```
1.1.2-beta5
```

```
out = response.getOutputStream();
response.setContentType("multipart/form-data");
response.setCharacterEncoding("utf-8");
String fileName = new String(("收款方列表" + new SimpleDateFormat("yyyy-MM-dd").format(new Date()))
                    .getBytes(), "UTF-8");
response.setHeader("Content-disposition", "attachment;filename="+fileName+".xlsx");
## 下面一行报错
ExcelWriter writer = new ExcelWriter(out, ExcelTypeEnum.XLSX, false);
Sheet sheet1 = new Sheet(1, 0);
sheet1.setSheetName("导入格式");
writer.write(payOrderPayeeExcelModelList, sheet1);
writer.finish();
out.flush();
```
error info
```
java.lang.NoClassDefFoundError: org/apache/poi/xssf/streaming/SXSSFWorkbook
	at com.alibaba.excel.util.WorkBookUtil.createWorkBook(WorkBookUtil.java:27) ~[easyexcel-1.1.2-beta5.jar:na]
	at com.alibaba.excel.context.WriteContext.<init>(WriteContext.java:103) ~[easyexcel-1.1.2-beta5.jar:na]
	at com.alibaba.excel.write.ExcelBuilderImpl.<init>(ExcelBuilderImpl.java:40) ~[easyexcel-1.1.2-beta5.jar:na]
	at com.alibaba.excel.ExcelWriter.<init>(ExcelWriter.java:58) ~[easyexcel-1.1.2-beta5.jar:na]
```
我在对应的poi包中确实没有找到对应的方法
![image](https://user-images.githubusercontent.com/22952321/58449752-bcfa8180-813e-11e9-8b98-e04c4432d66b.png)

**Comment by fish7790714** [comment]
easyexcel 基于poi 3.17 将你配置pom.xml的poi 删除 或者改成3.17即可

**Comment by evanyangg** [comment]
抱歉 jar包冲突了。
