### ISSUE TITLE
排除poi 4.x版本引入最新5.2.5版本出现错误：java.lang.NoSuchFieldError: Factory

### ISSUE THREAD

**Issue by phial3** [alibaba/easyexcel#3821]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 触发场景描述
因 poi 4.1.x 版本太低存在高危漏洞提示，更换最新poi版本5.2.5之后，下面简单的导出文件出现错误

<img width="799" alt="image" src="https://github.com/alibaba/easyexcel/assets/27754514/5a578b4f-a80c-442b-b19f-dd1909e55b37">

# 触发Bug的代码
```java
protected String export(Page<T> page, QueryWrapper<T> queryWrapper) {
    final String fileName = exportFileName();
    Page<T> paged = this.page(page, queryWrapper);
    EasyExcel.write(fileName, getEntityClass()).sheet("Sheet1").doWrite(paged.getRecords());
    return fileName;
}
```
# 提示的异常或者没有达到的效果
```text
Caused by: java.lang.NoSuchFieldError: Factory
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.onWorkbookCreate(XSSFWorkbook.java:506)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:233)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:227)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:215)
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.<init>(SXSSFWorkbook.java:267)
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.<init>(SXSSFWorkbook.java:237)
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.<init>(SXSSFWorkbook.java:212)
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.<init>(SXSSFWorkbook.java:187)
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.<init>(SXSSFWorkbook.java:148)
	at com.alibaba.excel.util.WorkBookUtil.createWorkBook(WorkBookUtil.java:48)
	at com.alibaba.excel.context.WriteContextImpl.<init>(WriteContextImpl.java:96)
	at com.alibaba.excel.write.ExcelBuilderImpl.<init>(ExcelBuilderImpl.java:36)
	... 120 common frames omitted
```

**Comment by phial3** [comment]
```xml
 <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>easyexcel</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.poi</groupId>
                    <artifactId>poi</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.poi</groupId>
                    <artifactId>poi-ooxml</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.apache.poi</groupId>
                    <artifactId>poi-ooxml-schemas</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```
排除所有poi依赖使用最新版测试没问题了
