### ISSUE TITLE
使用easyExcel导入报异常：org.apache.poi.openxml4j.exceptions.NotOfficeXmlFileException: No valid entries or contents found, this is not a valid OOXML (Office Open XML) file

### ISSUE THREAD

**Issue by lyj890110** [alibaba/easyexcel#3826]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 触发场景描述
easyexcel导入Excel文件（.xlsx）报错
POM文件：
<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>3.17</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>3.17</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-scratchpad</artifactId>
			<version>4.0.0</version>
		</dependency>

		<dependency>
			<groupId>com.alibaba</groupId>
			<artifactId>easyexcel</artifactId>
			<version>2.2.10</version>
		</dependency>

# 触发Bug的代码
        String fileName = file.getOriginalFilename();
        ExcelTypeEnum excelTypeEnum = null;
        if (fileName.endsWith(".xlsx")) {
            excelTypeEnum = ExcelTypeEnum.XLSX;
        } else if (fileName.endsWith(".xls")) {
            excelTypeEnum = ExcelTypeEnum.XLS;
        }
        if (excelTypeEnum == null) {
            // 文件类型不支持
            return ResultDTO.fail("A0701", "文件类型错误");
        }
        // 解析Sheet1
        List<X113AreaGreenEnergy> x113AreaGreenEnergyList = new ArrayList<>();
        InputStream inputStream1 = file.getInputStream();
        EasyExcel.read(inputStream1, X113AreaGreenEnergy.class, new ExcelListener(list -> {
            x113AreaGreenEnergyList.addAll(list);
        })).excelType(excelTypeEnum).headRowNumber(2).sheet(0).doRead();

调用doRead()时报错，异常信息如下：

# 提示的异常或者没有达到的效果
 org.apache.poi.openxml4j.exceptions.NotOfficeXmlFileException: No valid entries or contents found, this is not a valid OOXML (Office Open XML) file

 	at org.apache.poi.openxml4j.opc.ZipPackage.getPartsImpl(ZipPackage.java:286)

 	at org.apache.poi.openxml4j.opc.OPCPackage.getParts(OPCPackage.java:756)

 	at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:298)

 	at com.alibaba.excel.analysis.v07.XlsxSaxAnalyser.readOpcPackage(XlsxSaxAnalyser.java:154)

 	at com.alibaba.excel.analysis.v07.XlsxSaxAnalyser.<init>(XlsxSaxAnalyser.java:63)

 	at com.alibaba.excel.analysis.ExcelAnalyserImpl.choiceExcelExecutor(ExcelAnalyserImpl.java:99)

 	at com.alibaba.excel.analysis.ExcelAnalyserImpl.<init>(ExcelAnalyserImpl.java:51)

 	at com.alibaba.excel.ExcelReader.<init>(ExcelReader.java:145)

 	at com.alibaba.excel.read.builder.ExcelReaderBuilder.build(ExcelReaderBuilder.java:193)

 	at com.alibaba.excel.read.builder.ExcelReaderBuilder.sheet(ExcelReaderBuilder.java:229)

 	at com.alibaba.excel.read.builder.ExcelReaderBuilder.sheet(ExcelReaderBuilder.java:221)

 	at pro.business.enterpriseCarbonInterfaceService.service.GreenEnergyService.importExcel(GreenEnergyService.java:136)

 	at pro.business.enterpriseCarbonInterfaceService.controller.GreenEnergyController.importExcel(GreenEnergyController.java:74)

 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

 	at java.lang.reflect.Method.invoke(Method.java:498)

 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)

 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)

 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)

 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)

 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)

 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)

 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1061)

 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:961)

 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)

 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)

 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)

 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)

 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)

 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)

 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)

 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

 	at com.github.xiaoymin.knife4j.spring.filter.ProductionSecurityFilter.doFilter(ProductionSecurityFilter.java:53)

 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

 	at com.github.xiaoymin.knife4j.spring.filter.SecurityBasicAuthFilter.doFilter(SecurityBasicAuthFilter.java:90)

 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

 	at pro.business.enterpriseCarbonInterfaceService.utils.CrosFilter.doFilter(CrosFilter.java:26)

 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)

 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)

 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)

 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)

 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)

 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)

 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)

 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)

 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)

 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)

 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)

 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)

 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)

 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)

 	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:764)

 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)

 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)

 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)

 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)

 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)

 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)

 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)

 	at java.lang.Thread.run(Thread.java:750)

**Comment by psxjoy** [comment]
怀疑导入的时候打开了原始文档。建议尝试：
1. 关闭所有文件；
2. 升级到easyexcel 最新的版本。

**Comment by psxjoy** [comment]
It is not a bug, change to the `help wanted` tag. @zhuangjiaju

**Comment by lyj890110** [comment]
不是框架问题，是因为Excel文件加密导致的，解密后就能正常导入了

**Comment by lyj890110** [comment]
问题已解决
