### ISSUE TITLE
4.0.0版本依赖commons-io版本过低导致异常

### ISSUE THREAD

**Issue by oSunnyo** [alibaba/easyexcel#3841]
# 触发场景描述
手写纯净Java环境测试4.0.0的版本，导出Excel时报异常

# 触发Bug的代码
```java
    public static void main(String[] args) {
        final String DEST = "/Users/xxx/Downloads/test.xlsx";

        List<SysLogExport> excelDatas = new ArrayList<>();
        for (int i = 0; i < 10; i++) {
            SysLogExport export = new SysLogExport();
            export.setLevel("ACCESS");
            export.setCategory("INFO");
            export.setUsername("ADMIN");
            export.setTime(LocalDateTime.now());
            export.setMsg("sysLog.getMsg()");
            excelDatas.add(export);
        }
        File file = new File(DEST);
        EasyExcel.write(file, SysLogExport.class)
                .sheet()
                .doWrite(excelDatas);
    }

# 异常信息
Exception in thread "main" com.alibaba.excel.exception.ExcelGenerateException: java.lang.NoSuchMethodError: 'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
	at com.alibaba.excel.write.ExcelBuilderImpl.<init>(ExcelBuilderImpl.java:42)
	at com.alibaba.excel.ExcelWriter.<init>(ExcelWriter.java:39)
	at com.alibaba.excel.write.builder.ExcelWriterBuilder.build(ExcelWriterBuilder.java:133)
	at com.alibaba.excel.write.builder.ExcelWriterBuilder.sheet(ExcelWriterBuilder.java:149)
	at com.alibaba.excel.write.builder.ExcelWriterBuilder.sheet(ExcelWriterBuilder.java:137)

```
# 提示的异常或者没有达到的效果
修改使用commons-io:2.16.1问题可修复

**Comment by psxjoy** [comment]
good issue， @zhuangjiaju will check and fix it.

**Comment by zhuangjiaju** [comment]
是个 bug 麻烦使用 4.0.1

**Comment by LeePui** [comment]
4.0.1也有这个问题：
```
Caused by: java.lang.NoSuchMethodError: 'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
	at org.apache.poi.util.IOUtils.peekFirstNBytes(IOUtils.java:144) ~[poi-5.2.5.jar:5.2.5]
	at com.alibaba.excel.support.ExcelTypeEnum.recognitionExcelType(ExcelTypeEnum.java:98) ~[easyexcel-core-4.0.1.jar:?]
	at com.alibaba.excel.support.ExcelTypeEnum.valueOf(ExcelTypeEnum.java:87) ~[easyexcel-core-4.0.1.jar:?]
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.choiceExcelExecutor(ExcelAnalyserImpl.java:66) ~[easyexcel-core-4.0.1.jar:?]
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.<init>(ExcelAnalyserImpl.java:55) ~[easyexcel-core-4.0.1.jar:?]
	... 85 more
```

**Comment by psxjoy** [comment]
> ```java
> public static void main(String[] args) {
>         final String DEST = "/Users/xxx/Downloads/test.xlsx";
> 
>         List<SysLogExport> excelDatas = new ArrayList<>();
>         for (int i = 0; i < 10; i++) {
>             SysLogExport export = new SysLogExport();
>             export.setLevel("ACCESS");
>             export.setCategory("INFO");
>             export.setUsername("ADMIN");
>             export.setTime(LocalDateTime.now());
>             export.setMsg("sysLog.getMsg()");
>             excelDatas.add(export);
>         }
>         File file = new File(DEST);
>         EasyExcel.write(file, SysLogExport.class)
>                 .sheet()
>                 .doWrite(excelDatas);
>     }
> ```

Hi，刚刚重新跑了一下demo，并没有发现该问题。

**Comment by psxjoy** [comment]
> 4.0.1也有这个问题：
> 
> ```
> Caused by: java.lang.NoSuchMethodError: 'org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream$Builder org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream.builder()'
> 	at org.apache.poi.util.IOUtils.peekFirstNBytes(IOUtils.java:144) ~[poi-5.2.5.jar:5.2.5]
> 	at com.alibaba.excel.support.ExcelTypeEnum.recognitionExcelType(ExcelTypeEnum.java:98) ~[easyexcel-core-4.0.1.jar:?]
> 	at com.alibaba.excel.support.ExcelTypeEnum.valueOf(ExcelTypeEnum.java:87) ~[easyexcel-core-4.0.1.jar:?]
> 	at com.alibaba.excel.analysis.ExcelAnalyserImpl.choiceExcelExecutor(ExcelAnalyserImpl.java:66) ~[easyexcel-core-4.0.1.jar:?]
> 	at com.alibaba.excel.analysis.ExcelAnalyserImpl.<init>(ExcelAnalyserImpl.java:55) ~[easyexcel-core-4.0.1.jar:?]
> 	... 85 more
> ```

Hi，刚刚重新跑了一下demo，并没有发现该问题。

**Comment by genglongsir** [comment]
我这里4.0.2和4.0.3也有这个问题，使用3.3.4就不会

**Comment by ljp190** [comment]
同样遇见了，4.0.3   io版本是2.7  会出现UnsynchronizedByteArrayOutputStream这个异常
想用高版本，就必须把io的版本也升上去
