### ISSUE TITLE
根据原文件作为模板写入数据生成新的文件占用内存很大OOM

### ISSUE THREAD

**Issue by xiongyanokok** [alibaba/easyexcel#3858]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 异常代码
```java
   ExcelWriter excelWriter = EasyExcel.write(outputStream).withTemplate(byteArrayInputStream).build();
```
# 异常提示
java.lang.OutOfMemoryError: Java heap space
Wrapped by: com.alibaba.excel.exception.ExcelGenerateException: java.lang.OutOfMemoryError: Java heap space
	at com.alibaba.excel.write.ExcelBuilderImpl.<init>(ExcelBuilderImpl.java:41)
	at com.alibaba.excel.ExcelWriter.<init>(ExcelWriter.java:47)
	at com.alibaba.excel.write.builder.ExcelWriterBuilder.build(ExcelWriterBuilder.java:130)

"org.apache.poi.xssf.usermodel.XSSFWorkbook", loaded by
"org.springframework.boot.loader.LaunchedURLClassLoader@0xe0000000",
which occupies 702,261,008 (83.36%) bytes.
# 问题描述

**Comment by xiongyanokok** [comment]
现在使用的版本是2.2.7

**Comment by psxjoy** [comment]
建议升级版本至 3.3.4+ 或者分批写入。

**Comment by xiongyanokok** [comment]
由于生成失败内容的excel需要使用原文件的样式, 需要用原文件生成Workbook,  发现Workbook workbook = WorkbookFactory.create(inputStream); 这里占用内存也比较多, 也试过SXSSFWorkbook 方式 各种报错

**Comment by whatalittlebear** [comment]
分批写入也出错，怎么办，我是分批fill，但是easyExcel只是最后再output文件，怎么解决呢
