### ISSUE TITLE
大量数据导入的时候，20w的数据，多线程导入解析多个sheet，报错

### ISSUE THREAD

**Issue by gyj1500146362** [alibaba/easyexcel#3943]
2024-08-21 10:32:37.728  WARN [ool-1-thread-12] o.e.i.p.DefaultLocalPersistenceService   : Could not delete directory for context 4c772ede-dd82-4ba1-8c52-20b8c4b5e413
2024-08-21 10:32:37.728  INFO [ool-1-thread-12] org.ehcache.core.EhcacheManager          : Cache '4c772ede-dd82-4ba1-8c52-20b8c4b5e413' removed from EhcacheManager.
2024-08-21 10:32:37.728  WARN [pool-1-thread-5] org.terracotta.utilities.io.Files        : Persistent IOException renaming "C:\Users\pc\AppData\Local\Temp\53e4dcd2-fc3d-410e-93e8-c5f2a4637211\excache\7e68af69-8a7c-4a18-a15d-4cce58b4ddd3\file\86022aed-d80f-4a82-9cff-38ee7f1003b6_d518a7f275ed48aff2103a4f081c930cf6d033dd" to "C:\Users\pc\AppData\Local\Temp\53e4dcd2-fc3d-410e-93e8-c5f2a4637211\excache\7e68af69-8a7c-4a18-a15d-4cce58b4ddd3\file\del4032942918110800876"; elapsedTime=PT0.9412889S

java.nio.file.AccessDeniedException: C:\Users\pc\AppData\Local\Temp\53e4dcd2-fc3d-410e-93e8-c5f2a4637211\excache\7e68af69-8a7c-4a18-a15d-4cce58b4ddd3\file\86022aed-d80f-4a82-9cff-38ee7f1003b6_d518a7f275ed48aff2103a4f081c930cf6d033dd -> C:\Users\pc\AppData\Local\Temp\53e4dcd2-fc3d-410e-93e8-c5f2a4637211\excache\7e68af69-8a7c-4a18-a15d-4cce58b4ddd3\file\del4032942918110800876
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:301)
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:287)
	at java.nio.file.Files.move(Files.java:1392)
	at org.terracotta.utilities.io.Files.retryingRenamePath(Files.java:1107)
	at org.terracotta.utilities.io.Files.retryingRename(Files.java:1012)
	at org.terracotta.utilities.io.Files.deleteTreeWithRetry(Files.java:928)
	at org.terracotta.utilities.io.Files.deleteTree(Files.java:411)
	at org.ehcache.impl.persistence.FileUtils.tryRecursiveDelete(FileUtils.java:102)
	at org.ehcache.impl.persistence.DefaultLocalPersistenceService.destroy(DefaultLocalPersistenceService.java:205)
	at org.ehcache.impl.persistence.DefaultLocalPersistenceService.destroySafeSpace(DefaultLocalPersistenceService.java:182)
	at org.ehcache.impl.persistence.DefaultDiskResourceService.destroy(DefaultDiskResourceService.java:183)
	at org.ehcache.core.EhcacheManager.closeEhcache(EhcacheManager.java:236)
	at org.ehcache.core.EhcacheManager.removeCache(EhcacheManager.java:214)
	at org.ehcache.core.EhcacheManager.removeCache(EhcacheManager.java:188)
	at com.alibaba.excel.cache.Ehcache.destroy(Ehcache.java:160)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.finish(ExcelAnalyserImpl.java:154)
	at com.alibaba.excel.ExcelReader.finish(ExcelReader.java:102)
	at com.alibaba.excel.read.builder.ExcelReaderSheetBuilder.doRead(ExcelReaderSheetBuilder.java:66)
	at com.banksteel.poi.controller.EasyExcelReadApiImpl.lambda$readFileThread$1(EasyExcelReadApiImpl.java:69)
	at com.banksteel.poi.controller.EasyExcelReadApiImpl$$Lambda$1145/1895213232.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)

**Comment by psxjoy** [comment]
Hi, we currently do not support multithreaded write operations.

目前版本暂时不支持多线程写入。

**Comment by gyj1500146362** [comment]
我看只会报WARN日志，数据时解析到了的

**Comment by psxjoy** [comment]
We don’t recommend concurrent read/write operations, as they are **very likely** to cause issues.

不建议并发读写，它很有可能导致读写错误。
