### ISSUE TITLE
Didn't find class "java.awt.font.FontRenderContext"

### ISSUE THREAD

**Issue by D-zy** [alibaba/easyexcel#3996]
# 建议先去看文档
[快速开始](https://easyexcel.opensource.alibaba.com/docs/current/) 、[常见问题](https://easyexcel.opensource.alibaba.com/qa/)
# 异常代码
```java
   这里写你的代码
```
# 异常提示
大家尽量把问题一次性描述清楚，然后贴上全部异常，这样方便把问题一次性解决掉。
至少大家要符合一个原则就是，能让其他人复现出这个问题，如果无法复现，肯定无法解决。
# 问题描述

**Comment by psxjoy** [comment]
The error suggests a missing font. Please refer to [this link](https://easyexcel.opensource.alibaba.com/qa/#%E6%88%91%E5%9C%A8%E6%9C%AC%E5%9C%B0%E5%8F%AF%E4%BB%A5%E5%8F%91%E5%B8%83%E5%88%B0%E7%BA%BF%E4%B8%8A%E7%8E%AF%E5%A2%83%E6%80%8E%E4%B9%88%E4%B8%8D%E5%8F%AF%E4%BB%A5%E4%BA%86) for troubleshooting steps.

从报错信息上判断是缺少了字体。可以按照[这个地址](https://easyexcel.opensource.alibaba.com/qa/#%E6%88%91%E5%9C%A8%E6%9C%AC%E5%9C%B0%E5%8F%AF%E4%BB%A5%E5%8F%91%E5%B8%83%E5%88%B0%E7%BA%BF%E4%B8%8A%E7%8E%AF%E5%A2%83%E6%80%8E%E4%B9%88%E4%B8%8D%E5%8F%AF%E4%BB%A5%E4%BA%86)进行排查处理

**Comment by psxjoy** [comment]
This issue has been completed, I will close this issue.

**Comment by jiangjm424** [comment]
> This issue has been completed, I will close this issue.

这个问题是如何解决的了，我在安卓上使用虚拟机生成excel时也会提示这个问题
```kotlin

class ExcelFileWriter(context: Context) {
    private val name: String = "excel_" + System.currentTimeMillis() + ".xlsx"
    private val path = context.getExternalFilesDir(null).toString() + "/" + name
    suspend fun doWrite() {
        Log.i("jiang","write file:$path")
        EasyExcel.write(path).sheet("asdfaf").doWrite(data())
    }

    private fun data(): List<Table1> {
        val list = mutableListOf<Table1>()
        repeat(1000) {
            list += Table1(
                name = "name:$it",
                data = Date(),
                ss = System.currentTimeMillis()
            )
        }
        return list
    }

}
```

所报问题：
```
2024-10-18 15:41:55.311 10561-10561 jiang                   com.example.exceltest                I  write file:/storage/emulated/0/Android/data/com.example.exceltest/files/excel_1729237315295.xlsx
2024-10-18 15:41:55.318 10561-10561 System.err              com.example.exceltest                W  SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2024-10-18 15:41:55.318 10561-10561 System.err              com.example.exceltest                W  SLF4J: Defaulting to no-operation (NOP) logger implementation
2024-10-18 15:41:55.318 10561-10561 System.err              com.example.exceltest                W  SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2024-10-18 15:41:55.347 10561-10561 ample.exceltest         com.example.exceltest                W  Accessing hidden method Ljava/lang/invoke/LambdaMetafactory;->metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; (blocked, linking, denied)
2024-10-18 15:41:55.347 10561-10561 ample.exceltest         com.example.exceltest                W  Accessing hidden method Ljava/lang/invoke/LambdaMetafactory;->metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; (blocked, linking, denied)
2024-10-18 15:41:55.360 10561-10561 ample.exceltest         com.example.exceltest                W  Accessing hidden method Ljava/lang/invoke/LambdaMetafactory;->metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; (blocked, linking, denied)
2024-10-18 15:41:55.362 10561-10561 ample.exceltest         com.example.exceltest                W  Accessing hidden method Ljava/lang/invoke/LambdaMetafactory;->metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; (blocked, linking, denied)
2024-10-18 15:41:55.368 10561-10561 System.err              com.example.exceltest                W  ERROR StatusLogger Unable to load services for service class org.apache.logging.log4j.spi.Provider
2024-10-18 15:41:55.368 10561-10561 System.err              com.example.exceltest                W   java.lang.NoSuchMethodError: No static method metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; in class Ljava/lang/invoke/LambdaMetafactory; or its super classes (declaration of 'java.lang.invoke.LambdaMetafactory' appears in /apex/com.android.art/javalib/core-oj.jar)
2024-10-18 15:41:55.368 10561-10561 System.err              com.example.exceltest                W  	at org.apache.logging.log4j.util.ServiceLoaderUtil.callServiceLoader(ServiceLoaderUtil.java:110)
2024-10-18 15:41:55.368 10561-10561 System.err              com.example.exceltest                W  	at org.apache.logging.log4j.util.ServiceLoaderUtil$ServiceLoaderSpliterator.<init>(ServiceLoaderUtil.java:146)
2024-10-18 15:41:55.368 10561-10561 System.err              com.example.exceltest                W  	at org.apache.logging.log4j.util.ServiceLoaderUtil.loadClassloaderServices(ServiceLoaderUtil.java:101)
2024-10-18 15:41:55.369 10561-10561 System.err              com.example.exceltest                W  	at org.apache.logging.log4j.util.ServiceLoaderUtil.loadServices(ServiceLoaderUtil.java:83)
2024-10-18 15:41:55.369 10561-10561 System.err              com.example.exceltest                W  	at org.apache.logging.log4j.util.ServiceLoaderUtil.loadServices(ServiceLoaderUtil.java:77)
2024-10-18 15:41:55.369 10561-10561 System.err              com.example.exceltest                W  	at org.apache.logging.log4j.util.ProviderUtil.<init>(ProviderUtil.java:70)
2024-10-18 15:41:55.369 10561-10561 System.err              com.example.exceltest                W  	at org.apache.logging.log4j.util.ProviderUtil.lazyInit(ProviderUtil.java:148)
2024-10-18 15:41:55.369 10561-10561 System.err              com.example.exceltest                W  	at org.apache.logging.log4j.util.ProviderUtil.hasProviders(ProviderUtil.java:132)
2024-10-18 15:41:55.369 10561-10561 System.err              com.example.exceltest                W  	at org.apache.logging.log4j.LogManager.<clinit>(LogManager.java:90)
2024-10-18 15:41:55.369 10561-10561 System.err              com.example.exceltest                W  	at org.apache.poi.xssf.streaming.SXSSFWorkbook.<clinit>(SXSSFWorkbook.java:113)
2024-10-18 15:41:55.369 10561-10561 System.err              com.example.exceltest                W  	at com.alibaba.excel.util.WorkBookUtil.createWorkBook(WorkBookUtil.java:48)
2024-10-18 15:41:55.369 10561-10561 System.err              com.example.exceltest                W  	at com.alibaba.excel.context.WriteContextImpl.<init>(WriteContextImpl.java:96)
2024-10-18 15:41:55.369 10561-10561 System.err              com.example.exceltest                W  	at com.alibaba.excel.write.ExcelBuilderImpl.<init>(ExcelBuilderImpl.java:36)
2024-10-18 15:41:55.369 10561-10561 System.err              com.example.exceltest                W  	at com.alibaba.excel.ExcelWriter.<init>(ExcelWriter.java:39)
2024-10-18 15:41:55.369 10561-10561 System.err              com.example.exceltest                W  	at com.alibaba.excel.write.builder.ExcelWriterBuilder.build(ExcelWriterBuilder.java:133)
2024-10-18 15:41:55.369 10561-10561 System.err              com.example.exceltest                W  	at com.alibaba.excel.write.builder.ExcelWriterBuilder.sheet(ExcelWriterBuilder.java:149)
2024-10-18 15:41:55.369 10561-10561 System.err              com.example.exceltest                W  	at com.alibaba.excel.write.builder.ExcelWriterBuilder.sheet(ExcelWriterBuilder.java:145)
2024-10-18 15:41:55.369 10561-10561 System.err              com.example.exceltest                W  	at com.example.exceltest.excel.ExcelFileWriter.doWrite(ExcelFileWriter.kt:17)
2024-10-18 15:41:55.369 10561-10561 System.err              com.example.exceltest                W  	at com.example.exceltest.ui.home.HomeFragment$onCreateView$2$1$1.invokeSuspend(HomeFragment.kt:41)
2024-10-18 15:41:55.369 10561-10561 System.err              com.example.exceltest                W  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-10-18 15:41:55.369 10561-10561 System.err              com.example.exceltest                W  	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
2024-10-18 15:41:55.369 10561-10561 System.err              com.example.exceltest                W  	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
2024-10-18 15:41:55.369 10561-10561 System.err              com.example.exceltest                W  	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
2024-10-18 15:41:55.369 10561-10561 System.err              com.example.exceltest                W  	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
2024-10-18 15:41:55.370 10561-10561 System.err              com.example.exceltest                W  	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
2024-10-18 15:41:55.370 10561-10561 System.err              com.example.exceltest                W  	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
2024-10-18 15:41:55.370 10561-10561 System.err              com.example.exceltest                W  	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
2024-10-18 15:41:55.370 10561-10561 System.err              com.example.exceltest                W  	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
2024-10-18 15:41:55.370 10561-10561 System.err              com.example.exceltest                W  	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
2024-10-18 15:41:55.370 10561-10561 System.err              com.example.exceltest                W  	at com.example.exceltest.ui.home.HomeFragment.onCreateView$lambda$1(HomeFragment.kt:40)
2024-10-18 15:41:55.370 10561-10561 System.err              com.example.exceltest                W  	at com.example.exceltest.ui.home.HomeFragment.$r8$lambda$hhnyguiE5IWBBZRazxnwEa277tU(Unknown Source:0)
2024-10-18 15:41:55.370 10561-10561 System.err              com.example.exceltest                W  	at com.example.exceltest.ui.home.HomeFragment$$ExternalSyntheticLambda0.onClick(D8$$SyntheticClass:0)
2024-10-18 15:41:55.370 10561-10561 System.err              com.example.exceltest                W  	at android.view.View.performClick(View.java:7659)
2024-10-18 15:41:55.370 10561-10561 System.err              com.example.exceltest                W  	at android.view.View.performClickInternal(View.java:7636)
2024-10-18 15:41:55.370 10561-10561 System.err              com.example.exceltest                W  	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
2024-10-18 15:41:55.370 10561-10561 System.err              com.example.exceltest                W  	at android.view.View$PerformClick.run(View.java:30156)
2024-10-18 15:41:55.370 10561-10561 System.err              com.example.exceltest                W  	at android.os.Handler.handleCallback(Handler.java:958)
2024-10-18 15:41:55.370 10561-10561 System.err              com.example.exceltest                W  	at android.os.Handler.dispatchMessage(Handler.java:99)
2024-10-18 15:41:55.370 10561-10561 System.err              com.example.exceltest                W  	at android.os.Looper.loopOnce(Looper.java:205)
2024-10-18 15:41:55.370 10561-10561 System.err              com.example.exceltest                W  	at android.os.Looper.loop(Looper.java:294)
2024-10-18 15:41:55.370 10561-10561 System.err              com.example.exceltest                W  	at android.app.ActivityThread.main(ActivityThread.java:8177)
2024-10-18 15:41:55.370 10561-10561 System.err              com.example.exceltest                W  	at java.lang.reflect.Method.invoke(Native Method)
2024-10-18 15:41:55.370 10561-10561 System.err              com.example.exceltest                W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
2024-10-18 15:41:55.370 10561-10561 System.err              com.example.exceltest                W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
2024-10-18 15:41:55.374 10561-10561 System.err              com.example.exceltest                W  ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
2024-10-18 15:41:55.381 10561-10561 ample.exceltest         com.example.exceltest                W  Accessing hidden method Ljava/lang/invoke/LambdaMetafactory;->metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; (blocked, linking, denied)
2024-10-18 15:41:55.397 10561-10561 Compatibil...geReporter com.example.exceltest                D  Compat change id reported: 247079863; UID 10199; state: ENABLED
2024-10-18 15:41:56.512 10561-10561 AndroidRuntime          com.example.exceltest                E  FATAL EXCEPTION: main
                                                                                                    Process: com.example.exceltest, PID: 10561
                                                                                                    com.alibaba.excel.exception.ExcelGenerateException: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/font/FontRenderContext;
                                                                                                    	at com.alibaba.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl.java:65)
                                                                                                    	at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:73)
                                                                                                    	at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:50)
                                                                                                    	at com.alibaba.excel.write.builder.ExcelWriterSheetBuilder.doWrite(ExcelWriterSheetBuilder.java:62)
                                                                                                    	at com.example.exceltest.excel.ExcelFileWriter.doWrite(ExcelFileWriter.kt:17)
                                                                                                    	at com.example.exceltest.ui.home.HomeFragment$onCreateView$2$1$1.invokeSuspend(HomeFragment.kt:41)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:367)
                                                                                                    	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
                                                                                                    	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
                                                                                                    	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
                                                                                                    	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
                                                                                                    	at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
                                                                                                    	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
                                                                                                    	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
                                                                                                    	at com.example.exceltest.ui.home.HomeFragment.onCreateView$lambda$1(HomeFragment.kt:40)
                                                                                                    	at com.example.exceltest.ui.home.HomeFragment.$r8$lambda$hhnyguiE5IWBBZRazxnwEa277tU(Unknown Source:0)
                                                                                                    	at com.example.exceltest.ui.home.HomeFragment$$ExternalSyntheticLambda0.onClick(D8$$SyntheticClass:0)
                                                                                                    	at android.view.View.performClick(View.java:7659)
                                                                                                    	at android.view.View.performClickInternal(View.java:7636)
                                                                                                    	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
                                                                                                    	at android.view.View$PerformClick.run(View.java:30156)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@d8c095f, Dispatchers.Main.immediate]
                                                                                                    Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/font/FontRenderContext;
                                                                                                    	at org.apache.poi.ss.util.SheetUtil.<clinit>(SheetUtil.java:98)
                                                                                                    	at org.apache.poi.xssf.streaming.AutoSizeColumnTracker.<init>(AutoSizeColumnTracker.java:117)
                                                                                                    	at org.apache.poi.xssf.streaming.SXSSFSheet.<init>(SXSSFSheet.java:106)
                                                                                                    	at org.apache.poi.xssf.streaming.SXSSFWorkbook.createAndRegisterSXSSFSheet(SXSSFWorkbook.java:694)
                                                                                                    	at org.apache.poi.xssf.streaming.SXSSFWorkbook.createSheet(SXSSFWorkbook.java:712)
                                                                                                    	at org.apache.poi.xssf.streaming.SXSSFWorkbook.createSheet(SXSSFWorkbook.java:104)
                                                                                                    	at com.alibaba.excel.util.WorkBookUtil.createSheet(WorkBookUtil.java:86)
                                                                                                    	at com.alibaba.excel.context.WriteContextImpl.createSheet(WriteContextImpl.java:223)
                                                                                                    	at com.alibaba.excel.context.WriteContextImpl.initSheet(WriteContextImpl.java:203)
                                                                                                    	at com.alibaba.excel.context.WriteContextImpl.currentSheet(WriteContextImpl.java:135)
                                                                                                    	at com.alibaba.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl.java:54)
                                                                                                    	... 30 more
2024-10-18 15:41:56.512 10561-10561 AndroidRuntime          com.example.exceltest                E  Caused by: java.lang.ClassNotFoundException: Didn't find class "java.awt.font.FontRenderContext" on path: DexPathList[[dex file "/data/data/com.example.exceltest/code_cache/.overlay/base.apk/classes4.dex", zip file "/data/app/~~c7c3MTIygZcN9kJ-HRfL8g==/com.example.exceltest-6lqs4k45Ciuw6qUJT7DXRQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~c7c3MTIygZcN9kJ-HRfL8g==/com.example.exceltest-6lqs4k45Ciuw6qUJT7DXRQ==/lib/arm64, /system/lib64, /system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	... 41 more
---------------------------- PROCESS ENDED (10561) for package com.example.exceltest ----------------------------
2024-10-18 15:41:56.522 10561-10561 Process                 com.example.exceltest                I  Sending signal. PID: 10561 SIG: 9
```
