### ISSUE TITLE
行数超过百万报错要怎么解决？我已经分sheet了，好像不管用？    Invalid row number (1048576) outside allowable range (0..1048575)

### ISSUE THREAD

**Issue by Godfavorstheinfantry** [alibaba/easyexcel#403]
`2019-06-13 15:48:51,217 ERROR [500.jsp] - Invalid row number (1048576) outside allowable range (0..1048575)
java.lang.IllegalArgumentException: Invalid row number (1048576) outside allowable range (0..1048575)
	at org.apache.poi.xssf.streaming.SXSSFSheet.createRow(SXSSFSheet.java:123)
	at org.apache.poi.xssf.streaming.SXSSFSheet.createRow(SXSSFSheet.java:65)
	at com.alibaba.excel.util.WorkBookUtil.createRow(WorkBookUtil.java:55)
	at com.alibaba.excel.write.ExcelBuilderImpl.addOneRowOfDataToExcel(ExcelBuilderImpl.java:132)
	at com.alibaba.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl.java:65)
	at com.alibaba.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl.java:79)
	at com.alibaba.excel.ExcelWriter.write1(ExcelWriter.java:179)
	at com.jeeplus.modules.sztd.service.SensorDataService.getExcelByTimeRange(SensorDataService.java:183)`

**Comment by zhouquan2016** [comment]
怎么解决得？

**Comment by richardplas** [comment]
没人管吗？我也遇到了
