### ISSUE TITLE
Fontconfig head is null, check your fonts or fonts configuration

### ISSUE THREAD

**Issue by Rmond** [alibaba/easyexcel#4065]
Caused by: java.lang.RuntimeException: Fontconfig head is null, check your fonts or fonts configuration
	at java.desktop/sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1271)
	at java.desktop/sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:224)
	at java.desktop/sun.awt.FontConfiguration.init(FontConfiguration.java:106)
	at java.desktop/sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:706)
	at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:358)
	at java.desktop/sun.font.SunFontManager$2.run(SunFontManager.java:315)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/sun.font.SunFontManager.<init>(SunFontManager.java:315)
	at java.desktop/sun.awt.FcFontManager.<init>(FcFontManager.java:35)
	at java.desktop/sun.awt.X11FontManager.<init>(X11FontManager.java:56)
	... 135 common frames omitted

容器环境，镜像版本 openjdk-alpine:17.0.11-cds
已经用如下命令安装300+字体，依然报错
RUN apk add  fontconfig ttf-dejavu font-noto-cjk font-noto-extra
版本：3.3.4

**Comment by tlbcc** [comment]
``` bash
yum install -y fontconfig
```

我也遇到了同样的问题，操作系统安装这个库后，重启服务就好了
