### ISSUE TITLE
用excel可以打开的文件，用该工具读取报错。

### ISSUE THREAD

**Issue by zishinan** [alibaba/easyexcel#411]
读取代码：
`InputStream inputStream = FileUtil.getResourcesFileInputStream("5555.xls");
        List<Object> data = EasyExcelFactory.read(inputStream, new Sheet(1, 0));
        inputStream.close();
        print(data);`
报错信息：
`com.alibaba.excel.exception.ExcelAnalysisException: File type error，io must be available markSupported,you can do like this <code> new BufferedInputStream(new FileInputStream(\"/xxxx\"))</code> "

	at com.alibaba.excel.analysis.ExcelAnalyserImpl.getSaxAnalyser(ExcelAnalyserImpl.java:58)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.analysis(ExcelAnalyserImpl.java:72)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.analysis(ExcelAnalyserImpl.java:67)
	at com.alibaba.excel.ExcelReader.read(ExcelReader.java:112)`

**Comment by zishinan** [comment]
补充一下，表是从考勤机导出来的，另存一次后就可以打开。
大概也知道是文件类型的问题，但是具体细节不清楚。
而且excel能解析，理论上Java也应该可以，难道要改POI底层？
请大神解惑，谢谢。

**Comment by zhuangjiaju** [comment]
这个已经在最新版本修复，请使用最新版本。https://maven-badges.herokuapp.com/maven-central/com.alibaba/easyexcel。 并且参照：https://github.com/alibaba/easyexcel/blob/master/quickstart.md 去书写。
