### ISSUE TITLE
Write Excel时ExcelColumnNum注解不能用吗？由于没有head，合并单元格判断那里出现报数组越界异常

### ISSUE THREAD

**Issue by Uetty** [alibaba/easyexcel#451]
@ExcelColumnNum(value=6)
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:422)
	at java.util.ArrayList.get(ArrayList.java:435)
	at com.alibaba.excel.metadata.ExcelHeadProperty.getHeadByRowNum(ExcelHeadProperty.java:176)
	at com.alibaba.excel.metadata.ExcelHeadProperty.getCellRangeModels(ExcelHeadProperty.java:161)
	at com.alibaba.excel.context.WriteContext.addMergedRegionToCurrentSheet(WriteContext.java:182)
	at com.alibaba.excel.context.WriteContext.initTableHead(WriteContext.java:169)
	at com.alibaba.excel.context.WriteContext.initCurrentSheet(WriteContext.java:137)
	at com.alibaba.excel.context.WriteContext.currentSheet(WriteContext.java:125)
	at com.alibaba.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl.java:71)
	at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:91)
	at com.uetty.test.EasyExcelTest.main(EasyExcelTest.java:104)

**Comment by Uetty** [comment]
嗯，知道了，@ExcelProperty和@ExcelColumnNum注解不能同时使用，只能使用其中一种。
建议FAQ
