### ISSUE TITLE
读取.xlsx文件出错，找不到sharedString.xml文件

### ISSUE THREAD

**Issue by hahaduo** [alibaba/easyexcel#49]
<img width="922" alt="qq20180814-225547 2x" src="https://user-images.githubusercontent.com/1441608/44100656-21cb3536-a018-11e8-99b8-3961333e19cd.png">

我用的是mac系统，把官方的例子拷贝过来执行，报下面的错误，莫名其妙，我也不知道错误中那个文件为什么找不到，这个文件不是我的，应该是执行过程中生成的文件。
`
java.io.FileNotFoundException: /var/folders/p4/ytdlw57579d6tf7fndxzj84r0000gn/T/easyexcel/-4992373293564731499/xl/sharedStrings.xml (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.alibaba.excel.read.SaxAnalyserV07.initSharedStringsTable(SaxAnalyserV07.java:221)
	at com.alibaba.excel.read.SaxAnalyserV07.start(SaxAnalyserV07.java:158)
	at com.alibaba.excel.read.SaxAnalyserV07.<init>(SaxAnalyserV07.java:61)
	at com.alibaba.excel.read.ExcelAnalyserImpl.getSaxAnalyser(ExcelAnalyserImpl.java:28)
	at com.alibaba.excel.read.ExcelAnalyserImpl.analysis(ExcelAnalyserImpl.java:49)
	at com.alibaba.excel.ExcelReader.read(ExcelReader.java:55)
`

**Comment by xulj1989** [comment]
文件中有字符串(非数值)时才会生成sharedStrings.xml

**Comment by jipengfei-jpf** [comment]
由于1.0.*版本核心考虑的是怎么解决读excel内存溢出问题，自己重写了读excel的POI的底层，写仍旧使用POI。可以从根本解决OOM问题。但是由于自己对excel的格式认识不全面，有很多坑产生了很多BUG。最新版本以POI为底层。最新版：1.1.2-beat1，虽然不能完全解决OOM但可以解决大部分的OOM问题，完全解决OOM版本会等稳定后再开放，敬请理解。目前稳定版本1.1.2-beat1
