### ISSUE TITLE
最新版本导出多字段数据时候会抛异常

### ISSUE THREAD

**Issue by aiwthao** [alibaba/easyexcel#514]
com.alibaba.excel.exception.ExcelGenerateException: The index of erictionTorquePercentage and neutralSwitchStatus must be inconsistent
	at com.alibaba.excel.metadata.property.ExcelHeadProperty.initColumnProperties(ExcelHeadProperty.java:141)
	at com.alibaba.excel.metadata.property.ExcelHeadProperty.<init>(ExcelHeadProperty.java:75)
	at com.alibaba.excel.write.property.ExcelWriteHeadProperty.<init>(ExcelWriteHeadProperty.java:35)
	at com.alibaba.excel.write.metadata.holder.AbstractWriteHolder.<init>(AbstractWriteHolder.java:101)
	at com.alibaba.excel.write.metadata.holder.WriteWorkbookHolder.<init>(WriteWorkbookHolder.java:82)
	at com.alibaba.excel.context.WriteContextImpl.initCurrentWorkbookHolder(WriteContextImpl.java:103)
	at com.alibaba.excel.context.WriteContextImpl.<init>(WriteContextImpl.java:65)
	at com.alibaba.excel.write.ExcelBuilderImpl.<init>(ExcelBuilderImpl.java:55)
	at com.alibaba.excel.ExcelWriter.<init>(ExcelWriter.java:40)
	at com.alibaba.excel.write.builder.ExcelWriterBuilder.build(ExcelWriterBuilder.java:171)
	at com.alibaba.excel.write.builder.ExcelWriterBuilder.sheet(ExcelWriterBuilder.java:187)
	at com.alibaba.excel.write.builder.ExcelWriterBuilder.sheet(ExcelWriterBuilder.java:183)
	at com.saicmotor.maxus.status.handler.ExportEvgbHandler.exportD20VehSignal(ExportEvgbHandler.java:593)
	at com.saicmotor.maxus.status.server.ExportStatusServer.exportD20VehSignal(ExportStatusServer.java:81)

**Comment by aiwthao** [comment]
在1.1.2-beta5 版本中无这种问题

**Comment by zhuangjiaju** [comment]
请尝试 将 这两个字段 用不同的index 。

**Comment by aiwthao** [comment]
你好 请问是哪两个? 我的VO实体类里面都是定义了不同的index

**Comment by zhuangjiaju** [comment]
erictionTorquePercentage and neutralSwitchStatus

**Comment by aiwthao** [comment]
这算是BUG么?还是就是设计成这样的?
