### ISSUE TITLE
升级2.0.0-beta3的jar冲突

### ISSUE THREAD

**Issue by liweixian** [alibaba/easyexcel#537]
**异常代码**
```
04-Sep-2019 09:55:18.601 SEVERE [RMI TCP Connection(4)-127.0.0.1] org.apache.catalina.startup.ContextConfig.processAnnotationsJar Unable to process Jar entry [module-info.class] from Jar [jar:file:/D:/gitFile/gitFile/test/test/target/test/WEB-INF/lib/istack-commons-runtime-3.0.7.jar!/] for annotations
 org.apache.tomcat.util.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 19
	at org.apache.tomcat.util.bcel.classfile.Constant.readConstant(Constant.java:97)
	at org.apache.tomcat.util.bcel.classfile.ConstantPool.<init>(ConstantPool.java:54)

```
**异常提示**
stax-ex-1.8.jar
txw2-2.3.1.jar
jaxb-runtime-2.3.1.jar
FastInfoset-1.2.15.jar
jaxb-api-2.3.1.jar
这几个包报ClassFormatException: Invalid byte tag in constant pool: 19
我用的jdk是1.8.092，从easyexcel1升级到2后就出现这个问题，有人说是poi版本太高和jdk冲突的问题，虽然能运行tomcat，但是每次启动都会报错

**Comment by zhuangjiaju** [comment]
请尝试使用tomcat8 及以上版本

**Comment by ggfickle** [comment]
> 请尝试使用tomcat8 及以上版本

我用的tomcat 8.5也会报这个错误
