### ISSUE TITLE
支持列表

### ISSUE THREAD

**Issue by githublms** [alibaba/easyexcel#538]
数据结构如下：
````
public class AA{
String  name;
List<BB>bb；
}
class BB{
String color;
....
}

```
导出时报错
```
com.alibaba.excel.exception.ExcelDataConvertException: Can not find 'Converter' support class List.
	at com.alibaba.excel.write.ExcelBuilderImpl.convert(ExcelBuilderImpl.java:355)
	at com.alibaba.excel.write.ExcelBuilderImpl.converterAndSet(ExcelBuilderImpl.java:293)
```

**Comment by zhuangjiaju** [comment]
目前不支持list 请自定义转换器 或者用 `@ExcelIgnore`将这列不放入excel

**Comment by perhamer** [comment]
不向下兼容的吗?

**Comment by zenglanyuan** [comment]
实体导出的List类型的加了 @ExcelIgnore 注解， 也是一直提示这个问题。

**Comment by yhx1001** [comment]
怎么自定义转换吗

**Comment by yhx1001** [comment]
怎么自定义转换，大佬

**Comment by darkjune** [comment]
> 怎么自定义转换，大佬

继承下Convert类看
