### ISSUE TITLE
Can not Close IO

### ISSUE THREAD

**Issue by HoZanDung** [alibaba/easyexcel#604]
om.alibaba.excel.exception.ExcelGenerateException: Can not close IO
	at com.alibaba.excel.context.WriteContextImpl.finish(WriteContextImpl.java:350)
	at com.alibaba.excel.write.ExcelBuilderImpl.finish(ExcelBuilderImpl.java:105)
	at com.alibaba.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl.java:97)
	at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:154)
	at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:139)
	at cn.com.gzkit.common.excel.ExportUtil.easyExcelExport(ExportUtil.java:92)
	at cn.com.gzkit.changingManagement.controller.ChangingController.exportExcel(ChangingController.java:1294)
	at cn.com.gzkit.changingManagement.controller.ChangingController$$FastClassBySpringCGLIB$$3cf8e2b8.invoke(<generated>)

----- 以下为调用代码 -----
       ExcelWriter excelWriter = EasyExcel.write(dest.getPath(), clz).build();

        WriteSheet writeSheet1 = EasyExcel.writerSheet("模板1").build();
        WriteSheet writeSheet2 = EasyExcel.writerSheet("模板2").build();

        excelWriter.write(list, writeSheet1);
        excelWriter.write(list, writeSheet2);
        /// 千万别忘记finish 会帮忙关闭流
        excelWriter.finish();

---- 传入对象 -----
clz是实体类class,里面有自己自定义的注解
list是List<实体类>的一个list,第一句写那个sheet报了一个没办法关闭
用的版本是2.0.0-beta1。我换一个试试吧哈哈

**Comment by HoZanDung** [comment]
哦 我看了一眼发现问题了this.writeWorkbookHolder.getWorkbook().close();
这个版本没有close的方法，我换个版本试试

**Comment by HoZanDung** [comment]
哦弄好了,我的POI包版本低了 3.9没有那个方法
