### ISSUE TITLE
 Can not close IO

### ISSUE THREAD

**Issue by wyzhangjie** [alibaba/easyexcel#613]
**异常代码**
```java
   EasyExcel.read(is, GipsVo.class,new GipsListener(externalHandlerContext)).sheet(0).doRead();
```
**异常提示**
com.alibaba.excel.exception.ExcelAnalysisException: Can not close IO
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.throwCanNotCloseIo(ExcelAnalyserImpl.java:152) ~[easyexcel-2.0.0.jar:?]
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.finish(ExcelAnalyserImpl.java:125) ~[easyexcel-2.0.0.jar:?]
	at com.alibaba.excel.ExcelReader.finalize(ExcelReader.java:286) [easyexcel-2.0.0.jar:?]
	at java.lang.System$2.invokeFinalize(System.java:1270) [?:1.8.0_102]
	at java.lang.ref.Finalizer.runFinalizer(Finalizer.java:98) [?:1.8.0_102]
	at java.lang.ref.Finalizer.access$100(Finalizer.java:34) [?:1.8.0_102]
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:210) [?:1.8.0_102]
Caused by: java.io.FileNotFoundException: C:\Users\jiezh\AppData\Local\Temp\excache\43dabea0-4c94-4ed2-bf92-7ffe74cc619d\437537ad-0ff6-4e75-bb77-235ddd88991e.xlsx (系统找不到指定的路径。)
	at java.io.FileOutputStream.open0(Native Method) ~[?:1.8.0_102]
	at java.io.FileOutputStream.open(FileOutputStream.java:270) ~[?:1.8.0_102]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213) ~[?:1.8.0_102]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162) ~[?:1.8.0_102]
	at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1471) ~[poi-ooxml-4.0.1.jar:4.0.1]
	at org.apache.poi.openxml4j.opc.OPCPackage.close(OPCPackage.java:447) ~[poi-ooxml-4.0.1.jar:4.0.1]
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.finish(ExcelAnalyserImpl.java:122) ~[easyexcel-2.0.0.jar:?]
	... 5 more
**建议描述**
50万数据跑着跑着报这个错误了，请问是啥原因呢

**Comment by zhuangjiaju** [comment]
这个是这样子的，中间用到了临时文件。是否你中间有删除过java的临时文件？

**Comment by luckyuer** [comment]
writeWorkbookHolder.getWorkbook().close();这个方法在2.0.1中不存在？

**Comment by luoniabiao** [comment]
maven里面又引入了其它版本的poi要怎么解决兼容呢？

**Comment by zhuangjiaju** [comment]
> maven里面又引入了其它版本的poi要怎么解决兼容呢？

统一版本就可以

**Comment by wylyeak** [comment]
1. 确认 POI 的版本， 可以尝试升级到```4.1.0```版本

```
 <dependency>
    <groupId>org.apache.poi</groupId>
    <artifactId>poi</artifactId>
    <version>4.1.0</version>
</dependency>
<dependency>
    <groupId>org.apache.poi</groupId>
    <artifactId>poi-ooxml</artifactId>
    <version>4.1.0</version>
</dependency>
```

2. 确认项目 ASM 依赖是否有两个,  需要```org.ow2.asm:asm```, 排除 ```asm:asm```

**Comment by shenzhuan** [comment]
我只引入了easyexcel3.1.1 没有其他任何poi也会有这样的错误
