### ISSUE TITLE
org.apache.poi.poifs.filesystem.FileMagic

### ISSUE THREAD

**Issue by zyjin** [alibaba/easyexcel#636]
**触发场景描述**
   如下代码所示
**触发Bug的代码**
```java
    @Test
    public void simpleRead() {

        // 写法2：
        String fileName =  "test.xlsx";
        ExcelReader excelReader = EasyExcel.read(fileName, DemoData.class, new DemoDataListener()).build();
        ReadSheet readSheet = EasyExcel.readSheet(0).build();
        excelReader.read(readSheet);
        // 这里千万别忘记关闭，读的时候会创建临时文件，到时磁盘会崩的
        excelReader.finish();
    }
```
**提示的异常或者没有达到的效果**
Caused by: java.lang.ClassNotFoundException: org.apache.poi.poifs.filesystem.FileMagic
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 32 more

**Comment by zhuangjiaju** [comment]
请尝试先阅读文档，这个问题在文档中有描述，jar冲突，请统一poi版本
