### ISSUE TITLE
Found interface org.apache.poi.util.POILogger, but class was expected

### ISSUE THREAD

**Issue by gongfj** [alibaba/easyexcel#694]
在做项目时，使用导出excel时遇到这个问题，不知如何解决，求指导Caused by: java.lang.IncompatibleClassChangeError: Found interface org.apache.poi.util.POILogger, but class was expected

**Comment by zhuangjiaju** [comment]
请提供详细异常代码

**Comment by zhuangjiaju** [comment]
不知道您是否已经解决了问题？如果未解决 请重新打开问题

**Comment by michaellct** [comment]
解决了吗？我还引用了
	<dependency>
        <groupId>org.apache.poi</groupId>
        <artifactId>poi</artifactId>
        <version>4.1.0</version>
	</dependency>
``
Caused by: java.lang.IncompatibleClassChangeError: Found interface org.apache.poi.util.POILogger, but class was expected
	at org.apache.poi.openxml4j.opc.ZipPackage.buildPartName(ZipPackage.java:366)
	at org.apache.poi.openxml4j.opc.ZipPackage.getPartsImpl(ZipPackage.java:303)
	at org.apache.poi.openxml4j.opc.OPCPackage.getParts(OPCPackage.java:756)
	at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:298)
	at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:201)
	at com.alibaba.excel.analysis.v07.XlsxSaxAnalyser.readOpcPackage(XlsxSaxAnalyser.java:124)
	at com.alibaba.excel.analysis.v07.XlsxSaxAnalyser.<init>(XlsxSaxAnalyser.java:58)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.choiceExcelExecutor(ExcelAnalyserImpl.java:92)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.<init>(ExcelAnalyserImpl.java:45)
``

**Comment by xpwi** [comment]
The org.apache.poi.util.POILogger was an abstract class until apache poi 4.0.1. Now in apache poi 4.1.0 it is an interface. You have a mix of apache poi versions running. Exactly version 4.1.0 and an earlier version. Don't do that

**Comment by xpwi** [comment]
版本问题 copy  from stackoverflow
