### ISSUE TITLE
2.0.5 xls格式的文件获取sheet里面总行数报空指针

### ISSUE THREAD

**Issue by zarkerXu** [alibaba/easyexcel#722]
**异常代码**
```java
   这里写你的代码
``` analysisContext.readSheetHolder().getTotal()
**异常提示**
请提供完整的异常提示,记住是全部异常！
java.lang.NullPointerException
	at com.hzcursor.q_core.excel.ReadFileListener.invoke(ReadFileListener.java:84)
	at com.hzcursor.q_core.excel.ReadFileListener.invoke(ReadFileListener.java:20)
	at com.alibaba.excel.read.metadata.holder.AbstractReadHolder.notifyEndOneRow(AbstractReadHolder.java:141)
	at com.alibaba.excel.analysis.v03.XlsSaxAnalyser.endRow(XlsSaxAnalyser.java:188)
	at com.alibaba.excel.analysis.v03.XlsSaxAnalyser.processLastCellOfRow(XlsSaxAnalyser.java:178)
	at com.alibaba.excel.analysis.v03.XlsSaxAnalyser.processRecord(XlsSaxAnalyser.java:167)
	at org.apache.poi.hssf.eventusermodel.MissingRecordAwareHSSFListener.processRecord(MissingRecordAwareHSSFListener.java:158)
	at org.apache.poi.hssf.eventusermodel.FormatTrackingHSSFListener.processRecord(FormatTrackingHSSFListener.java:92)
	at org.apache.poi.hssf.eventusermodel.HSSFRequest.processRecord(HSSFRequest.java:109)
	at org.apache.poi.hssf.eventusermodel.HSSFEventFactory.genericProcessEvents(HSSFEventFactory.java:179)
	at org.apache.poi.hssf.eventusermodel.HSSFEventFactory.processEvents(HSSFEventFactory.java:136)
	at org.apache.poi.hssf.eventusermodel.HSSFEventFactory.processWorkbookEvents(HSSFEventFactory.java:82)
	at org.apache.poi.hssf.eventusermodel.HSSFEventFactory.processWorkbookEvents(HSSFEventFactory.java:54)
	at com.alibaba.excel.analysis.v03.XlsSaxAnalyser.execute(XlsSaxAnalyser.java:107)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.analysis(ExcelAnalyserImpl.java:91)
	at com.alibaba.excel.ExcelReader.read(ExcelReader.java:170)
	at com.hzcursor.q_core.service.impl.SmartModelRunServiceImpl.doReadFile(SmartModelRunServiceImpl.java:115)
	at com.hzcursor.q_core.service.impl.SmartModelRunServiceImpl.runSmartModel(SmartModelRunServiceImpl.java:91)
	at com.hzcursor.q_core.threadPool.IntentionRunner.run(IntentionRunner.java:43)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

**建议描述**
Listener 的invoke获取xls格式sheet的总行数报空指针，xlsx是正常的

**Comment by zhuangjiaju** [comment]
这个是bug ，我空了研究下。但是这个行数也是不会特别精确。最终还是要以自己的统计为准

**Comment by zarkerXu** [comment]
> 这个是bug ，我空了研究下。但是这个行数也是不会特别精确。最终还是要以自己的统计为准

好的，多谢大神了
