### ISSUE TITLE
导出文件的时候报 Can not close IO，文件也顺利导出来了

### ISSUE THREAD

**Issue by huangfuliang** [alibaba/easyexcel#736]
**异常代码**
```java
   EasyExcel.write(response.getOutputStream(), WarningExportVO.class).sheet("预警工单").doWrite(warningExports);
```
**异常提示**
com.alibaba.excel.exception.ExcelGenerateException: Can not close IO
	at com.alibaba.excel.context.WriteContextImpl.throwCanNotCloseIo(WriteContextImpl.java:390)
	at com.alibaba.excel.context.WriteContextImpl.finish(WriteContextImpl.java:352)
	at com.alibaba.excel.write.ExcelBuilderImpl.finish(ExcelBuilderImpl.java:106)
	at com.alibaba.excel.ExcelWriter.finish(ExcelWriter.java:297)
	at com.alibaba.excel.write.builder.ExcelWriterSheetBuilder.doWrite(ExcelWriterSheetBuilder.java:135)
**建议描述**

**Comment by zhuangjiaju** [comment]
请提供全部异常
