### ISSUE TITLE
2.1.0-beta1/beta2 03版指定sheet，java.lang.NullPointerException

### ISSUE THREAD

**Issue by xht592** [alibaba/easyexcel#742]
**触发场景描述**
03版指定sheetNo>0,则报错
**触发Bug的代码**
```java
    ExcelReaderBuilder read = EasyExcel.read(excelPath, new TestExcelListener());
    ExcelReaderSheetBuilder sheet = read.sheet(1);
    sheet.doRead();
```
**提示的异常或者没有达到的效果**
java.lang.NullPointerException
	at com.alibaba.excel.analysis.v03.handlers.BofRecordHandler.processRecord(BofRecordHandler.java:78)
	at com.alibaba.excel.analysis.v03.XlsSaxAnalyser.processRecord(XlsSaxAnalyser.java:138)
	at org.apache.poi.hssf.eventusermodel.MissingRecordAwareHSSFListener.processRecord(MissingRecordAwareHSSFListener.java:203)
	at org.apache.poi.hssf.eventusermodel.FormatTrackingHSSFListener.processRecord(FormatTrackingHSSFListener.java:92)
	at org.apache.poi.hssf.eventusermodel.HSSFRequest.processRecord(HSSFRequest.java:109)
	at org.apache.poi.hssf.eventusermodel.HSSFEventFactory.genericProcessEvents(HSSFEventFactory.java:179)
	at org.apache.poi.hssf.eventusermodel.HSSFEventFactory.processEvents(HSSFEventFactory.java:136)
	at org.apache.poi.hssf.eventusermodel.HSSFEventFactory.processWorkbookEvents(HSSFEventFactory.java:82)
	at org.apache.poi.hssf.eventusermodel.HSSFEventFactory.processWorkbookEvents(HSSFEventFactory.java:54)
	at com.alibaba.excel.analysis.v03.XlsSaxAnalyser.execute(XlsSaxAnalyser.java:110)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.analysis(ExcelAnalyserImpl.java:104)
	at com.alibaba.excel.ExcelReader.read(ExcelReader.java:185)
	at com.alibaba.excel.ExcelReader.read(ExcelReader.java:174)
	at com.alibaba.excel.read.builder.ExcelReaderSheetBuilder.doRead(ExcelReaderSheetBuilder.java:160)

**Comment by zhuangjiaju** [comment]
建议升级到 `2.0.5` 如果你要读取全部sheet的话 升到到`2.1.0-beat2`

**Comment by xht592** [comment]
2.0.*版本 03版不能获取 sheetName，total等
