### ISSUE TITLE
您好，我在用easyExcel读.xlsx时超过6000行报错Can not close IO，麻烦帮忙指点下，谢谢啦！

### ISSUE THREAD

**Issue by SuperQiangYuan** [alibaba/easyexcel#865]
**异常代码**
```
//这是读excel的代码
public static List<String> readExcelNeName(File excelFile) {
        ExcelReadListener listener = new ExcelReadListener();
       //这行报错
        EasyExcel.read(excelFile, ExcelData.class, listener).sheet().headRowNumber(2).doRead();
        return new ArrayList<>(listener.getNeNames());
    }


//这是定义的ExcelData
public class ExcelData {
    @ExcelProperty(index = 1)
    private String neName;

    public String getNeName() {
        return neName;
    }

    public void setNeName(String neName) {
        this.neName = neName;
    }
}


//这是Listener
public class ExcelReadListener extends AnalysisEventListener<ExcelData> {
    private Set<String> neNames = new HashSet<>();

    public Set<String> getNeNames() {
        return neNames;
    }

    @Override
    public void invoke(ExcelData data, AnalysisContext context) {
        String neName = JSONObject.parseObject(JSON.toJSONString(data)).getString("neName");
        if (StringUtils.isNotEmpty(neName)) {
            neNames.add(neName);
        }
    }

    @Override
    public void doAfterAllAnalysed(AnalysisContext context) {

    }
}
```
**异常提示**
[ ERROR]:2019-11-20 09:57:53 [pool-7-thread-3] CmePreTaskManage:122 - com.alibaba.excel.exception.ExcelAnalysisException: Can not close IO
com.alibaba.excel.exception.ExcelAnalysisException: Can not close IO
        at com.alibaba.excel.analysis.ExcelAnalyserImpl.throwCanNotCloseIo(ExcelAnalyserImpl.java:152) ~[easyexcel-2.0.0.jar:?]
        at com.alibaba.excel.analysis.ExcelAnalyserImpl.finish(ExcelAnalyserImpl.java:125) ~[easyexcel-2.0.0.jar:?]
        at com.alibaba.excel.analysis.ExcelAnalyserImpl.<init>(ExcelAnalyserImpl.java:43) ~[easyexcel-2.0.0.jar:?]
        at com.alibaba.excel.ExcelReader.<init>(ExcelReader.java:145) ~[easyexcel-2.0.0.jar:?]
        at com.alibaba.excel.read.builder.ExcelReaderBuilder.build(ExcelReaderBuilder.java:203) ~[easyexcel-2.0.0.jar:?]
        at com.alibaba.excel.read.builder.ExcelReaderBuilder.sheet(ExcelReaderBuilder.java:219) ~[easyexcel-2.0.0.jar:?]
        at com.alibaba.excel.read.builder.ExcelReaderBuilder.sheet(ExcelReaderBuilder.java:207) ~[easyexcel-2.0.0.jar:?]
        at com.huawei.genexcloud.util.fileprocess.FileProcess.readExcelNeName(FileProcess.java:57) ~[classes/:?]
        at com.huawei.genexcloud.cme.CmePreTaskManage$CmePreTaskThread.run(CmePreTaskManage.java:100) [classes/:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: org.apache.poi.openxml4j.exceptions.OpenXML4JRuntimeException: Fail to save: an error occurs while saving the package : The part /xl/styles.xml failed to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@d689707
        at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:558) ~[poi-ooxml-4.1.0.jar:4.1.0]
        at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1488) ~[poi-ooxml-4.1.0.jar:4.1.0]
        at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1475) ~[poi-ooxml-4.1.0.jar:4.1.0]
        at org.apache.poi.openxml4j.opc.ZipPackage.closeImpl(ZipPackage.java:431) ~[poi-ooxml-4.1.0.jar:4.1.0]
        at org.apache.poi.openxml4j.opc.OPCPackage.close(OPCPackage.java:451) ~[poi-ooxml-4.1.0.jar:4.1.0]
        at com.alibaba.excel.analysis.ExcelAnalyserImpl.finish(ExcelAnalyserImpl.java:122) ~[easyexcel-2.0.0.jar:?]
        ... 10 more
Caused by: org.apache.poi.openxml4j.exceptions.OpenXML4JException: The part /xl/styles.xml failed to be saved in the stream with marshaller org.apache.poi.openxml4j.opc.internal.marshallers.DefaultMarshaller@d689707
        at org.apache.poi.openxml4j.opc.ZipPackage.saveImpl(ZipPackage.java:547) ~[poi-ooxml-4.1.0.jar:4.1.0]
        at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1488) ~[poi-ooxml-4.1.0.jar:4.1.0]
        at org.apache.poi.openxml4j.opc.OPCPackage.save(OPCPackage.java:1475) ~[poi-ooxml-4.1.0.jar:4.1.0]
        at org.apache.poi.openxml4j.opc.ZipPackage.closeImpl(ZipPackage.java:431) ~[poi-ooxml-4.1.0.jar:4.1.0]
        at org.apache.poi.openxml4j.opc.OPCPackage.close(OPCPackage.java:451) ~[poi-ooxml-4.1.0.jar:4.1.0]
        at com.alibaba.excel.analysis.ExcelAnalyserImpl.finish(ExcelAnalyserImpl.java:122) ~[easyexcel-2.0.0.jar:?]
        ... 10 more
[ WARN ]:2019-11-20 10:15:57 [Finalizer] ExcelReader:288 - Destroy object failed
java.lang.NullPointerException: null
        at com.alibaba.excel.ExcelReader.finalize(ExcelReader.java:286) [easyexcel-2.0.0.jar:?]
        at java.lang.System$2.invokeFinalize(System.java:1270) [?:1.8.0_191]
        at java.lang.ref.Finalizer.runFinalizer(Finalizer.java:102) [?:1.8.0_191]
        at java.lang.ref.Finalizer.access$100(Finalizer.java:34) [?:1.8.0_191]
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:217) [?:1.8.0_191]
[ WARN ]:2019-11-20 10:15:57 [Finalizer] ExcelReader:288 - Destroy object failed
java.lang.NullPointerException: null
        at com.alibaba.excel.ExcelReader.finalize(ExcelReader.java:286) [easyexcel-2.0.0.jar:?]
        at java.lang.System$2.invokeFinalize(System.java:1270) [?:1.8.0_191]
        at java.lang.ref.Finalizer.runFinalizer(Finalizer.java:102) [?:1.8.0_191]
        at java.lang.ref.Finalizer.access$100(Finalizer.java:34) [?:1.8.0_191]
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:217) [?:1.8.0_191]
**建议描述**

**Comment by pdkst** [comment]
我测试生成的，新建的，改名xls，读取都没有复现这个问题，可能是文件的问题，
代码我看了，也没有特殊的地方，除了
`JSONObject.parseObject(JSON.toJSONString(data)).getString("neName");`
有点迷惑……

**Comment by SuperQiangYuan** [comment]
果然是数据有问题。。。谢谢您啦
