### ISSUE TITLE
在使用动态head的时候出现问题

### ISSUE THREAD

**Issue by llk2014** [alibaba/easyexcel#881]
**异常代码**
ArrayList<List<String>> lists = new ArrayList<>();
lists.add(Collections.singletonList("区域名称"));
```
**异常提示**
java.lang.UnsupportedOperationException: null
	at java.util.AbstractList.add(AbstractList.java:148)
	at java.util.AbstractList.add(AbstractList.java:108)
	at com.alibaba.excel.metadata.property.ExcelHeadProperty.initHeadRowNumber(ExcelHeadProperty.java:113)
	at com.alibaba.excel.metadata.property.ExcelHeadProperty.<init>(ExcelHeadProperty.java:93)
	at com.alibaba.excel.write.property.ExcelWriteHeadProperty.<init>(ExcelWriteHeadProperty.java:36)
	at com.alibaba.excel.write.metadata.holder.AbstractWriteHolder.<init>(AbstractWriteHolder.java:166)
	at com.alibaba.excel.write.metadata.holder.WriteSheetHolder.<init>(WriteSheetHolder.java:68)
	at com.alibaba.excel.context.WriteContextImpl.initCurrentSheetHolder(WriteContextImpl.java:135)
	at com.alibaba.excel.context.WriteContextImpl.currentSheet(WriteContextImpl.java:128)
	at com.alibaba.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl.java:56)
	at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:161)
	at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:146)
	at com.alibaba.excel.write.builder.ExcelWriterSheetBuilder.doWrite(ExcelWriterSheetBuilder.java:190)

**建议描述**
当我使用这个方法去写入头的时候，会导致如上问题，原因是SingletonList没有实现AbstractList的add方法，这可能是个不算问题的问题。

顺便还有一个请求：
我看到使用动态请求头的话会导致类上使用的类型转换失效，这个可以不可以支持，我想既使用动态head，又使用注解或者别的什么方式来做类型转换，而不是我转换后再进行输出。
You can only choose one of the {@link ExcelWriterSheetBuilder#head(List)} and
     * {@link ExcelWriterSheetBuilder#head(Class)}

感谢大佬的工具

**Comment by pdkst** [comment]
空指针的问题我尝试修复一下
动态表头那个我看了一下，理论上workbook页上用`com.alibaba.excel.write.builder.ExcelWriterBuilder#head(java.util.List<java.util.List<java.lang.String>>)`的话，workbook的headClass会生效，sheet页上用`com.alibaba.excel.write.builder.ExcelWriterSheetBuilder#head(java.util.List<java.util.List<java.lang.String>>)`的话sheet页的headClass理论上会生效，这个我没有试验
既想使用head，又想使用注解的话，推荐使用table，顺序一样关闭table的head就没有区别了
[官方demo-使用table去写入](https://alibaba-easyexcel.github.io/quickstart/write.html#%E4%BD%BF%E7%94%A8table%E5%8E%BB%E5%86%99%E5%85%A5)

**Comment by llk2014** [comment]
已解决，感谢大佬，分成2个table写入以后就没问题了

ExcelWriter excelWriter = EasyExcel.write(response.getOutputStream(), SalaryAreaManagedRiskStatDailyVO.class).build();
            WriteSheet writeSheet = EasyExcel.writerSheet("sheet").needHead(Boolean.FALSE).build();
            WriteTable writeTable0 = EasyExcel.writerTable(0).needHead(Boolean.TRUE).head(getHead(queryDTO.getRptdate())).build();
            WriteTable writeTable1 = EasyExcel.writerTable(1).needHead(Boolean.FALSE).excludeColumnFiledNames(Arrays.asList("areaCde")).build();
            excelWriter.write(new ArrayList(), writeSheet, writeTable0);
            excelWriter.write(list, writeSheet, writeTable1);
            excelWriter.finish();
