### ISSUE TITLE
在读取Excel文本数据，例如20800.0，会让com.alibaba.excel.util.NumberUtils这个工具类处理，结果报错解析异常

### ISSUE THREAD

**Issue by HK-Kerwin** [alibaba/easyexcel#941]
**触发场景描述**
1、依赖版本
       <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>easyexcel</artifactId>
            <version>2.1.4</version>
        </dependency>
ps：2.1.3版本也试过，一样的情况，目前2.1.3
2、Excel有24个字段，表格全部都为文本类型，6、7、8、9列数据为20800.0带小数点文本
3、继承com.alibaba.excel.event.AnalysisEventListener的监听对象，重写了 invoke()方法 
4、按照文档代码解析对象到List集合，并未存数据库
**触发Bug的代码**
```java
--------------------------------------------------分割线-------------------------------------------------
   package com.tedu.sois.common.listener;

import com.alibaba.excel.context.AnalysisContext;
import com.alibaba.excel.event.AnalysisEventListener;
import com.alibaba.fastjson.JSON;
import com.tedu.sois.sys.entity.DemoData;
import com.tedu.sois.sys.entity.SysStuCrmManageTemporary;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.List;
/**
测试监听对象
*/
public class DemoListener extends AnalysisEventListener<SysStuCrmManageTemporary> {
    private static final Logger LOGGER = LoggerFactory.getLogger(DemoListener.class);

    /**
     * 每隔3000条存储数据库，然后清理list ，方便内存回收
     */
//    private static final int BATCH_COUNT = 1000;

    List<DemoData> list = new ArrayList<>();

    @Override
    public void invoke(SysStuCrmManageTemporary sysStuCrmManageTemporary, AnalysisContext analysisContext) {
        if(!("正式学员".equals(sysStuCrmManageTemporary.getColumn4()) ||
                "毕业学员".equals(sysStuCrmManageTemporary.getColumn4())))
            return;
        LOGGER.info("解析到一条数据:{}", JSON.toJSONString(sysStuCrmManageTemporary));
        DemoData data = new DemoData();
        data.setCost_all(sysStuCrmManageTemporary.getColumn6());
        data.setCost_value(sysStuCrmManageTemporary.getColumn9());
        list.add(data);
    }

    @Override
    public void doAfterAllAnalysed(AnalysisContext analysisContext) {
        LOGGER.info("所有数据解析完毕");
    }

//    @Override
//    public void onException(Exception exception, AnalysisContext context) {
//        LOGGER.error("解析失败，但是继续解析下一行:{}", exception.getMessage());
//        // 如果是某一个单元格的转换异常 能获取到具体行号
//        // 如果要获取头的信息 配合invokeHeadMap使用
//        if (exception instanceof ExcelDataConvertException) {
//            ExcelDataConvertException excelDataConvertException = (ExcelDataConvertException)exception;
//            LOGGER.error("第{}行，第{}列解析异常", excelDataConvertException.getRowIndex(),
//                    excelDataConvertException.getColumnIndex());
//        }
//    }

    public List<DemoData> getList(){
        return list;
    }
}
--------------------------------------------------分割线-------------------------------------------------
package com.tedu.sois.sys.entity;

import lombok.Data;
import lombok.ToString;

import java.io.Serializable;

/**
 * 临时表实体对象
 */
@Data
@ToString
public class SysStuCrmManageTemporary implements Serializable {

    private String column0;
    private String column1;
    private String column2;
    private String column3;
    private String column4;
    private String column5;
    private Double column6;
    private Double column7;
    private Double column8;
    private Double column9;
    private String column10;
    private String column11;
    private String column12;
    private String column13;
    private String column14;
    private String column15;
    private String column16;
    private String column17;
    private String column18;
    private String column19;
    private String column20;
    private String column21;
    private String column22;
}
--------------------------------------------------分割线-------------------------------------------------
package com.tedu.sois.sys.entity;

import com.alibaba.excel.annotation.ExcelProperty;
import com.alibaba.excel.annotation.format.NumberFormat;
import lombok.Data;
import lombok.ToString;

import java.io.Serializable;

@Data
@ToString
public class DemoData implements Serializable {
    @NumberFormat("#.#")
    @ExcelProperty(value = "学费总值",index = 6)
    private Double cost_value;

    @NumberFormat("#.#")
    @ExcelProperty(value = "累计缴费",index = 9)
    private Double cost_all;
}

```
**提示的异常或者没有达到的效果**
com.alibaba.excel.exception.ExcelAnalysisException: Convert data 20800.0 to class java.lang.Integer error 

	at com.alibaba.excel.read.metadata.holder.AbstractReadHolder.notifyEndOneRow(AbstractReadHolder.java:151)
	at com.alibaba.excel.analysis.v03.XlsSaxAnalyser.endRow(XlsSaxAnalyser.java:193)
	at com.alibaba.excel.analysis.v03.XlsSaxAnalyser.processLastCellOfRow(XlsSaxAnalyser.java:183)
	at com.alibaba.excel.analysis.v03.XlsSaxAnalyser.processRecord(XlsSaxAnalyser.java:172)
	at org.apache.poi.hssf.eventusermodel.MissingRecordAwareHSSFListener.processRecord(MissingRecordAwareHSSFListener.java:158)
	at org.apache.poi.hssf.eventusermodel.FormatTrackingHSSFListener.processRecord(FormatTrackingHSSFListener.java:92)
	at org.apache.poi.hssf.eventusermodel.HSSFRequest.processRecord(HSSFRequest.java:109)
	at org.apache.poi.hssf.eventusermodel.HSSFEventFactory.genericProcessEvents(HSSFEventFactory.java:179)
	at org.apache.poi.hssf.eventusermodel.HSSFEventFactory.processEvents(HSSFEventFactory.java:136)
	at org.apache.poi.hssf.eventusermodel.HSSFEventFactory.processWorkbookEvents(HSSFEventFactory.java:82)
	at org.apache.poi.hssf.eventusermodel.HSSFEventFactory.processWorkbookEvents(HSSFEventFactory.java:54)
	at com.alibaba.excel.analysis.v03.XlsSaxAnalyser.execute(XlsSaxAnalyser.java:112)
	at com.alibaba.excel.analysis.ExcelAnalyserImpl.analysis(ExcelAnalyserImpl.java:105)
	at com.alibaba.excel.ExcelReader.read(ExcelReader.java:180)
	at com.alibaba.excel.ExcelReader.read(ExcelReader.java:170)
	at com.alibaba.excel.read.builder.ExcelReaderSheetBuilder.doRead(ExcelReaderSheetBuilder.java:160)
	at com.tedu.sois.service.SysStuCrmManageServiceTestCase.reader(SysStuCrmManageServiceTestCase.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.alibaba.excel.exception.ExcelDataConvertException: Convert data 20800.0 to class java.lang.Integer error 
	at com.alibaba.excel.util.ConverterUtils.doConvertToJavaObject(ConverterUtils.java:135)
	at com.alibaba.excel.util.ConverterUtils.convertToJavaObject(ConverterUtils.java:103)
	at com.alibaba.excel.read.listener.ModelBuildEventListener.buildUserModel(ModelBuildEventListener.java:113)
	at com.alibaba.excel.read.listener.ModelBuildEventListener.invoke(ModelBuildEventListener.java:38)
	at com.alibaba.excel.read.listener.ModelBuildEventListener.invoke(ModelBuildEventListener.java:28)
	at com.alibaba.excel.read.metadata.holder.AbstractReadHolder.notifyEndOneRow(AbstractReadHolder.java:145)
	... 46 more
Caused by: java.lang.NumberFormatException: For input string: "20800.0"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at com.alibaba.excel.util.NumberUtils.parseInteger(NumberUtils.java:90)
	at com.alibaba.excel.converters.integer.IntegerStringConverter.convertToJavaData(IntegerStringConverter.java:32)
	at com.alibaba.excel.converters.integer.IntegerStringConverter.convertToJavaData(IntegerStringConverter.java:17)
	at com.alibaba.excel.util.ConverterUtils.doConvertToJavaObject(ConverterUtils.java:133)
	... 51 more

**Comment by zhuangjiaju** [comment]
请检查您的对象。目前来看 您肯定用integer去接收了

**Comment by HK-Kerwin** [comment]
并不是喔。之后我全部用String类型，指定excel单元格接收位置，但是依然是这样，不过我后面换了一个思路，虽然会比较麻烦，但是可以解决我的需求。如同我上方粘贴的代码，创建全字段实体对象进行监听，接收到excel表数据后，把监听对象某些属性的值set到我需要的字段的对象里。因为表数据4000条左右，性能和并发不用考虑，所以这个思路解决了我的需求，如果其他人的情况和我相似，可以参考这样做。
