### ISSUE TITLE
无法处理BigInteger 

### ISSUE THREAD

**Issue by xiaochanglaoshi** [alibaba/easyexcel#963]
**异常代码**

 
##  实体类 
```
@Data
public class DemoData {
    @ExcelProperty("字符串标题")
    private String string;
    @ExcelProperty("日期标题")
    private Date date;
    @ExcelProperty("数字标题")
    private Double doubleData;
    @ExcelProperty("bigIntegerData")
    private BigInteger bigIntegerData;
    /**
     * 忽略这个字段
     */
    @ExcelIgnore
    private String ignore;
} 
```
## 数据 
```
    private List<DemoData> data() {
        List<DemoData> list = new ArrayList<DemoData>();
        for (int i = 0; i < 10; i++) {
            DemoData data = new DemoData();
            data.setString("字符串" + i);
            data.setDate(new Date());
            data.setDoubleData(0.56);
            data.setBigIntegerData(  new BigInteger(System.currentTimeMillis()+"" ) );
            list.add(data);
        }
        return list;
    } 
```

## 执行代码 
```
   @Test
    public void customHandlerWrite() {
        String fileName = TestFileUtil.getPath() + "customHandlerWrite" + System.currentTimeMillis() + ".xlsx";
        // 这里 需要指定写用哪个class去写，然后写到第一个sheet，名字为模板 然后文件流会自动关闭
        EasyExcel.write(fileName, DemoData.class).registerWriteHandler(new CustomSheetWriteHandler())
            .registerWriteHandler(new CustomCellWriteHandler()).sheet("模板").doWrite(data());

    }

```

```
**异常提示**
com.alibaba.excel.exception.ExcelDataConvertException: Can not find 'Converter' support class BigInteger.

	at com.alibaba.excel.write.executor.AbstractExcelWriteExecutor.doConvert(AbstractExcelWriteExecutor.java:108)
	at com.alibaba.excel.write.executor.AbstractExcelWriteExecutor.convert(AbstractExcelWriteExecutor.java:93)
	at com.alibaba.excel.write.executor.AbstractExcelWriteExecutor.converterAndSet(AbstractExcelWriteExecutor.java:39)
	at com.alibaba.excel.write.executor.ExcelWriteAddExecutor.addJavaObjectToExcel(ExcelWriteAddExecutor.java:137)
	at com.alibaba.excel.write.executor.ExcelWriteAddExecutor.addOneRowOfDataToExcel(ExcelWriteAddExecutor.java:65)
	at com.alibaba.excel.write.executor.ExcelWriteAddExecutor.add(ExcelWriteAddExecutor.java:51)
	at com.alibaba.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl.java:61)
	at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:161)
	at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:146)
	at com.alibaba.excel.write.builder.ExcelWriterSheetBuilder.doWrite(ExcelWriterSheetBuilder.java:190)
	at com.alibaba.easyexcel.test.demo.write.WriteTest.customHandlerWrite(WriteTest.java:424)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)


## **建议描述**
1.希望能默认加入支持BigInteger 类型转换 ,理由是jpa 默认查询从的long 会被转成BigInteger

**Comment by yanchuang-16** [comment]
我尝试写了下，感觉不是很必要。你可以看看[issue963](https://github.com/yanchuang-16/easyexcel/tree/issue963)

**Comment by yanchuang-16** [comment]
![excel](https://user-images.githubusercontent.com/19201393/70439845-d4da9700-1acb-11ea-8195-34266271e728.png)
你要是想用可以自己打包用

**Comment by xiaochanglaoshi** [comment]
> 我尝试写了下，感觉不是很必要。你可以看看[issue963](https://github.com/yanchuang-16/easyexcel/tree/issue963)

我个人觉得  需要加入 BigInteger 类型的支持 ,主要是为了 方便jpa 调用,不过从全局的角度来说又是相对多余的

**Comment by xiaochanglaoshi** [comment]
> ![excel](https://user-images.githubusercontent.com/19201393/70439845-d4da9700-1acb-11ea-8195-34266271e728.png)
> 你要是想用可以自己打包用

感谢  我试一下

**Comment by zhuangjiaju** [comment]
可以考虑加入

**Comment by KID0031** [comment]
开发者您好，我们希望可以完善一下这个issue

**Comment by KID0031** [comment]
开发者您好，我们希望可以完善一下这个issue，请问可以分配给我们吗

**Comment by KID0031** [comment]
可以通过设置converter解决 #1864

**Comment by KID0031** [comment]
可以通过设置converter解决

**Comment by KID0031** [comment]
> 可以通过设置converter解决

#1864

**Comment by zhuangjiaju** [comment]
已经在`3.0.0-beta1` 版本修复，beta版本会在一个月内升级成正式版。
