### ISSUE TITLE
使用lombok @Builder 映射不到实体

### ISSUE THREAD

**Issue by Vetich** [alibaba/easyexcel#972]
**触发场景描述**
读取映射
**触发Bug的代码**
```java
@Builder
@Data
@Entity
@Table(name = "tsccheck_on_work")
public class AttendSheet implements Serializable {
```
**提示的异常或者没有达到的效果**
Caused by: java.lang.IllegalAccessException: Class com.alibaba.excel.read.listener.ModelBuildEventListener can not access a member of class com.demo with modifiers ""
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
	at java.lang.Class.newInstance(Class.java:436)
	at com.alibaba.excel.read.listener.ModelBuildEventListener.buildUserModel(ModelBuildEventListener.java:94)
	... 47 more

**Comment by Kaiser-Wu** [comment]
注意 lombok 的版本，加上 有参和全参构造试试

**Comment by zhuangjiaju** [comment]
目前必须使用 无参构造 函数。后续可能会考虑支持
