### ISSUE TITLE
excel并发写出现异常异常ExcelDataConvertException: Can not find 'Converter' support class String.  

### ISSUE THREAD

**Issue by wsh759146139** [alibaba/easyexcel#977]
**触发场景描述**
在做excel导出压力测试时，出现异常：com.alibaba.excel.exception.ExcelDataConvertException: Can not find 'Converter' support class String.
**触发Bug的代码**
```java
try (ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {
    EasyExcel.write(outputStream).sheet().doWrite(sampleResp.getData().getData());
    //....
}
```
**提示的异常或者没有达到的效果**
异常堆栈如下：
```
Caused by: com.alibaba.excel.exception.ExcelDataConvertException: Can not find 'Converter' support class String.
        at com.alibaba.excel.write.ExcelBuilderImpl.convert(ExcelBuilderImpl.java:366)
        at com.alibaba.excel.write.ExcelBuilderImpl.converterAndSet(ExcelBuilderImpl.java:304)
        at com.alibaba.excel.write.ExcelBuilderImpl.doAddBasicTypeToExcel(ExcelBuilderImpl.java:195)
        at com.alibaba.excel.write.ExcelBuilderImpl.addBasicTypeToExcel(ExcelBuilderImpl.java:185)
        at com.alibaba.excel.write.ExcelBuilderImpl.addOneRowOfDataToExcel(ExcelBuilderImpl.java:126)
        at com.alibaba.excel.write.ExcelBuilderImpl.doAddContent(ExcelBuilderImpl.java:79)
        at com.alibaba.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl.java:93)
        at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:155)
        at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:140)
        at com.alibaba.excel.write.builder.ExcelWriterSheetBuilder.doWrite(ExcelWriterSheetBuilder.java:134)
        at com.haixue.datamart.biz.TaskExecuteBiz.estimateFileSize(TaskExecuteBiz.java:156)
        at com.haixue.datamart.biz.TaskExecuteBiz.preCheck(TaskExecuteBiz.java:113)
```
跟代码发现`DefaultConverterLoader.loadDefaultWriteConverter()`方法是非线程安全的，不确定是否因为此方法导致出现该异常？

**Comment by zhuangjiaju** [comment]
对。这个应该就是bug,建议处理方案启动的时候先load一下。下个 版本会修复。

**Comment by wsh759146139** [comment]
谢谢，那我这边先这样处理。
